@echo off
rem //build Nov 11-23
rem //Nintendo - Nintendo 64 (BigEndian) (Parent-Clone) (20230921-114440)

md _MOVED_ROMS
move "1080 Snowboarding (USA) (En,Ja) (LodgeNet).zip" _MOVED_ROMS\
move "2048 (World) (En,Fr,Es) (Aftermarket) (Unl).zip" _MOVED_ROMS\
rem //move "40 Winks (USA) (Aftermarket) (Unl).zip" _MOVED_ROMS\
move "Action Replay Pro 64 (Europe) (v3.0) (Unl).zip" _MOVED_ROMS\
move "Action Replay Pro 64 (Europe) (v3.3) (Unl).zip" _MOVED_ROMS\
move "Cruis'n USA (USA) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Donkey Kong 64 (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Donsol (World) (Aftermarket) (Unl).zip" _MOVED_ROMS\
move "Dr. Mario 64 (USA) (LodgeNet).zip" _MOVED_ROMS\
move "EEPROM & SRAM Erase Program (USA) (v1.2) (LodgeNet).zip" _MOVED_ROMS\
move "Excitebike 64 (USA) (LodgeNet).zip" _MOVED_ROMS\
move "F-Zero X (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Fission Failure 64 (World) (Aftermarket) (Unl).zip" _MOVED_ROMS\
move "Flood64 (World) (En,Fr,Es) (Aftermarket) (Unl).zip" _MOVED_ROMS\
move "GameBooster 64 (Europe) (v1.1) (Unl).zip" _MOVED_ROMS\
move "GameBooster 64 (USA) (v1.1) (Unl).zip" _MOVED_ROMS\
move "GameShark Pro (USA) (v2.0) (Unl).zip" _MOVED_ROMS\
move "GameShark Pro (USA) (v3.3) (Unl).zip" _MOVED_ROMS\
move "Gauntlet Legends (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Glamorous Zombie Flakes (World) (Aftermarket) (Unl).zip" _MOVED_ROMS\
move "GoldenEye 007 (USA, Europe) (Switch Online).zip" _MOVED_ROMS\
move "Hydro Thunder (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Kirby 64 - The Crystal Shards (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Legend of Zelda, The - Majora's Mask (Europe) (En,Fr,De,Es) (Rev 1) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Legend of Zelda, The - Majora's Mask (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Legend of Zelda, The - Ocarina of Time (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Legend of Zelda, The - The Sealed Palace (USA) (v1.21) (Aftermarket) (Pirate).zip" _MOVED_ROMS\
move "Legend of Zelda, The - The Sealed Palace (USA) (v1.3) (Aftermarket) (Pirate).zip" _MOVED_ROMS\
move "Mario Golf (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Mario Kart 64 (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Mario Party 2 (Europe) (En,Fr,De,Es,It) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Mario Party 2 (Japan) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Mario Party 2 (USA) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Mario Party 3 (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Mario Tennis (Europe) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Mario Tennis (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Mario Tennis (USA) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Mario Tennis 64 (Japan) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Midway's Greatest Arcade Hits - Volume 1 (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Mortal Kombat 4 (USA) (LodgeNet).zip" _MOVED_ROMS\
move "New Tetris, The (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Ogre Battle 64 - Person of Lordly Caliber (Japan) (Rev 1) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Ogre Battle 64 - Person of Lordly Caliber (USA, Europe) (Rev 1) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Paper Mario (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Pilotwings 64 (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Pokemon Puzzle League (Europe) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Pokemon Puzzle League (France) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Pokemon Puzzle League (Germany) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Pokemon Puzzle League (USA) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Pokemon Snap (Japan) (Rev 1) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Pokemon Snap (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Pyoro 64 (Unknown) (MPAL) (Aftermarket) (Unl).zip" _MOVED_ROMS\
move "Pyoro 64 (Unknown) (NTSC) (Aftermarket) (Unl).zip" _MOVED_ROMS\
move "Pyoro 64 (Unknown) (PAL) (Aftermarket) (Unl).zip" _MOVED_ROMS\
move "Rampage 2 - Universal Tour (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Ready 2 Rumble Boxing (USA) (LodgeNet).zip" _MOVED_ROMS\
rem // move "Ronaldinho's Soccer 64 (Brazil) (Pirate).zip" _MOVED_ROMS\
move "Rush 2 - Extreme Racing USA (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Sblobber 64 (World) (Aftermarket) (Unl).zip" _MOVED_ROMS\
move "Star Fox 64 (Japan) (Rev 1) (Wii Virtual Console).zip" _MOVED_ROMS\
move "Star Fox 64 (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Star Wars - Rogue Squadron (USA) (LodgeNet).zip" _MOVED_ROMS\
rem // move "Star Wars - Shadows of the Empire (USA) (Aftermarket) (Unl).zip" _MOVED_ROMS\
rem // move "Star Wars Episode I - Racer (USA) (Aftermarket) (Unl).zip" _MOVED_ROMS\
move "Styx (World) (Aftermarket) (Unl).zip" _MOVED_ROMS\
move "Super Mario 64 (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Super Smash Bros. (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Swoop 64, The (World) (Aftermarket) (Unl).zip" _MOVED_ROMS\
move "Telocation - Gemini (World) (v1.2) (Aftermarket) (Unl).zip" _MOVED_ROMS\
move "Virtual Chess 64 (USA) (En,Fr,Es) (LodgeNet).zip" _MOVED_ROMS\
move "Virtual Pool 64 (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Wave Race 64 - Kawasaki Jet Ski (USA) (LodgeNet).zip" _MOVED_ROMS\
move "Wizard of the Board (World) (NTSC) (Aftermarket) (Unl).zip" _MOVED_ROMS\
move "Wizard of the Board (World) (PAL) (Aftermarket) (Unl).zip" _MOVED_ROMS\
move "Xplorer 64 (Germany) (v1.067) (Unl).zip" _MOVED_ROMS\
move "Yoshi's Story (USA) (En,Ja) (LodgeNet).zip" _MOVED_ROMS\
move "[BIOS] Nintendo 64 - PIF (Brazil).zip" _MOVED_ROMS\
move "[BIOS] Nintendo 64 - PIF (Europe).zip" _MOVED_ROMS\
move "[BIOS] Nintendo 64 - PIF (Japan, USA).zip" _MOVED_ROMS\
move "Nintendo 64 Modem (Japan) (Add-on).zip" _MOVED_ROMS\
move "Turok - Dinosaur Hunter (USA) (Demo) (Kiosk, E3 1997).zip" _MOVED_ROMS\
move "Doom 64 (USA) (Beta) (1996-12-10).zip" _MOVED_ROMS\
move "Turok - Dinosaur Hunter (Europe) (Rev 1).zip" _MOVED_ROMS\
move "Turok - Dinosaur Hunter (USA) (Rev 1).zip" _MOVED_ROMS\
move "Turok - Dinosaur Hunter (USA) (Rev 2).zip" _MOVED_ROMS\
move "Turok - Dinosaur Hunter (Germany) (Rev 2).zip" _MOVED_ROMS\
move "Zelda no Densetsu - Toki no Ocarina (Japan) (Rev 2).zip" _MOVED_ROMS\
move "Turok 3 - Shadow of Oblivion (USA) (Beta) (2000-07-18).zip" _MOVED_ROMS\
move "Turok 3 - Shadow of Oblivion (Europe) (Beta) (2000-07-16T211412).zip" _MOVED_ROMS\
move "F-Zero X (USA) (Beta) (The Legend of Zelda - Ocarina of Time leftover data).zip" _MOVED_ROMS\
move "Blues Brothers 2000 (Europe) (En,Fr,De,Es,It,Nl) (Beta) (2000-01-15) (#53).zip" _MOVED_ROMS\
move "SpaceStation Silicon Valley (Japan) (Proto).zip" _MOVED_ROMS\
move "South Park - Chef's Luv Shack (USA).zip" _MOVED_ROMS\
move "FIFA Soccer 64 (USA) (En,Fr,De).zip" _MOVED_ROMS\
move "F-1 World Grand Prix (Europe) (Beta).zip" _MOVED_ROMS\
move "Wetrix (USA) (En,Fr,De,Es,It,Nl).zip" _MOVED_ROMS\
move "Zelda no Densetsu - Toki no Ocarina (Japan) (Rev 1).zip" _MOVED_ROMS\
move "Turok 2 - Seeds of Evil (USA) (Rev 1).zip" _MOVED_ROMS\
move "Turok 2 - Seeds of Evil (Europe) (Demo) (Kiosk).zip" _MOVED_ROMS\
move "Zelda no Densetsu - Toki no Ocarina (Japan).zip" _MOVED_ROMS\
move "SpaceStation Silicon Valley (USA) (Rev 1).zip" _MOVED_ROMS\
move "Powerpuff Girls, The - Chemical X-Traction (USA) (Beta) (2001-09-27).zip" _MOVED_ROMS\

cls
choice /m "do you want to rename to FATX?"
if %errorlevel% equ 2 exit

md _REN

move "40 Winks (USA) (Aftermarket) (Unl).zip" "_REN\40 Winks (U) (Aftermarket) (Unl).zip"
move "Ronaldinho's Soccer 64 (Brazil) (Pirate).zip" "_REN\Ronaldinho's Soccer 64 (B) (Pirate).zip"
move "Star Wars - Shadows of the Empire (USA) (Aftermarket) (Unl).zip" "_REN\StarWarsEpisodeIRacer(U)(Unl).zip"
move "Star Wars Episode I - Racer (USA) (Aftermarket) (Unl).zip" "_REN\StarWarsShadowsoftheEmpire(U)(Unl).zip"

move "007 - The World Is Not Enough (Europe) (En,Fr,De).zip" "_REN\007-TheWorldIsNotEnough(E)(EnFrDe).zip"
move "007 - The World Is Not Enough (USA) (v2) (Beta).zip" "_REN\007-TheWorldIsNotEnough(U)(v2)(Beta).zip"
move "007 - The World Is Not Enough (USA) (v21) (Beta).zip" "_REN\007-TheWorldIsNotEnough(U)(v21)(Beta).zip"
move "007 - The World Is Not Enough (USA).zip" "_REN\007 - The World Is Not Enough (U).zip"
move "1080 Snowboarding (Europe) (En,Ja,Fr,De).zip" "_REN\1080 Snowboarding (E) (EnJaFrDe).zip"
move "1080 Snowboarding (Japan, USA) (En,Ja).zip" "_REN\1080 Snowboarding (Japan USA) (EnJa).zip"
move "3D Model RGB Test Program (USA) (Test Program).zip" "_REN\3DModelRGBTestProgram(U)(TestProgram).zip"
move "40 Winks (Europe) (En,Es,It) (Proto) (1999-10-07).zip" "_REN\40Winks(E)(EnEsIt)(Proto)(1999-10-07).zip"
move "40 Winks (USA) (Proto) (2000-01-10).zip" "_REN\40 Winks (U) (Proto) (2000-01-10).zip"
move "64 de Hakken!! Tamagotchi - Minna de Tamagotchi World (Japan).zip" "_REN\64deHakkenTamagotchiMinnadeTamagotc(J).zip"
move "64 Hanafuda - Tenshi no Yakusoku (Japan).zip" "_REN\64 Hanafuda - Tenshi no Yakusoku (J).zip"
move "64 Oozumou (Japan).zip" "_REN\64 Oozumou (J).zip"
move "64 Oozumou 2 (Japan).zip" "_REN\64 Oozumou 2 (J).zip"
move "64 Trump Collection - Alice no Wakuwaku Trump World (Japan).zip" "_REN\64TrumpCollectionAlicenoWakuwakuTru(J).zip"
move "AeroFighters Assault (Europe) (En,Fr,De).zip" "_REN\AeroFighters Assault (E) (EnFrDe).zip"
move "AeroFighters Assault (USA).zip" "_REN\AeroFighters Assault (U).zip"
move "AeroGauge (Europe) (En,Fr,De).zip" "_REN\AeroGauge (E) (EnFrDe).zip"
move "AeroGauge (Japan) (Demo) (Kiosk).zip" "_REN\AeroGauge (J) (Demo) (Kiosk).zip"
move "AeroGauge (Japan) (Rev 1).zip" "_REN\AeroGauge (J) (Rev 1).zip"
move "AeroGauge (USA).zip" "_REN\AeroGauge (U).zip"
move "AI Shougi 3 (Japan).zip" "_REN\AI Shougi 3 (J).zip"
move "Aidyn Chronicles - The First Mage (Europe) (Beta) (2001-03-02).zip" "_REN\AidynChroniclesTheFirstMage(E)(Beta).zip"
move "Aidyn Chronicles - The First Mage (Europe) (Beta) (2001-04-10).zip" "_REN\AidynChroniclesTheFirstMage(E)(Beta)_0.zip"
move "Aidyn Chronicles - The First Mage (Europe).zip" "_REN\Aidyn Chronicles - The First Mage (E).zip"
move "Aidyn Chronicles - The First Mage (USA) (Beta) (2000-02-10).zip" "_REN\AidynChroniclesTheFirstMage(U)(Beta).zip"
move "Aidyn Chronicles - The First Mage (USA) (Beta) (2000-05-09).zip" "_REN\AidynChroniclesTheFirstMage(U)(Beta)_0.zip"
move "Aidyn Chronicles - The First Mage (USA) (Beta) (2000-12-05).zip" "_REN\AidynChroniclesTheFirstMage(U)(Beta)_1.zip"
move "Aidyn Chronicles - The First Mage (USA) (Rev 1).zip" "_REN\AidynChronicles-TheFirstMage(U)(Rev1).zip"
move "Aidyn Chronicles - The First Mage (USA).zip" "_REN\Aidyn Chronicles - The First Mage (U).zip"
move "Air Boarder 64 (Japan).zip" "_REN\Air Boarder 64 (J).zip"
move "Airboarder 64 (Europe).zip" "_REN\Airboarder 64 (E).zip"
move "Akumajou Dracula Mokushiroku - Real Action Adventure (Japan).zip" "_REN\AkumajouDraculaMokushirokuRealActio(J).zip"
move "Akumajou Dracula Mokushiroku Gaiden - Legend of Cornell (Japan).zip" "_REN\AkumajouDraculaMokushirokuGaidenLeg(J).zip"
move "All Star Tennis '99 (Europe) (En,Fr,De,Es,It).zip" "_REN\All Star Tennis '99 (E) (EnFrDeEsIt).zip"
move "All Star Tennis 99 (USA).zip" "_REN\All Star Tennis 99 (U).zip"
move "All-Star Baseball 2000 (Europe).zip" "_REN\All-Star Baseball 2000 (E).zip"
move "All-Star Baseball 2000 (USA).zip" "_REN\All-Star Baseball 2000 (U).zip"
move "All-Star Baseball 2001 (USA).zip" "_REN\All-Star Baseball 2001 (U).zip"
move "All-Star Baseball 99 (Europe).zip" "_REN\All-Star Baseball 99 (E).zip"
move "All-Star Baseball 99 (USA).zip" "_REN\All-Star Baseball 99 (U).zip"
move "Armorines - Project S.W.A.R.M. (Europe).zip" "_REN\Armorines - Project S.W.A.R.M. (E).zip"
move "Armorines - Project S.W.A.R.M. (Germany).zip" "_REN\Armorines - Project S.W.A.R.M. (G).zip"
move "Armorines - Project S.W.A.R.M. (USA).zip" "_REN\Armorines - Project S.W.A.R.M. (U).zip"
move "Army Men - Air Combat (USA).zip" "_REN\Army Men - Air Combat (U).zip"
move "Army Men - Sarge's Heroes (Europe) (En,Fr,De).zip" "_REN\Army Men - Sarge's Heroes (E) (EnFrDe).zip"
move "Army Men - Sarge's Heroes (USA).zip" "_REN\Army Men - Sarge's Heroes (U).zip"
move "Army Men - Sarge's Heroes 2 (USA).zip" "_REN\Army Men - Sarge's Heroes 2 (U).zip"
move "Asteroids Hyper 64 (USA).zip" "_REN\Asteroids Hyper 64 (U).zip"
move "Automobili Lamborghini (Europe).zip" "_REN\Automobili Lamborghini (E).zip"
move "Automobili Lamborghini (USA).zip" "_REN\Automobili Lamborghini (U).zip"
move "Baku Bomberman (Japan).zip" "_REN\Baku Bomberman (J).zip"
move "Baku Bomberman 2 (Japan).zip" "_REN\Baku Bomberman 2 (J).zip"
move "Bakuretsu Muteki Bangaioh (Japan).zip" "_REN\Bakuretsu Muteki Bangaioh (J).zip"
move "Bakushou Jinsei 64 - Mezase! Resort Ou (Japan).zip" "_REN\BakushouJinsei64-Mezase!ResortOu(J).zip"
move "Banjo to Kazooie no Daibouken (Japan).zip" "_REN\Banjo to Kazooie no Daibouken (J).zip"
move "Banjo to Kazooie no Daibouken 2 (Japan).zip" "_REN\Banjo to Kazooie no Daibouken 2 (J).zip"
move "Banjo-Kazooie (Europe) (En,Fr,De).zip" "_REN\Banjo-Kazooie (E) (EnFrDe).zip"
move "Banjo-Kazooie (USA) (Rev 1).zip" "_REN\Banjo-Kazooie (U) (Rev 1).zip"
move "Banjo-Kazooie (USA).zip" "_REN\Banjo-Kazooie (U).zip"
move "Banjo-Tooie (Australia).zip" "_REN\Banjo-Tooie (A).zip"
move "Banjo-Tooie (Europe) (En,Fr,De,Es).zip" "_REN\Banjo-Tooie (E) (EnFrDeEs).zip"
move "Banjo-Tooie (USA).zip" "_REN\Banjo-Tooie (U).zip"
move "Bass Rush - ECOGEAR PowerWorm Championship (Japan).zip" "_REN\BassRushECOGEARPowerWormChampionshi(J).zip"
move "Bassmasters 2000 (USA) (Beta).zip" "_REN\Bassmasters 2000 (U) (Beta).zip"
move "Bassmasters 2000 (USA).zip" "_REN\Bassmasters 2000 (U).zip"
move "Batman Beyond - Return of the Joker (USA).zip" "_REN\BatmanBeyond-ReturnoftheJoker(U).zip"
move "Batman of the Future - Return of the Joker (Europe) (En,Fr,De).zip" "_REN\BatmanoftheFutureReturnoftheJoker(E).zip"
move "BattleTanx (USA).zip" "_REN\BattleTanx (U).zip"
move "BattleTanx - Global Assault (Europe) (En,Fr,De).zip" "_REN\BattleTanx-GlobalAssault(E)(EnFrDe).zip"
move "BattleTanx - Global Assault (USA).zip" "_REN\BattleTanx - Global Assault (U).zip"
move "Battlezone - Rise of the Black Dogs (USA).zip" "_REN\Battlezone-RiseoftheBlackDogs(U).zip"
move "Beetle Adventure Racing! (Europe) (En,Fr,De).zip" "_REN\Beetle Adventure Racing! (E) (EnFrDe).zip"
move "Beetle Adventure Racing! (Japan).zip" "_REN\Beetle Adventure Racing! (J).zip"
move "Beetle Adventure Racing! (USA) (En,Fr,De).zip" "_REN\Beetle Adventure Racing! (U) (EnFrDe).zip"
move "Big Mountain 2000 (USA).zip" "_REN\Big Mountain 2000 (U).zip"
move "Bio F.R.E.A.K.S. (Europe).zip" "_REN\Bio F.R.E.A.K.S. (E).zip"
move "Bio F.R.E.A.K.S. (USA).zip" "_REN\Bio F.R.E.A.K.S. (U).zip"
move "Biohazard 2 (Japan).zip" "_REN\Biohazard 2 (J).zip"
move "Blast Corps (Europe) (En,De).zip" "_REN\Blast Corps (E) (EnDe).zip"
move "Blast Corps (USA) (Rev 1).zip" "_REN\Blast Corps (U) (Rev 1).zip"
move "Blast Corps (USA).zip" "_REN\Blast Corps (U).zip"
move "Blastdozer (Japan).zip" "_REN\Blastdozer (J).zip"
move "Blues Brothers 2000 (Europe) (En,Fr,De,Es,It,Nl) (Beta) (2000-01-15) (#20).zip" "_REN\BluesBrothers2000(E)(Beta).zip"
move "Blues Brothers 2000 (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN\Blues Brothers 2000 (E) (EnFrDeEsItNl).zip"
move "Blues Brothers 2000 (USA).zip" "_REN\Blues Brothers 2000 (U).zip"
move "Body Harvest (Europe) (En,Fr,De).zip" "_REN\Body Harvest (E) (EnFrDe).zip"
move "Body Harvest (USA).zip" "_REN\Body Harvest (U).zip"
move "Bokujou Monogatari 2 (Japan) (Rev 1).zip" "_REN\Bokujou Monogatari 2 (J) (Rev 1).zip"
move "Bokujou Monogatari 2 (Japan) (Rev 2).zip" "_REN\Bokujou Monogatari 2 (J) (Rev 2).zip"
move "Bokujou Monogatari 2 (Japan).zip" "_REN\Bokujou Monogatari 2 (J).zip"
move "Bomberman 64 (Europe).zip" "_REN\Bomberman 64 (E).zip"
move "Bomberman 64 (Japan).zip" "_REN\Bomberman 64 (J).zip"
move "Bomberman 64 (USA).zip" "_REN\Bomberman 64 (U).zip"
move "Bomberman 64 - The Second Attack! (USA).zip" "_REN\Bomberman 64 - The Second Attack! (U).zip"
move "Bomberman Hero (Europe).zip" "_REN\Bomberman Hero (E).zip"
move "Bomberman Hero (USA).zip" "_REN\Bomberman Hero (U).zip"
move "Bomberman Hero - Mirian Oujo o Sukue! (Japan).zip" "_REN\BombermanHero-MirianOujooSukue!(J).zip"
move "Bottom of the 9th (USA).zip" "_REN\Bottom of the 9th (U).zip"
move "Brunswick Circuit Pro Bowling (USA).zip" "_REN\Brunswick Circuit Pro Bowling (U).zip"
move "Buck Bumble (Europe) (En,Fr,De,Es,It).zip" "_REN\Buck Bumble (E) (EnFrDeEsIt).zip"
move "Buck Bumble (Japan).zip" "_REN\Buck Bumble (J).zip"
move "Buck Bumble (USA).zip" "_REN\Buck Bumble (U).zip"
move "Bug's Life, A (Europe).zip" "_REN\Bug's Life A (E).zip"
move "Bug's Life, A (France).zip" "_REN\Bug's Life A (F).zip"
move "Bug's Life, A (Germany).zip" "_REN\Bug's Life A (G).zip"
move "Bug's Life, A (Italy).zip" "_REN\Bug's Life A (I).zip"
move "Bug's Life, A (USA).zip" "_REN\Bug's Life A (U).zip"
move "Bust-A-Move '99 (USA).zip" "_REN\Bust-A-Move '99 (U).zip"
move "Bust-A-Move 2 - Arcade Edition (Europe).zip" "_REN\Bust-A-Move 2 - Arcade Edition (E).zip"
move "Bust-A-Move 2 - Arcade Edition (USA).zip" "_REN\Bust-A-Move 2 - Arcade Edition (U).zip"
move "Bust-A-Move 3 DX (Europe).zip" "_REN\Bust-A-Move 3 DX (E).zip"
move "California Speed (Europe) (Proto).zip" "_REN\California Speed (E) (Proto).zip"
move "California Speed (USA).zip" "_REN\California Speed (U).zip"
move "Carmageddon 64 (Europe) (En,Fr,De,Es).zip" "_REN\Carmageddon 64 (E) (EnFrDeEs).zip"
move "Carmageddon 64 (Europe) (En,Fr,Es,It).zip" "_REN\Carmageddon 64 (E) (EnFrEsIt).zip"
move "Carmageddon 64 (USA).zip" "_REN\Carmageddon 64 (U).zip"
move "Carnivale - Cenzo's Adventure (USA) (Proto) (2000-07-21).zip" "_REN\CarnivaleCenzosAdventure(U)(Proto).zip"
move "Castlevania (Europe) (En,Fr,De).zip" "_REN\Castlevania (E) (EnFrDe).zip"
move "Castlevania (USA) (Rev 1).zip" "_REN\Castlevania (U) (Rev 1).zip"
move "Castlevania (USA) (Rev 2).zip" "_REN\Castlevania (U) (Rev 2).zip"
move "Castlevania (USA).zip" "_REN\Castlevania (U).zip"
move "Castlevania - Legacy of Darkness (Europe) (En,Fr,De).zip" "_REN\CastlevaniaLegacyofDarkness(E)(EnFrDe).zip"
move "Castlevania - Legacy of Darkness (USA).zip" "_REN\Castlevania - Legacy of Darkness (U).zip"
move "Centre Court Tennis (Europe).zip" "_REN\Centre Court Tennis (E).zip"
move "Chameleon Twist (Europe).zip" "_REN\Chameleon Twist (E).zip"
move "Chameleon Twist (Japan).zip" "_REN\Chameleon Twist (J).zip"
move "Chameleon Twist (USA) (Rev 1).zip" "_REN\Chameleon Twist (U) (Rev 1).zip"
move "Chameleon Twist (USA).zip" "_REN\Chameleon Twist (U).zip"
move "Chameleon Twist 2 (Europe).zip" "_REN\Chameleon Twist 2 (E).zip"
move "Chameleon Twist 2 (Japan).zip" "_REN\Chameleon Twist 2 (J).zip"
move "Chameleon Twist 2 (USA).zip" "_REN\Chameleon Twist 2 (U).zip"
move "Charlie Blast's Territory (Europe).zip" "_REN\Charlie Blast's Territory (E).zip"
move "Charlie Blast's Territory (USA).zip" "_REN\Charlie Blast's Territory (U).zip"
move "Chopper Attack (Europe).zip" "_REN\Chopper Attack (E).zip"
move "Chopper Attack (USA).zip" "_REN\Chopper Attack (U).zip"
move "Choro Q 64 (Japan).zip" "_REN\Choro Q 64 (J).zip"
move "Choro Q 64 2 - Hacha Mecha Grand Prix Race (Japan).zip" "_REN\ChoroQ642-HachaMechaGrandPrixRace(J).zip"
move "Chou Kuukan Nighter Pro Yakyuu King (Japan).zip" "_REN\ChouKuukanNighterProYakyuuKing(J).zip"
move "Chou Kuukan Nighter Pro Yakyuu King 2 (Japan).zip" "_REN\ChouKuukanNighterProYakyuuKing2(J).zip"
move "Chou Snobo Kids (Japan).zip" "_REN\Chou Snobo Kids (J).zip"
move "City-Tour GP - Zen-Nihon GT Senshuken (Japan).zip" "_REN\City-TourGP-Zen-NihonGTSenshuken(J).zip"
move "Clay Fighter - Sculptor's Cut (USA).zip" "_REN\Clay Fighter - Sculptor's Cut (U).zip"
move "Clay Fighter 63 1-3 (Europe).zip" "_REN\Clay Fighter 63 1-3 (E).zip"
move "Clay Fighter 63 1-3 (USA) (Beta).zip" "_REN\Clay Fighter 63 1-3 (U) (Beta).zip"
move "Clay Fighter 63 1-3 (USA).zip" "_REN\Clay Fighter 63 1-3 (U).zip"
move "Command & Conquer (Europe) (En,Fr).zip" "_REN\Command & Conquer (E) (EnFr).zip"
move "Command & Conquer (Germany).zip" "_REN\Command & Conquer (G).zip"
move "Command & Conquer (USA).zip" "_REN\Command & Conquer (U).zip"
move "Conker's Bad Fur Day (Europe).zip" "_REN\Conker's Bad Fur Day (E).zip"
move "Conker's Bad Fur Day (USA) (Beta) (2000-08-26) (ECTS 2000).zip" "_REN\ConkersBadFurDay(U)(Beta).zip"
move "Conker's Bad Fur Day (USA) (Beta) (2000-10-25).zip" "_REN\Conker'sBadFurDay(U)(Beta)(2000-10-25).zip"
move "Conker's Bad Fur Day (USA).zip" "_REN\Conker's Bad Fur Day (U).zip"
move "Controller Kensa-ki NUS-yo N Cassette (Japan) (Test Program).zip" "_REN\ControllerKensakiNUSyoNCassette(J).zip"
move "Cruis'n Exotica (USA).zip" "_REN\Cruis'n Exotica (U).zip"
move "Cruis'n USA (Europe).zip" "_REN\Cruis'n USA (E).zip"
move "Cruis'n USA (USA) (Rev 1).zip" "_REN\Cruis'n USA (U) (Rev 1).zip"
move "Cruis'n USA (USA) (Rev 2).zip" "_REN\Cruis'n USA (U) (Rev 2).zip"
move "Cruis'n USA (USA).zip" "_REN\Cruis'n USA (U).zip"
move "Cruis'n World (Europe) (Rev 1).zip" "_REN\Cruis'n World (E) (Rev 1).zip"
move "Cruis'n World (Europe).zip" "_REN\Cruis'n World (E).zip"
move "Cruis'n World (USA).zip" "_REN\Cruis'n World (U).zip"
move "Custom Robo (Japan).zip" "_REN\Custom Robo (J).zip"
move "Custom Robo V2 (Japan).zip" "_REN\Custom Robo V2 (J).zip"
move "CyberTiger (Europe).zip" "_REN\CyberTiger (E).zip"
move "CyberTiger (USA).zip" "_REN\CyberTiger (U).zip"
move "Daffy Duck Starring as Duck Dodgers (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN\DaffyDuckStarringasDuckDodgers(E).zip"
move "Dance Dance Revolution - Disney Dancing Museum (Japan).zip" "_REN\DanceDanceRevolutionDisneyDancingMu(J).zip"
move "Dark Rift (Europe).zip" "_REN\Dark Rift (E).zip"
move "Dark Rift (USA).zip" "_REN\Dark Rift (U).zip"
move "Deadly Arts (USA).zip" "_REN\Deadly Arts (U).zip"
move "Defi au Tetris Magique (France).zip" "_REN\Defi au Tetris Magique (F).zip"
move "Densha de Go! 64 (Japan).zip" "_REN\Densha de Go! 64 (J).zip"
move "Derby Stallion 64 (Japan) (Beta) [b].zip" "_REN\Derby Stallion 64 (J) (Beta) [b].zip"
move "Derby Stallion 64 (Japan).zip" "_REN\Derby Stallion 64 (J).zip"
move "Destruction Derby 64 (Europe) (En,Fr,De).zip" "_REN\Destruction Derby 64 (E) (EnFrDe).zip"
move "Destruction Derby 64 (USA) (1998-07-31) (Beta).zip" "_REN\DestructionDerby64(U)(19980731)(Beta).zip"
move "Destruction Derby 64 (USA).zip" "_REN\Destruction Derby 64 (U).zip"
move "Dezaemon 3D (Japan).zip" "_REN\Dezaemon 3D (J).zip"
move "Diddy Kong Racing (Europe) (En,Fr,De) (Rev 1).zip" "_REN\Diddy Kong Racing (E) (EnFrDe) (Rev 1).zip"
move "Diddy Kong Racing (Europe) (En,Fr,De).zip" "_REN\Diddy Kong Racing (E) (EnFrDe).zip"
move "Diddy Kong Racing (Japan).zip" "_REN\Diddy Kong Racing (J).zip"
move "Diddy Kong Racing (USA) (En,Fr) (Rev 1).zip" "_REN\Diddy Kong Racing (U) (EnFr) (Rev 1).zip"
move "Diddy Kong Racing (USA) (En,Fr).zip" "_REN\Diddy Kong Racing (U) (EnFr).zip"
move "Die Hard 64 (USA) (Proto) (Level 1).zip" "_REN\Die Hard 64 (U) (Proto) (Level 1).zip"
move "Die Hard 64 (USA) (Proto) (Level 2).zip" "_REN\Die Hard 64 (U) (Proto) (Level 2).zip"
move "Die Hard 64 (USA) (Proto) (Level 3).zip" "_REN\Die Hard 64 (U) (Proto) (Level 3).zip"
move "Dinosaur Planet (USA) (Proto) (2000-12-01).zip" "_REN\DinosaurPlanet(U)(Proto)(2000-12-01).zip"
move "Donald Duck - Goin' Quackers (USA) (En,Fr,De,Es,It).zip" "_REN\DonaldDuckGoin'Quackers(U)(EnFrDeEsIt).zip"
move "Donald Duck - Quack Attack (Europe) (En,Fr,De,Es,It).zip" "_REN\DonaldDuck-QuackAttack(E)(EnFrDeEsIt).zip"
move "Donkey Kong 64 (Europe) (En,Fr,De,Es).zip" "_REN\Donkey Kong 64 (E) (EnFrDeEs).zip"
move "Donkey Kong 64 (Japan).zip" "_REN\Donkey Kong 64 (J).zip"
move "Donkey Kong 64 (USA) (Demo) (Kiosk).zip" "_REN\Donkey Kong 64 (U) (Demo) (Kiosk).zip"
move "Donkey Kong 64 (USA).zip" "_REN\Donkey Kong 64 (U).zip"
move "Doom 64 (Europe).zip" "_REN\Doom 64 (E).zip"
move "Doom 64 (Japan).zip" "_REN\Doom 64 (J).zip"
move "Doom 64 (USA) (Rev 1).zip" "_REN\Doom 64 (U) (Rev 1).zip"
move "Doom 64 (USA).zip" "_REN\Doom 64 (U).zip"
move "Doraemon - Nobita to 3tsu no Seireiseki (Japan).zip" "_REN\Doraemon-Nobitato3tsunoSeireiseki(J).zip"
move "Doraemon 2 - Nobita to Hikari no Shinden (Japan).zip" "_REN\Doraemon2-NobitatoHikarinoShinden(J).zip"
move "Doraemon 3 - Nobita no Machi SOS! (Japan).zip" "_REN\Doraemon 3 - Nobita no Machi SOS! (J).zip"
move "Doubutsu Banchou (Japan) (Proto).zip" "_REN\Doubutsu Banchou (J) (Proto).zip"
move "Doubutsu no Mori (Japan).zip" "_REN\Doubutsu no Mori (J).zip"
move "Dr. Mario 64 (USA).zip" "_REN\Dr. Mario 64 (U).zip"
move "Dragon Sword 64 (Europe) (Proto).zip" "_REN\Dragon Sword 64 (E) (Proto).zip"
move "Dragon Sword 64 (USA) (1999-08-25) (Proto).zip" "_REN\DragonSword64(U)(1999-08-25)(Proto).zip"
move "Dual Heroes (Europe).zip" "_REN\Dual Heroes (E).zip"
move "Dual Heroes (Japan).zip" "_REN\Dual Heroes (J).zip"
move "Dual Heroes (USA).zip" "_REN\Dual Heroes (U).zip"
move "Duck Dodgers Starring Daffy Duck (USA) (En,Fr,Es) (Beta) (2000-03-07).zip" "_REN\DuckDodgersStarringDaffyDuck(U)(Beta).zip"
move "Duck Dodgers Starring Daffy Duck (USA) (En,Fr,Es).zip" "_REN\DuckDodgersStarringDaffyDuck(U).zip"
move "Duke Nukem - Zero Hour (Europe).zip" "_REN\Duke Nukem - Zero Hour (E).zip"
move "Duke Nukem - Zero Hour (France).zip" "_REN\Duke Nukem - Zero Hour (F).zip"
move "Duke Nukem - Zero Hour (USA) (Beta).zip" "_REN\Duke Nukem - Zero Hour (U) (Beta).zip"
move "Duke Nukem - Zero Hour (USA).zip" "_REN\Duke Nukem - Zero Hour (U).zip"
move "Duke Nukem 64 (Europe) (Beta).zip" "_REN\Duke Nukem 64 (E) (Beta).zip"
move "Duke Nukem 64 (Europe).zip" "_REN\Duke Nukem 64 (E).zip"
move "Duke Nukem 64 (France).zip" "_REN\Duke Nukem 64 (F).zip"
move "Duke Nukem 64 (USA).zip" "_REN\Duke Nukem 64 (U).zip"
move "Earthworm Jim 3D (Europe) (En,Fr,De,Es,It).zip" "_REN\Earthworm Jim 3D (E) (EnFrDeEsIt).zip"
move "Earthworm Jim 3D (USA).zip" "_REN\Earthworm Jim 3D (U).zip"
move "ECW Hardcore Revolution (Europe).zip" "_REN\ECW Hardcore Revolution (E).zip"
move "ECW Hardcore Revolution (Germany).zip" "_REN\ECW Hardcore Revolution (G).zip"
move "ECW Hardcore Revolution (USA) (Beta).zip" "_REN\ECW Hardcore Revolution (U) (Beta).zip"
move "ECW Hardcore Revolution (USA).zip" "_REN\ECW Hardcore Revolution (U).zip"
move "Eikou no Saint Andrews (Japan).zip" "_REN\Eikou no Saint Andrews (J).zip"
move "Eltale Monsters (Japan).zip" "_REN\Eltale Monsters (J).zip"
move "Excitebike 64 (Europe).zip" "_REN\Excitebike 64 (E).zip"
move "Excitebike 64 (Japan).zip" "_REN\Excitebike 64 (J).zip"
move "Excitebike 64 (USA) (Demo) (Kiosk).zip" "_REN\Excitebike 64 (U) (Demo) (Kiosk).zip"
move "Excitebike 64 (USA) (Rev 1).zip" "_REN\Excitebike 64 (U) (Rev 1).zip"
move "Excitebike 64 (USA).zip" "_REN\Excitebike 64 (U).zip"
move "Extreme-G (Europe) (En,Fr,De,Es,It).zip" "_REN\Extreme-G (E) (EnFrDeEsIt).zip"
move "Extreme-G (Japan).zip" "_REN\Extreme-G (J).zip"
move "Extreme-G (USA).zip" "_REN\Extreme-G (U).zip"
move "Extreme-G XG2 (Europe) (En,Fr,De,Es,It).zip" "_REN\Extreme-G XG2 (E) (EnFrDeEsIt).zip"
move "Extreme-G XG2 (Japan).zip" "_REN\Extreme-G XG2 (J).zip"
move "Extreme-G XG2 (USA).zip" "_REN\Extreme-G XG2 (U).zip"
move "F-1 World Grand Prix (Europe).zip" "_REN\F-1 World Grand Prix (E).zip"
move "F-1 World Grand Prix (France).zip" "_REN\F-1 World Grand Prix (F).zip"
move "F-1 World Grand Prix (Germany).zip" "_REN\F-1 World Grand Prix (G).zip"
move "F-1 World Grand Prix (Japan).zip" "_REN\F-1 World Grand Prix (J).zip"
move "F-1 World Grand Prix (USA).zip" "_REN\F-1 World Grand Prix (U).zip"
move "F-1 World Grand Prix II (Europe) (En,Fr,De,Es).zip" "_REN\F-1 World Grand Prix II (E) (EnFrDeEs).zip"
move "F-Zero X (Europe).zip" "_REN\F-Zero X (E).zip"
move "F-Zero X (Japan).zip" "_REN\F-Zero X (J).zip"
move "F-Zero X (USA).zip" "_REN\F-Zero X (U).zip"
move "F1 Pole Position 64 (Europe) (En,Fr,De).zip" "_REN\F1 Pole Position 64 (E) (EnFrDe).zip"
move "F1 Pole Position 64 (USA) (En,Fr,De).zip" "_REN\F1 Pole Position 64 (U) (EnFrDe).zip"
move "F1 Racing Championship (Brazil) (En,Fr).zip" "_REN\F1 Racing Championship (B) (EnFr).zip"
move "F1 Racing Championship (Europe) (En,Fr,De,Es,It).zip" "_REN\F1RacingChampionship(E)(EnFrDeEsIt).zip"
move "F1 Racing Championship (USA) (Beta).zip" "_REN\F1 Racing Championship (U) (Beta).zip"
move "Famista 64 (Japan).zip" "_REN\Famista 64 (J).zip"
move "FIFA - Road to World Cup 98 (Europe) (En,Fr,De,Es,It,Nl,Sv).zip" "_REN\FIFARoadtoWorldCup98(E).zip"
move "FIFA - Road to World Cup 98 (USA) (En,Fr,De,Es,It,Nl,Sv).zip" "_REN\FIFARoadtoWorldCup98(U).zip"
move "FIFA - Road to World Cup 98 - World Cup e no Michi (Japan).zip" "_REN\FIFARoadtoWorldCup98WorldCupenoMich(J).zip"
move "FIFA 64 (Europe) (En,Fr,De).zip" "_REN\FIFA 64 (E) (EnFrDe).zip"
move "FIFA 99 (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv).zip" "_REN\FIFA 99 (E) (EnFrDeEsItNlPtSv).zip"
move "FIFA 99 (USA) (En,Fr,De,Es,It,Nl,Pt,Sv).zip" "_REN\FIFA 99 (U) (EnFrDeEsItNlPtSv).zip"
move "Fighter Destiny 2 (USA).zip" "_REN\Fighter Destiny 2 (U).zip"
move "Fighters Destiny (Europe).zip" "_REN\Fighters Destiny (E).zip"
move "Fighters Destiny (France).zip" "_REN\Fighters Destiny (F).zip"
move "Fighters Destiny (Germany).zip" "_REN\Fighters Destiny (G).zip"
move "Fighters Destiny (USA).zip" "_REN\Fighters Destiny (U).zip"
move "Fighting Cup (Japan).zip" "_REN\Fighting Cup (J).zip"
move "Fighting Force 64 (Europe).zip" "_REN\Fighting Force 64 (E).zip"
move "Fighting Force 64 (USA).zip" "_REN\Fighting Force 64 (U).zip"
move "Flying Dragon (Europe).zip" "_REN\Flying Dragon (E).zip"
move "Flying Dragon (USA).zip" "_REN\Flying Dragon (U).zip"
move "Forsaken (Europe) (En,Fr,Es,It).zip" "_REN\Forsaken (E) (EnFrEsIt).zip"
move "Forsaken (Germany).zip" "_REN\Forsaken (G).zip"
move "Forsaken 64 (USA).zip" "_REN\Forsaken 64 (U).zip"
move "Fox Sports College Hoops '99 (USA).zip" "_REN\Fox Sports College Hoops '99 (U).zip"
move "Freak Boy (Unknown) (Proto).zip" "_REN\Freak Boy (Unknown) (Proto).zip"
move "Frogger 2 (USA) (Proto 1).zip" "_REN\Frogger 2 (U) (Proto 1).zip"
move "Frogger 2 (USA) (Proto 2).zip" "_REN\Frogger 2 (U) (Proto 2).zip"
move "Fushigi no Dungeon - Fuurai no Shiren 2 - Oni Shuurai! Shiren Jou! (Japan).zip" "_REN\FushiginoDungeonFuurainoShiren2OniS(J).zip"
move "G.A.S.P!! Fighters' NEXTream (Europe).zip" "_REN\G.A.S.P!! Fighters' NEXTream (E).zip"
move "G.A.S.P!! Fighters' NEXTream (Japan).zip" "_REN\G.A.S.P!! Fighters' NEXTream (J).zip"
move "Ganbare Goemon - Dero Dero Douchuu Obake Tenkomori (Japan).zip" "_REN\GanbareGoemonDeroDeroDouchuuObakeTe(J).zip"
move "Ganbare Goemon - Neo Momoyama Bakufu no Odori (Japan).zip" "_REN\GanbareGoemonNeoMomoyamaBakufunoOdo(J).zip"
move "Ganbare! Nippon! Olympics 2000 (Japan).zip" "_REN\Ganbare! Nippon! Olympics 2000 (J).zip"
move "Gauntlet Legends (Europe).zip" "_REN\Gauntlet Legends (E).zip"
move "Gauntlet Legends (Japan).zip" "_REN\Gauntlet Legends (J).zip"
move "Gauntlet Legends (USA).zip" "_REN\Gauntlet Legends (U).zip"
move "Getter Love!! - Cho Renai Party Game Tanjou (Japan).zip" "_REN\GetterLove!!ChoRenaiPartyGameTanjou(J).zip"
move "Gex 3 - Deep Cover Gecko (Europe) (En,Es,It).zip" "_REN\Gex 3 - Deep Cover Gecko (E) (EnEsIt).zip"
move "Gex 3 - Deep Cover Gecko (Europe) (Fr,De).zip" "_REN\Gex 3 - Deep Cover Gecko (E) (FrDe).zip"
move "Gex 3 - Deep Cover Gecko (USA).zip" "_REN\Gex 3 - Deep Cover Gecko (U).zip"
move "Gex 64 - Enter the Gecko (Europe).zip" "_REN\Gex 64 - Enter the Gecko (E).zip"
move "Gex 64 - Enter the Gecko (USA).zip" "_REN\Gex 64 - Enter the Gecko (U).zip"
move "Glover (Europe) (En,Fr,De).zip" "_REN\Glover (E) (EnFrDe).zip"
move "Glover (USA) (1998-07-16) (Beta) [b].zip" "_REN\Glover (U) (1998-07-16) (Beta) [b].zip"
move "Glover (USA) (1998-09-04) (Beta).zip" "_REN\Glover (U) (1998-09-04) (Beta).zip"
move "Glover (USA).zip" "_REN\Glover (U).zip"
move "Glover 2 (USA) (Proto 1).zip" "_REN\Glover 2 (U) (Proto 1).zip"
move "Glover 2 (USA) (Proto 2).zip" "_REN\Glover 2 (U) (Proto 2).zip"
move "Goemon - Mononoke Sugoroku (Japan).zip" "_REN\Goemon - Mononoke Sugoroku (J).zip"
move "Goemon's Great Adventure (USA).zip" "_REN\Goemon's Great Adventure (U).zip"
move "Golden Nugget 64 (USA).zip" "_REN\Golden Nugget 64 (U).zip"
move "GoldenEye 007 (Europe).zip" "_REN\GoldenEye 007 (E).zip"
move "GoldenEye 007 (Japan).zip" "_REN\GoldenEye 007 (J).zip"
move "GoldenEye 007 (USA).zip" "_REN\GoldenEye 007 (U).zip"
move "GT 64 - Championship Edition (Europe) (En,Fr,De).zip" "_REN\GT64-ChampionshipEdition(E)(EnFrDe).zip"
move "GT 64 - Championship Edition (USA) (1998-05-25) (Beta).zip" "_REN\GT64ChampionshipEdition(U)(Beta).zip"
move "GT 64 - Championship Edition (USA).zip" "_REN\GT 64 - Championship Edition (U).zip"
move "Hamster Monogatari 64 (Japan).zip" "_REN\Hamster Monogatari 64 (J).zip"
move "Harukanaru Augusta - Masters '98 (Japan).zip" "_REN\Harukanaru Augusta - Masters '98 (J).zip"
move "Harvest Moon 64 (USA).zip" "_REN\Harvest Moon 64 (U).zip"
move "Heiwa Pachinko World 64 (Japan).zip" "_REN\Heiwa Pachinko World 64 (J).zip"
move "Hercules - The Legendary Journeys (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN\HerculesTheLegendaryJourneys(E).zip"
move "Hercules - The Legendary Journeys (USA) (Beta 1).zip" "_REN\HerculesTheLegendaryJourneys(U)(Beta1).zip"
move "Hercules - The Legendary Journeys (USA) (Beta 2).zip" "_REN\HerculesTheLegendaryJourneys(U)(Beta2).zip"
move "Hercules - The Legendary Journeys (USA).zip" "_REN\Hercules - The Legendary Journeys (U).zip"
move "Hexen (Europe).zip" "_REN\Hexen (E).zip"
move "Hexen (France).zip" "_REN\Hexen (F).zip"
move "Hexen (Germany).zip" "_REN\Hexen (G).zip"
move "Hexen (Japan).zip" "_REN\Hexen (J).zip"
move "Hexen (USA).zip" "_REN\Hexen (U).zip"
move "Hey You, Pikachu! (USA).zip" "_REN\Hey You Pikachu! (U).zip"
move "Hiryuu no Ken Twin (Japan).zip" "_REN\Hiryuu no Ken Twin (J).zip"
move "Holy Magic Century (Europe).zip" "_REN\Holy Magic Century (E).zip"
move "Holy Magic Century (France).zip" "_REN\Holy Magic Century (F).zip"
move "Holy Magic Century (Germany).zip" "_REN\Holy Magic Century (G).zip"
move "Hoshi no Kirby 64 (Japan) (Rev 1).zip" "_REN\Hoshi no Kirby 64 (J) (Rev 1).zip"
move "Hoshi no Kirby 64 (Japan) (Rev 2).zip" "_REN\Hoshi no Kirby 64 (J) (Rev 2).zip"
move "Hoshi no Kirby 64 (Japan) (Rev 3).zip" "_REN\Hoshi no Kirby 64 (J) (Rev 3).zip"
move "Hoshi no Kirby 64 (Japan).zip" "_REN\Hoshi no Kirby 64 (J).zip"
move "Hot Wheels - Turbo Racing (Europe) (En,Fr,De).zip" "_REN\Hot Wheels - Turbo Racing (E) (EnFrDe).zip"
move "Hot Wheels - Turbo Racing (USA).zip" "_REN\Hot Wheels - Turbo Racing (U).zip"
move "HSV Adventure Racing! (Australia).zip" "_REN\HSV Adventure Racing! (A).zip"
move "Human Grand Prix - The New Generation (Japan).zip" "_REN\HumanGrandPrix-TheNewGeneration(J).zip"
move "Hybrid Heaven (Europe) (En,Fr,De).zip" "_REN\Hybrid Heaven (E) (EnFrDe).zip"
move "Hybrid Heaven (Japan).zip" "_REN\Hybrid Heaven (J).zip"
move "Hybrid Heaven (USA).zip" "_REN\Hybrid Heaven (U).zip"
move "Hydro Thunder (Europe).zip" "_REN\Hydro Thunder (E).zip"
move "Hydro Thunder (France).zip" "_REN\Hydro Thunder (F).zip"
move "Hydro Thunder (USA).zip" "_REN\Hydro Thunder (U).zip"
move "Hyper Olympics in Nagano 64 (Japan).zip" "_REN\Hyper Olympics in Nagano 64 (J).zip"
move "Ide Yosuke no Mahjong Juku (Japan).zip" "_REN\Ide Yosuke no Mahjong Juku (J).zip"
move "Iggy's Reckin' Balls (Europe).zip" "_REN\Iggy's Reckin' Balls (E).zip"
move "Iggy's Reckin' Balls (USA).zip" "_REN\Iggy's Reckin' Balls (U).zip"
move "Iggy-kun no Bura Bura Poyon (Japan).zip" "_REN\Iggy-kun no Bura Bura Poyon (J).zip"
move "In-Fisherman - Bass Hunter 64 (Europe).zip" "_REN\In-Fisherman - Bass Hunter 64 (E).zip"
move "In-Fisherman - Bass Hunter 64 (USA).zip" "_REN\In-Fisherman - Bass Hunter 64 (U).zip"
move "Indiana Jones and the Infernal Machine (Australia) (Proto).zip" "_REN\IndianaJonesandtheInfernalMa(A)(Proto).zip"
move "Indiana Jones and the Infernal Machine (USA).zip" "_REN\IndianaJonesandtheInfernalMachine(U).zip"
move "Indy Racing 2000 (USA).zip" "_REN\Indy Racing 2000 (U).zip"
move "International Superstar Soccer '98 (Europe) (1998-03-02) (Beta).zip" "_REN\InternationalSuperstarSoccer9(E)(Beta).zip"
move "International Superstar Soccer '98 (Europe).zip" "_REN\International Superstar Soccer '98 (E).zip"
move "International Superstar Soccer '98 (USA).zip" "_REN\International Superstar Soccer '98 (U).zip"
move "International Superstar Soccer 2000 (Europe) (En,De).zip" "_REN\InternationalSuperstarSoccer2000(E).zip"
move "International Superstar Soccer 2000 (Europe) (Fr,It).zip" "_REN\InternationalSuperstarSoccer2000(E)_0.zip"
move "International Superstar Soccer 2000 (USA) (En,Es) (Rev 1).zip" "_REN\InternationalSuperstarSoccer2(U)(Rev1).zip"
move "International Superstar Soccer 2000 (USA) (En,Es).zip" "_REN\InternationalSuperstarSoccer2000(U).zip"
move "International Superstar Soccer 64 (Europe).zip" "_REN\International Superstar Soccer 64 (E).zip"
move "International Superstar Soccer 64 (USA).zip" "_REN\International Superstar Soccer 64 (U).zip"
move "International Track & Field - Summer Games (Europe) (En,Fr,De).zip" "_REN\InternationalTrack&FieldSummerGames(E).zip"
move "International Track & Field 2000 (USA).zip" "_REN\International Track & Field 2000 (U).zip"
move "Itoi Shigesato no Bass Tsuri No. 1 Kettei Ban! (Japan).zip" "_REN\ItoiShigesatonoBassTsuriNo1KetteiBa(J).zip"
move "J.League Dynamite Soccer 64 (Japan).zip" "_REN\J.League Dynamite Soccer 64 (J).zip"
move "J.League Eleven Beat 1997 (Japan).zip" "_REN\J.League Eleven Beat 1997 (J).zip"
move "J.League Live 64 (Japan).zip" "_REN\J.League Live 64 (J).zip"
move "J.League Tactics Soccer (Japan) (Rev 1).zip" "_REN\J.League Tactics Soccer (J) (Rev 1).zip"
move "J.League Tactics Soccer (Japan).zip" "_REN\J.League Tactics Soccer (J).zip"
move "Jangou Simulation Mahjong Dou 64 (Japan).zip" "_REN\Jangou Simulation Mahjong Dou 64 (J).zip"
move "Jeopardy! (USA).zip" "_REN\Jeopardy! (U).zip"
move "Jeremy McGrath Supercross 2000 (Europe).zip" "_REN\Jeremy McGrath Supercross 2000 (E).zip"
move "Jeremy McGrath Supercross 2000 (USA) (Beta).zip" "_REN\JeremyMcGrathSupercross2000(U)(Beta).zip"
move "Jeremy McGrath Supercross 2000 (USA).zip" "_REN\Jeremy McGrath Supercross 2000 (U).zip"
move "Jet Force Gemini (Europe) (En,Fr,De,Es).zip" "_REN\Jet Force Gemini (E) (EnFrDeEs).zip"
move "Jet Force Gemini (USA) (Demo) (Kiosk).zip" "_REN\Jet Force Gemini (U) (Demo) (Kiosk).zip"
move "Jet Force Gemini (USA).zip" "_REN\Jet Force Gemini (U).zip"
move "Jikkyou G1 Stable (Japan) (Rev 1).zip" "_REN\Jikkyou G1 Stable (J) (Rev 1).zip"
move "Jikkyou G1 Stable (Japan).zip" "_REN\Jikkyou G1 Stable (J).zip"
move "Jikkyou J.League 1999 - Perfect Striker 2 (Japan) (Rev 1).zip" "_REN\JikkyouJLeague1999PerfectStri(J)(Rev1).zip"
move "Jikkyou J.League 1999 - Perfect Striker 2 (Japan).zip" "_REN\JikkyouJ.League1999-PerfectStriker2(J).zip"
move "Jikkyou J.League Perfect Striker (Japan).zip" "_REN\Jikkyou J.League Perfect Striker (J).zip"
move "Jikkyou Powerful Pro Yakyuu - Basic Ban 2001 (Japan) (Rev 1).zip" "_REN\JikkyouPowerfulProYakyuuBasic(J)(Rev1).zip"
move "Jikkyou Powerful Pro Yakyuu - Basic Ban 2001 (Japan).zip" "_REN\JikkyouPowerfulProYakyuuBasicBan200(J).zip"
move "Jikkyou Powerful Pro Yakyuu 2000 (Japan) (Rev 1).zip" "_REN\JikkyouPowerfulProYakyuu2000(J)(Rev1).zip"
move "Jikkyou Powerful Pro Yakyuu 2000 (Japan).zip" "_REN\Jikkyou Powerful Pro Yakyuu 2000 (J).zip"
move "Jikkyou Powerful Pro Yakyuu 4 (Japan) (1996-11-30) (Beta).zip" "_REN\JikkyouPowerfulProYakyuu4(J)(Beta).zip"
move "Jikkyou Powerful Pro Yakyuu 4 (Japan) (Rev 1).zip" "_REN\JikkyouPowerfulProYakyuu4(J)(Rev1).zip"
move "Jikkyou Powerful Pro Yakyuu 4 (Japan).zip" "_REN\Jikkyou Powerful Pro Yakyuu 4 (J).zip"
move "Jikkyou Powerful Pro Yakyuu 5 (Japan) (Rev 1).zip" "_REN\JikkyouPowerfulProYakyuu5(J)(Rev1).zip"
move "Jikkyou Powerful Pro Yakyuu 5 (Japan) (Rev 2).zip" "_REN\JikkyouPowerfulProYakyuu5(J)(Rev2).zip"
move "Jikkyou Powerful Pro Yakyuu 5 (Japan).zip" "_REN\Jikkyou Powerful Pro Yakyuu 5 (J).zip"
move "Jikkyou Powerful Pro Yakyuu 6 (Japan) (Rev 1).zip" "_REN\JikkyouPowerfulProYakyuu6(J)(Rev1).zip"
move "Jikkyou Powerful Pro Yakyuu 6 (Japan) (Rev 2).zip" "_REN\JikkyouPowerfulProYakyuu6(J)(Rev2).zip"
move "Jikkyou Powerful Pro Yakyuu 6 (Japan).zip" "_REN\Jikkyou Powerful Pro Yakyuu 6 (J).zip"
move "Jikkyou World Soccer - World Cup France '98 (Japan) (Rev 1).zip" "_REN\JikkyouWorldSoccerWorldCupFra(J)(Rev1).zip"
move "Jikkyou World Soccer - World Cup France '98 (Japan) (Rev 2).zip" "_REN\JikkyouWorldSoccerWorldCupFra(J)(Rev2).zip"
move "Jikkyou World Soccer - World Cup France '98 (Japan).zip" "_REN\JikkyouWorldSoccerWorldCupFrance'98(J).zip"
move "Jikkyou World Soccer 3 (Japan).zip" "_REN\Jikkyou World Soccer 3 (J).zip"
move "Jikuu Senshi Turok (Japan).zip" "_REN\Jikuu Senshi Turok (J).zip"
move "Jinsei Game 64 (Japan).zip" "_REN\Jinsei Game 64 (J).zip"
move "John Romero's Daikatana (Europe) (En,Fr,De).zip" "_REN\John Romero's Daikatana (E) (EnFrDe).zip"
move "John Romero's Daikatana (Japan).zip" "_REN\John Romero's Daikatana (J).zip"
move "John Romero's Daikatana (USA).zip" "_REN\John Romero's Daikatana (U).zip"
move "Kakutou Denshou - F-Cup Maniax (Japan).zip" "_REN\Kakutou Denshou - F-Cup Maniax (J).zip"
move "Ken Griffey Jr.'s Slugfest (USA).zip" "_REN\Ken Griffey Jr.'s Slugfest (U).zip"
move "Killer Instinct Gold (Europe).zip" "_REN\Killer Instinct Gold (E).zip"
move "Killer Instinct Gold (USA) (Rev 1).zip" "_REN\Killer Instinct Gold (U) (Rev 1).zip"
move "Killer Instinct Gold (USA) (Rev 2).zip" "_REN\Killer Instinct Gold (U) (Rev 2).zip"
move "Killer Instinct Gold (USA).zip" "_REN\Killer Instinct Gold (U).zip"
move "King Hill 64 - Extreme Snowboarding (Japan).zip" "_REN\KingHill64-ExtremeSnowboarding(J).zip"
move "Kiratto Kaiketsu! 64 Tanteidan (Japan).zip" "_REN\Kiratto Kaiketsu! 64 Tanteidan (J).zip"
move "Kirby 64 - The Crystal Shards (Europe).zip" "_REN\Kirby 64 - The Crystal Shards (E).zip"
move "Kirby 64 - The Crystal Shards (USA).zip" "_REN\Kirby 64 - The Crystal Shards (U).zip"
move "Knife Edge - Nose Gunner (Europe).zip" "_REN\Knife Edge - Nose Gunner (E).zip"
move "Knife Edge - Nose Gunner (Japan).zip" "_REN\Knife Edge - Nose Gunner (J).zip"
move "Knife Edge - Nose Gunner (USA).zip" "_REN\Knife Edge - Nose Gunner (U).zip"
move "Knockout Kings 2000 (Europe).zip" "_REN\Knockout Kings 2000 (E).zip"
move "Knockout Kings 2000 (USA).zip" "_REN\Knockout Kings 2000 (U).zip"
move "Kobe Bryant in NBA Courtside (Europe).zip" "_REN\Kobe Bryant in NBA Courtside (E).zip"
move "Kobe Bryant in NBA Courtside (USA).zip" "_REN\Kobe Bryant in NBA Courtside (U).zip"
move "Last Legion UX (Japan).zip" "_REN\Last Legion UX (J).zip"
move "Legend of Zelda, The - Majora's Mask (Europe) (En,Fr,De,Es) (Rev 1) (Debug).zip" "_REN\LegendofZeldaMajorasMask(E)(Rev1).zip"
move "Legend of Zelda, The - Majora's Mask (Europe) (En,Fr,De,Es) (Rev 1).zip" "_REN\LegendofZeldaMajorasMask(E)(Rev1)_0.zip"
move "Legend of Zelda, The - Majora's Mask (Europe) (En,Fr,De,Es).zip" "_REN\LegendofZeldaMajora'sMask(E)(EnFrDeEs).zip"
move "Legend of Zelda, The - Majora's Mask (Europe) (GameCube).zip" "_REN\LegendofZeldaMajora'sMask(E)(GameCube).zip"
move "Legend of Zelda, The - Majora's Mask (USA) (Demo) (Kiosk).zip" "_REN\LegendofZeldaMajorasMask(U)(Demo).zip"
move "Legend of Zelda, The - Majora's Mask (USA) (GameCube).zip" "_REN\LegendofZeldaMajora'sMask(U)(GameCube).zip"
move "Legend of Zelda, The - Majora's Mask (USA).zip" "_REN\Legend of Zelda - Majora's Mask (U).zip"
move "Legend of Zelda, The - Ocarina of Time (Europe) (Beta) (2003-02-13) (GameCube).zip" "_REN\LegendofZeldaOcarinaofTime(E)(Beta).zip"
move "Legend of Zelda, The - Ocarina of Time (Europe) (Beta) (2003-02-21) (GameCube) (Debug).zip" "_REN\LegendofZeldaOcarinaofTime(E)(Beta)_0.zip"
move "Legend of Zelda, The - Ocarina of Time (Europe) (En,Fr,De) (Rev 1).zip" "_REN\LegendofZeldaOcarinaofTime(E)(Rev1).zip"
move "Legend of Zelda, The - Ocarina of Time (Europe) (En,Fr,De).zip" "_REN\LegendofZelda-OcarinaofTime(E)(EnFrDe).zip"
move "Legend of Zelda, The - Ocarina of Time (Europe) (GameCube).zip" "_REN\LegendofZeldaOcarinaofTime(E)(GC).zip"
move "Legend of Zelda, The - Ocarina of Time (USA) (Beta).zip" "_REN\LegendofZelda-OcarinaofTime(U)(Beta).zip"
move "Legend of Zelda, The - Ocarina of Time (USA) (GameCube).zip" "_REN\LegendofZeldaOcarinaofTime(U)(GC).zip"
move "Legend of Zelda, The - Ocarina of Time (USA) (Rev 1).zip" "_REN\LegendofZelda-OcarinaofTime(U)(Rev1).zip"
move "Legend of Zelda, The - Ocarina of Time (USA) (Rev 2).zip" "_REN\LegendofZelda-OcarinaofTime(U)(Rev2).zip"
move "Legend of Zelda, The - Ocarina of Time (USA).zip" "_REN\Legend of Zelda - Ocarina of Time (U).zip"
move "Legend of Zelda, The - Ocarina of Time - Master Quest (Europe) (GameCube) (Debug).zip" "_REN\LegendofZeldaOcarinaofTimeMaste(E)(GC).zip"
move "Legend of Zelda, The - Ocarina of Time - Master Quest (Europe) (GameCube).zip" "_REN\LegendofZeldaOcarinaofTimeMaste(E)(G_0.zip"
move "Legend of Zelda, The - Ocarina of Time - Master Quest (USA) (GameCube).zip" "_REN\LegendofZeldaOcarinaofTimeMaste(U)(GC).zip"
move "LEGO Racers (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).zip" "_REN\LEGO Racers (E) (EnFrDeEsItNlSvNoDaFi).zip"
move "LEGO Racers (USA) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).zip" "_REN\LEGO Racers (U) (EnFrDeEsItNlSvNoDaFi).zip"
move "Let's Smash (Japan).zip" "_REN\Let's Smash (J).zip"
move "Lode Runner 3-D (Europe) (En,Fr,De,Es,It).zip" "_REN\Lode Runner 3-D (E) (EnFrDeEsIt).zip"
move "Lode Runner 3-D (Japan).zip" "_REN\Lode Runner 3-D (J).zip"
move "Lode Runner 3-D (USA).zip" "_REN\Lode Runner 3-D (U).zip"
move "Lylat Wars (Australia) (En,Fr,De).zip" "_REN\Lylat Wars (A) (EnFrDe).zip"
move "Lylatwars (Europe) (En,Fr,De).zip" "_REN\Lylatwars (E) (EnFrDe).zip"
move "Mace - The Dark Age (Europe).zip" "_REN\Mace - The Dark Age (E).zip"
move "Mace - The Dark Age (USA) (Beta).zip" "_REN\Mace - The Dark Age (U) (Beta).zip"
move "Mace - The Dark Age (USA).zip" "_REN\Mace - The Dark Age (U).zip"
move "Madden Football 64 (Europe).zip" "_REN\Madden Football 64 (E).zip"
move "Madden Football 64 (USA).zip" "_REN\Madden Football 64 (U).zip"
move "Madden NFL 2000 (USA).zip" "_REN\Madden NFL 2000 (U).zip"
move "Madden NFL 2001 (USA).zip" "_REN\Madden NFL 2001 (U).zip"
move "Madden NFL 2002 (USA).zip" "_REN\Madden NFL 2002 (U).zip"
move "Madden NFL 99 (Europe).zip" "_REN\Madden NFL 99 (E).zip"
move "Madden NFL 99 (USA) (1998-08-05) (Beta).zip" "_REN\Madden NFL 99 (U) (1998-08-05) (Beta).zip"
move "Madden NFL 99 (USA) (Rev 1).zip" "_REN\Madden NFL 99 (U) (Rev 1).zip"
move "Madden NFL 99 (USA).zip" "_REN\Madden NFL 99 (U).zip"
move "Magical Tetris Challenge (Europe).zip" "_REN\Magical Tetris Challenge (E).zip"
move "Magical Tetris Challenge (Germany).zip" "_REN\Magical Tetris Challenge (G).zip"
move "Magical Tetris Challenge (USA).zip" "_REN\Magical Tetris Challenge (U).zip"
move "Magical Tetris Challenge featuring Mickey (Japan).zip" "_REN\MagicalTetrisChallengefeaturingMick(J).zip"
move "Mahjong 64 (Japan).zip" "_REN\Mahjong 64 (J).zip"
move "Mahjong Hourouki Classic (Japan).zip" "_REN\Mahjong Hourouki Classic (J).zip"
move "Mahjong Master (Japan).zip" "_REN\Mahjong Master (J).zip"
move "Major League Baseball Featuring Ken Griffey Jr. (Australia).zip" "_REN\MajorLeagueBaseballFeaturingKenGrif(A).zip"
move "Major League Baseball Featuring Ken Griffey Jr. (USA).zip" "_REN\MajorLeagueBaseballFeaturingKenGrif(U).zip"
move "Mario Golf (Europe).zip" "_REN\Mario Golf (E).zip"
move "Mario Golf (USA).zip" "_REN\Mario Golf (U).zip"
move "Mario Golf 64 (Japan) (Rev 1).zip" "_REN\Mario Golf 64 (J) (Rev 1).zip"
move "Mario Golf 64 (Japan).zip" "_REN\Mario Golf 64 (J).zip"
move "Mario Kart 64 (Europe) (Rev 1).zip" "_REN\Mario Kart 64 (E) (Rev 1).zip"
move "Mario Kart 64 (Europe).zip" "_REN\Mario Kart 64 (E).zip"
move "Mario Kart 64 (Japan) (Rev 1).zip" "_REN\Mario Kart 64 (J) (Rev 1).zip"
move "Mario Kart 64 (Japan).zip" "_REN\Mario Kart 64 (J).zip"
move "Mario Kart 64 (USA).zip" "_REN\Mario Kart 64 (U).zip"
move "Mario no Photopie (Japan).zip" "_REN\Mario no Photopie (J).zip"
move "Mario Party (Europe) (En,Fr,De).zip" "_REN\Mario Party (E) (EnFrDe).zip"
move "Mario Party (Japan).zip" "_REN\Mario Party (J).zip"
move "Mario Party (USA).zip" "_REN\Mario Party (U).zip"
move "Mario Party 2 (Europe) (En,Fr,De,Es,It).zip" "_REN\Mario Party 2 (E) (EnFrDeEsIt).zip"
move "Mario Party 2 (Japan).zip" "_REN\Mario Party 2 (J).zip"
move "Mario Party 2 (USA).zip" "_REN\Mario Party 2 (U).zip"
move "Mario Party 3 (Europe) (En,Fr,De,Es).zip" "_REN\Mario Party 3 (E) (EnFrDeEs).zip"
move "Mario Party 3 (Japan).zip" "_REN\Mario Party 3 (J).zip"
move "Mario Party 3 (USA) (Beta).zip" "_REN\Mario Party 3 (U) (Beta).zip"
move "Mario Party 3 (USA).zip" "_REN\Mario Party 3 (U).zip"
move "Mario Story (Japan).zip" "_REN\Mario Story (J).zip"
move "Mario Tennis (Europe).zip" "_REN\Mario Tennis (E).zip"
move "Mario Tennis (USA).zip" "_REN\Mario Tennis (U).zip"
move "Mario Tennis 64 (Japan).zip" "_REN\Mario Tennis 64 (J).zip"
move "Mega Man 64 (USA) (Beta).zip" "_REN\Mega Man 64 (U) (Beta).zip"
move "Mega Man 64 (USA).zip" "_REN\Mega Man 64 (U).zip"
move "Mia Hamm Soccer 64 (USA) (En,Es).zip" "_REN\Mia Hamm Soccer 64 (U) (EnEs).zip"
move "Michael Owen's WLS 2000 (Europe) (En,Fr,De,Es,It) (Beta).zip" "_REN\MichaelOwensWLS2000(E)(Beta).zip"
move "Michael Owen's WLS 2000 (Europe).zip" "_REN\Michael Owen's WLS 2000 (E).zip"
move "Mickey no Racing Challenge USA (Japan).zip" "_REN\Mickey no Racing Challenge USA (J).zip"
move "Mickey's Speedway USA (Europe) (En,Fr,De,Es,It).zip" "_REN\Mickey's Speedway USA (E) (EnFrDeEsIt).zip"
move "Mickey's Speedway USA (USA).zip" "_REN\Mickey's Speedway USA (U).zip"
move "Micro Machines 64 Turbo (Europe) (En,Fr,De,Es,It).zip" "_REN\MicroMachines64Turbo(E)(EnFrDeEsIt).zip"
move "Micro Machines 64 Turbo (USA).zip" "_REN\Micro Machines 64 Turbo (U).zip"
move "Midway's Greatest Arcade Hits - Volume 1 (USA).zip" "_REN\Midway'sGreatestArcadeHits-Volume1(U).zip"
move "Mike Piazza's Strike Zone (USA).zip" "_REN\Mike Piazza's Strike Zone (U).zip"
move "Milo's Astro Lanes (Europe).zip" "_REN\Milo's Astro Lanes (E).zip"
move "Milo's Astro Lanes (USA).zip" "_REN\Milo's Astro Lanes (U).zip"
move "Mini Racers (USA) (Ja) (Proto).zip" "_REN\Mini Racers (U) (Ja) (Proto).zip"
move "Mischief Makers (Europe).zip" "_REN\Mischief Makers (E).zip"
move "Mischief Makers (USA) (Rev 1).zip" "_REN\Mischief Makers (U) (Rev 1).zip"
move "Mischief Makers (USA).zip" "_REN\Mischief Makers (U).zip"
move "Mission - Impossible (Europe) (Beta).zip" "_REN\Mission - Impossible (E) (Beta).zip"
move "Mission - Impossible (Europe).zip" "_REN\Mission - Impossible (E).zip"
move "Mission - Impossible (France).zip" "_REN\Mission - Impossible (F).zip"
move "Mission - Impossible (Germany).zip" "_REN\Mission - Impossible (G).zip"
move "Mission - Impossible (Italy).zip" "_REN\Mission - Impossible (I).zip"
move "Mission - Impossible (Spain) (Rev 1).zip" "_REN\Mission - Impossible (S) (Rev 1).zip"
move "Mission - Impossible (Spain).zip" "_REN\Mission - Impossible (S).zip"
move "Mission - Impossible (USA).zip" "_REN\Mission - Impossible (U).zip"
move "Monaco Grand Prix (USA).zip" "_REN\Monaco Grand Prix (U).zip"
move "Monaco Grand Prix - Racing Simulation 2 (Europe) (En,Fr,Es,It).zip" "_REN\MonacoGrandPrixRacingSimulation2(E).zip"
move "Monopoly (USA).zip" "_REN\Monopoly (U).zip"
move "Monster Truck Madness 64 (Europe) (En,Fr,De,Es,It).zip" "_REN\MonsterTruckMadness64(E)(EnFrDeEsIt).zip"
move "Monster Truck Madness 64 (USA).zip" "_REN\Monster Truck Madness 64 (U).zip"
move "Morita Shougi 64 (Japan).zip" "_REN\Morita Shougi 64 (J).zip"
move "Mortal Kombat 4 (Europe).zip" "_REN\Mortal Kombat 4 (E).zip"
move "Mortal Kombat 4 (USA).zip" "_REN\Mortal Kombat 4 (U).zip"
move "Mortal Kombat Mythologies - Sub-Zero (Europe).zip" "_REN\MortalKombatMythologies-Sub-Zero(E).zip"
move "Mortal Kombat Mythologies - Sub-Zero (USA).zip" "_REN\MortalKombatMythologies-Sub-Zero(U).zip"
move "Mortal Kombat Trilogy (Europe).zip" "_REN\Mortal Kombat Trilogy (E).zip"
move "Mortal Kombat Trilogy (USA) (1996-05-13) (Beta).zip" "_REN\MortalKombatTrilogy(U)(19960513)(Beta).zip"
move "Mortal Kombat Trilogy (USA) (Rev 1).zip" "_REN\Mortal Kombat Trilogy (U) (Rev 1).zip"
move "Mortal Kombat Trilogy (USA) (Rev 2).zip" "_REN\Mortal Kombat Trilogy (U) (Rev 2).zip"
move "Mortal Kombat Trilogy (USA).zip" "_REN\Mortal Kombat Trilogy (U).zip"
move "MRC - Multi-Racing Championship (Europe) (En,Fr,De).zip" "_REN\MRCMultiRacingChampionship(E)(EnFrDe).zip"
move "MRC - Multi-Racing Championship (Japan).zip" "_REN\MRC - Multi-Racing Championship (J).zip"
move "MRC - Multi-Racing Championship (USA).zip" "_REN\MRC - Multi-Racing Championship (U).zip"
move "Ms. Pac-Man - Maze Madness (USA).zip" "_REN\Ms. Pac-Man - Maze Madness (U).zip"
move "Mystical Ninja 2 Starring Goemon (Europe) (En,Fr,De).zip" "_REN\MysticalNinja2StarringGoemon(E).zip"
move "Mystical Ninja Starring Goemon (Europe).zip" "_REN\Mystical Ninja Starring Goemon (E).zip"
move "Mystical Ninja Starring Goemon (USA).zip" "_REN\Mystical Ninja Starring Goemon (U).zip"
move "Nagano Winter Olympics '98 (Europe).zip" "_REN\Nagano Winter Olympics '98 (E).zip"
move "Nagano Winter Olympics '98 (USA).zip" "_REN\Nagano Winter Olympics '98 (U).zip"
move "Namco Museum 64 (USA).zip" "_REN\Namco Museum 64 (U).zip"
move "NASCAR 2000 (USA).zip" "_REN\NASCAR 2000 (U).zip"
move "NASCAR 99 (Europe) (En,Fr,De).zip" "_REN\NASCAR 99 (E) (EnFrDe).zip"
move "NASCAR 99 (USA).zip" "_REN\NASCAR 99 (U).zip"
move "NBA Courtside 2 featuring Kobe Bryant (USA).zip" "_REN\NBACourtside2featuringKobeBryant(U).zip"
move "NBA Hangtime (Europe).zip" "_REN\NBA Hangtime (E).zip"
move "NBA Hangtime (USA).zip" "_REN\NBA Hangtime (U).zip"
move "NBA in the Zone '98 (Japan).zip" "_REN\NBA in the Zone '98 (J).zip"
move "NBA in the Zone '98 (USA).zip" "_REN\NBA in the Zone '98 (U).zip"
move "NBA in the Zone '99 (USA).zip" "_REN\NBA in the Zone '99 (U).zip"
move "NBA in the Zone 2 (Japan).zip" "_REN\NBA in the Zone 2 (J).zip"
move "NBA in the Zone 2000 (Europe).zip" "_REN\NBA in the Zone 2000 (E).zip"
move "NBA in the Zone 2000 (USA).zip" "_REN\NBA in the Zone 2000 (U).zip"
move "NBA Jam 2000 (Europe).zip" "_REN\NBA Jam 2000 (E).zip"
move "NBA Jam 2000 (USA).zip" "_REN\NBA Jam 2000 (U).zip"
move "NBA Jam 99 (Europe).zip" "_REN\NBA Jam 99 (E).zip"
move "NBA Jam 99 (USA).zip" "_REN\NBA Jam 99 (U).zip"
move "NBA Live 2000 (Europe) (En,Fr,De,Es).zip" "_REN\NBA Live 2000 (E) (EnFrDeEs).zip"
move "NBA Live 2000 (USA) (En,Fr,De,Es).zip" "_REN\NBA Live 2000 (U) (EnFrDeEs).zip"
move "NBA Live 99 (Europe) (En,Fr,De,Es,It).zip" "_REN\NBA Live 99 (E) (EnFrDeEsIt).zip"
move "NBA Live 99 (USA) (En,Fr,De,Es,It).zip" "_REN\NBA Live 99 (U) (EnFrDeEsIt).zip"
move "NBA Pro 98 (Europe).zip" "_REN\NBA Pro 98 (E).zip"
move "NBA Pro 99 (Europe).zip" "_REN\NBA Pro 99 (E).zip"
move "NBA Showtime - NBA on NBC (USA).zip" "_REN\NBA Showtime - NBA on NBC (U).zip"
move "Neon Genesis Evangelion (Japan).zip" "_REN\Neon Genesis Evangelion (J).zip"
move "New Tetris, The (Europe).zip" "_REN\New Tetris (E).zip"
move "New Tetris, The (USA).zip" "_REN\New Tetris (U).zip"
move "NFL Blitz (USA).zip" "_REN\NFL Blitz (U).zip"
move "NFL Blitz - Special Edition (USA).zip" "_REN\NFL Blitz - Special Edition (U).zip"
move "NFL Blitz 2000 (USA) (Rev 1).zip" "_REN\NFL Blitz 2000 (U) (Rev 1).zip"
move "NFL Blitz 2000 (USA).zip" "_REN\NFL Blitz 2000 (U).zip"
move "NFL Blitz 2001 (USA).zip" "_REN\NFL Blitz 2001 (U).zip"
move "NFL QB Club 2001 (USA).zip" "_REN\NFL QB Club 2001 (U).zip"
move "NFL Quarterback Club 2000 (Europe).zip" "_REN\NFL Quarterback Club 2000 (E).zip"
move "NFL Quarterback Club 2000 (USA).zip" "_REN\NFL Quarterback Club 2000 (U).zip"
move "NFL Quarterback Club 98 (Europe).zip" "_REN\NFL Quarterback Club 98 (E).zip"
move "NFL Quarterback Club 98 (USA).zip" "_REN\NFL Quarterback Club 98 (U).zip"
move "NFL Quarterback Club 99 (Europe).zip" "_REN\NFL Quarterback Club 99 (E).zip"
move "NFL Quarterback Club 99 (USA).zip" "_REN\NFL Quarterback Club 99 (U).zip"
move "NHL 99 (Europe) (En,De,Sv,Fi).zip" "_REN\NHL 99 (E) (EnDeSvFi).zip"
move "NHL 99 (USA).zip" "_REN\NHL 99 (U).zip"
move "NHL Blades of Steel '99 (USA).zip" "_REN\NHL Blades of Steel '99 (U).zip"
move "NHL Breakaway 98 (Europe).zip" "_REN\NHL Breakaway 98 (E).zip"
move "NHL Breakaway 98 (USA).zip" "_REN\NHL Breakaway 98 (U).zip"
move "NHL Breakaway 99 (Europe).zip" "_REN\NHL Breakaway 99 (E).zip"
move "NHL Breakaway 99 (USA).zip" "_REN\NHL Breakaway 99 (U).zip"
move "NHL Pro 99 (Europe).zip" "_REN\NHL Pro 99 (E).zip"
move "Nightmare Creatures (USA).zip" "_REN\Nightmare Creatures (U).zip"
move "Nintama Rantarou 64 Game Gallery (Japan).zip" "_REN\Nintama Rantarou 64 Game Gallery (J).zip"
move "Nintendo All-Star! Dairantou Smash Brothers (Japan).zip" "_REN\NintendoAllStarDairantouSmashBrothe(J).zip"
move "Nuclear Strike 64 (Europe) (En,Fr).zip" "_REN\Nuclear Strike 64 (E) (EnFr).zip"
move "Nuclear Strike 64 (Germany) (1999-11-17) (Beta).zip" "_REN\NuclearStrike64(G)(1999-11-17)(Beta).zip"
move "Nuclear Strike 64 (Germany).zip" "_REN\Nuclear Strike 64 (G).zip"
move "Nuclear Strike 64 (USA) (1999-09-21) (Beta).zip" "_REN\NuclearStrike64(U)(1999-09-21)(Beta).zip"
move "Nuclear Strike 64 (USA) (Beta) (Earlier).zip" "_REN\Nuclear Strike 64 (U) (Beta) (Earlier).zip"
move "Nuclear Strike 64 (USA).zip" "_REN\Nuclear Strike 64 (U).zip"
move "Nushi Zuri 64 (Japan) (Rev 1).zip" "_REN\Nushi Zuri 64 (J) (Rev 1).zip"
move "Nushi Zuri 64 (Japan).zip" "_REN\Nushi Zuri 64 (J).zip"
move "Nushi Zuri 64 - Shiokaze ni Notte (Japan).zip" "_REN\Nushi Zuri 64 - Shiokaze ni Notte (J).zip"
move "O.D.T. (Europe) (En,Fr,De,Es,It) (Proto).zip" "_REN\O.D.T. (E) (EnFrDeEsIt) (Proto).zip"
move "O.D.T. (USA) (En,Fr,Es) (Proto).zip" "_REN\O.D.T. (U) (EnFrEs) (Proto).zip"
move "Off Road Challenge (Europe).zip" "_REN\Off Road Challenge (E).zip"
move "Off Road Challenge (USA).zip" "_REN\Off Road Challenge (U).zip"
move "Ogre Battle 64 - Person of Lordly Caliber (Japan) (Rev 1).zip" "_REN\OgreBattle64PersonofLordlyCal(J)(Rev1).zip"
move "Ogre Battle 64 - Person of Lordly Caliber (USA) (Rev 1).zip" "_REN\OgreBattle64PersonofLordlyCal(U)(Rev1).zip"
move "Ogre Battle 64 - Person of Lordly Caliber (USA).zip" "_REN\OgreBattle64-PersonofLordlyCaliber(U).zip"
move "Olympic Hockey 98 (Europe) (En,Fr,De,Es).zip" "_REN\Olympic Hockey 98 (E) (EnFrDeEs).zip"
move "Olympic Hockey 98 (Japan).zip" "_REN\Olympic Hockey 98 (J).zip"
move "Olympic Hockey 98 (USA).zip" "_REN\Olympic Hockey 98 (U).zip"
move "Onegai Monsters (Japan).zip" "_REN\Onegai Monsters (J).zip"
move "Operation WinBack (Europe) (En,Fr,De,Es,It).zip" "_REN\Operation WinBack (E) (EnFrDeEsIt).zip"
move "Pachinko 365 Nichi (Japan).zip" "_REN\Pachinko 365 Nichi (J).zip"
move "Paper Mario (Europe) (En,Fr,De,Es).zip" "_REN\Paper Mario (E) (EnFrDeEs).zip"
move "Paper Mario (USA).zip" "_REN\Paper Mario (U).zip"
move "Paperboy (Europe).zip" "_REN\Paperboy (E).zip"
move "Paperboy (USA).zip" "_REN\Paperboy (U).zip"
move "Parlor! Pro 64 - Pachinko Jikki Simulation Game (Japan).zip" "_REN\ParlorPro64PachinkoJikkiSimulationG(J).zip"
move "PD Ultraman Battle Collection 64 (Japan).zip" "_REN\PD Ultraman Battle Collection 64 (J).zip"
move "Penny Racers (Europe).zip" "_REN\Penny Racers (E).zip"
move "Penny Racers (USA).zip" "_REN\Penny Racers (U).zip"
move "Perfect Dark (Europe) (2000-04-26) (Debug).zip" "_REN\Perfect Dark (E) (2000-04-26) (Debug).zip"
move "Perfect Dark (Europe) (En,Fr,De,Es,It).zip" "_REN\Perfect Dark (E) (EnFrDeEsIt).zip"
move "Perfect Dark (Japan).zip" "_REN\Perfect Dark (J).zip"
move "Perfect Dark (USA) (2000-03-22) (Debug).zip" "_REN\Perfect Dark (U) (2000-03-22) (Debug).zip"
move "Perfect Dark (USA) (Rev 1).zip" "_REN\Perfect Dark (U) (Rev 1).zip"
move "Perfect Dark (USA).zip" "_REN\Perfect Dark (U).zip"
move "PGA European Tour (USA).zip" "_REN\PGA European Tour (U).zip"
move "PGA European Tour Golf (Europe) (En,Fr,De,Es,It).zip" "_REN\PGAEuropeanTourGolf(E)(EnFrDeEsIt).zip"
move "Pikachuu Genki de Chuu (Japan).zip" "_REN\Pikachuu Genki de Chuu (J).zip"
move "Pilotwings 64 (Europe) (En,Fr,De).zip" "_REN\Pilotwings 64 (E) (EnFrDe).zip"
move "Pilotwings 64 (Japan).zip" "_REN\Pilotwings 64 (J).zip"
move "Pilotwings 64 (USA).zip" "_REN\Pilotwings 64 (U).zip"
move "Pokemon Puzzle League (Europe).zip" "_REN\Pokemon Puzzle League (E).zip"
move "Pokemon Puzzle League (France).zip" "_REN\Pokemon Puzzle League (F).zip"
move "Pokemon Puzzle League (Germany).zip" "_REN\Pokemon Puzzle League (G).zip"
move "Pokemon Puzzle League (USA).zip" "_REN\Pokemon Puzzle League (U).zip"
move "Pokemon Snap (Australia).zip" "_REN\Pokemon Snap (A).zip"
move "Pokemon Snap (Europe).zip" "_REN\Pokemon Snap (E).zip"
move "Pokemon Snap (France).zip" "_REN\Pokemon Snap (F).zip"
move "Pokemon Snap (Germany).zip" "_REN\Pokemon Snap (G).zip"
move "Pokemon Snap (Italy).zip" "_REN\Pokemon Snap (I).zip"
move "Pokemon Snap (Japan).zip" "_REN\Pokemon Snap (J).zip"
move "Pokemon Snap (Spain).zip" "_REN\Pokemon Snap (S).zip"
move "Pokemon Snap (USA).zip" "_REN\Pokemon Snap (U).zip"
move "Pokemon Snap Station (USA) (Demo) (Kiosk).zip" "_REN\PokemonSnapStation(U)(Demo)(Kiosk).zip"
move "Pokemon Stadium (Europe) (Rev 1).zip" "_REN\Pokemon Stadium (E) (Rev 1).zip"
move "Pokemon Stadium (Europe).zip" "_REN\Pokemon Stadium (E).zip"
move "Pokemon Stadium (France).zip" "_REN\Pokemon Stadium (F).zip"
move "Pokemon Stadium (Germany).zip" "_REN\Pokemon Stadium (G).zip"
move "Pokemon Stadium (Italy).zip" "_REN\Pokemon Stadium (I).zip"
move "Pokemon Stadium (Japan).zip" "_REN\Pokemon Stadium (J).zip"
move "Pokemon Stadium (Spain).zip" "_REN\Pokemon Stadium (S).zip"
move "Pokemon Stadium (USA) (Rev 1).zip" "_REN\Pokemon Stadium (U) (Rev 1).zip"
move "Pokemon Stadium (USA) (Rev 2).zip" "_REN\Pokemon Stadium (U) (Rev 2).zip"
move "Pokemon Stadium (USA).zip" "_REN\Pokemon Stadium (U).zip"
move "Pokemon Stadium 2 (Europe).zip" "_REN\Pokemon Stadium 2 (E).zip"
move "Pokemon Stadium 2 (France).zip" "_REN\Pokemon Stadium 2 (F).zip"
move "Pokemon Stadium 2 (Germany).zip" "_REN\Pokemon Stadium 2 (G).zip"
move "Pokemon Stadium 2 (Italy).zip" "_REN\Pokemon Stadium 2 (I).zip"
move "Pokemon Stadium 2 (Japan).zip" "_REN\Pokemon Stadium 2 (J).zip"
move "Pokemon Stadium 2 (Spain).zip" "_REN\Pokemon Stadium 2 (S).zip"
move "Pokemon Stadium 2 (USA).zip" "_REN\Pokemon Stadium 2 (U).zip"
move "Pokemon Stadium Kin Gin (Japan).zip" "_REN\Pokemon Stadium Kin Gin (J).zip"
move "Polaris SnoCross (USA).zip" "_REN\Polaris SnoCross (U).zip"
move "Power League 64 (Japan).zip" "_REN\Power League 64 (J).zip"
move "Power Rangers - Lightspeed Rescue (Europe).zip" "_REN\Power Rangers - Lightspeed Rescue (E).zip"
move "Power Rangers - Lightspeed Rescue (USA).zip" "_REN\Power Rangers - Lightspeed Rescue (U).zip"
move "Powerpuff Girls, The - Chemical X-Traction (USA).zip" "_REN\PowerpuffGirls-ChemicalX-Traction(U).zip"
move "Premier Manager 64 (Europe).zip" "_REN\Premier Manager 64 (E).zip"
move "Pro Mahjong Kiwame 64 (Japan) (Rev 1).zip" "_REN\Pro Mahjong Kiwame 64 (J) (Rev 1).zip"
move "Pro Mahjong Kiwame 64 (Japan).zip" "_REN\Pro Mahjong Kiwame 64 (J).zip"
move "Pro Mahjong Tsuwamono 64 - Jansou Battle ni Chousen (Japan).zip" "_REN\ProMahjongTsuwamono64JansouBattleni(J).zip"
move "Puyo Puyo Sun 64 (Japan).zip" "_REN\Puyo Puyo Sun 64 (J).zip"
move "Puyo Puyoon Party (Japan).zip" "_REN\Puyo Puyoon Party (J).zip"
move "Puzzle Bobble 64 (Japan).zip" "_REN\Puzzle Bobble 64 (J).zip"
move "Quake (Europe).zip" "_REN\Quake (E).zip"
move "Quake (USA).zip" "_REN\Quake (U).zip"
move "Quake II (Europe).zip" "_REN\Quake II (E).zip"
move "Quake II (USA).zip" "_REN\Quake II (U).zip"
move "Quest 64 (USA).zip" "_REN\Quest 64 (U).zip"
move "Racing Simulation 2 (Germany).zip" "_REN\Racing Simulation 2 (G).zip"
move "Rakugakids (Europe).zip" "_REN\Rakugakids (E).zip"
move "Rakugakids (Japan).zip" "_REN\Rakugakids (J).zip"
move "Rally '99 (Japan).zip" "_REN\Rally '99 (J).zip"
move "Rally Challenge 2000 (USA).zip" "_REN\Rally Challenge 2000 (U).zip"
move "Rampage - World Tour (Europe).zip" "_REN\Rampage - World Tour (E).zip"
move "Rampage - World Tour (USA).zip" "_REN\Rampage - World Tour (U).zip"
move "Rampage 2 - Universal Tour (Europe).zip" "_REN\Rampage 2 - Universal Tour (E).zip"
move "Rampage 2 - Universal Tour (USA).zip" "_REN\Rampage 2 - Universal Tour (U).zip"
move "Rat Attack (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN\Rat Attack (E) (EnFrDeEsItNl).zip"
move "Rat Attack! (USA).zip" "_REN\Rat Attack! (U).zip"
move "Rayman 2 - The Great Escape (Europe) (En,Fr,De,Es,It).zip" "_REN\Rayman2-TheGreatEscape(E)(EnFrDeEsIt).zip"
move "Rayman 2 - The Great Escape (USA) (En,Fr,De,Es,It).zip" "_REN\Rayman2-TheGreatEscape(U)(EnFrDeEsIt).zip"
move "Razmoket, Les - La Chasse aux Tresors (France).zip" "_REN\RazmoketLes-LaChasseauxTresors(F).zip"
move "Razor Freestyle Scooter (USA).zip" "_REN\Razor Freestyle Scooter (U).zip"
move "Re-Volt (Europe) (En,Fr,De,Es).zip" "_REN\Re-Volt (E) (EnFrDeEs).zip"
move "Re-Volt (USA).zip" "_REN\Re-Volt (U).zip"
move "Ready 2 Rumble Boxing (Europe) (En,Fr,De).zip" "_REN\Ready 2 Rumble Boxing (E) (EnFrDe).zip"
move "Ready 2 Rumble Boxing (USA).zip" "_REN\Ready 2 Rumble Boxing (U).zip"
move "Ready 2 Rumble Boxing - Round 2 (USA).zip" "_REN\Ready 2 Rumble Boxing - Round 2 (U).zip"
move "Resident Evil 2 (Europe) (En,Fr).zip" "_REN\Resident Evil 2 (E) (EnFr).zip"
move "Resident Evil 2 (USA) (Rev 1).zip" "_REN\Resident Evil 2 (U) (Rev 1).zip"
move "Resident Evil 2 (USA).zip" "_REN\Resident Evil 2 (U).zip"
move "Road Rash 64 (Europe) (Beta) (1999-10-12).zip" "_REN\Road Rash 64 (E) (Beta) (1999-10-12).zip"
move "Road Rash 64 (Europe).zip" "_REN\Road Rash 64 (E).zip"
move "Road Rash 64 (USA) (Beta 1).zip" "_REN\Road Rash 64 (U) (Beta 1).zip"
move "Road Rash 64 (USA) (Beta 2).zip" "_REN\Road Rash 64 (U) (Beta 2).zip"
move "Road Rash 64 (USA).zip" "_REN\Road Rash 64 (U).zip"
move "Roadsters (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN\Roadsters (E) (EnFrDeEsItNl).zip"
move "Roadsters (USA) (En,Fr,Es).zip" "_REN\Roadsters (U) (EnFrEs).zip"
move "Robot Poncots 64 - 7tsu no Umi no Caramel (Japan).zip" "_REN\RobotPoncots64-7tsunoUminoCaramel(J).zip"
move "Robotech - Crystal Dreams (USA) (Proto 1).zip" "_REN\Robotech-CrystalDreams(U)(Proto1).zip"
move "Robotech - Crystal Dreams (USA) (Proto 2).zip" "_REN\Robotech-CrystalDreams(U)(Proto2).zip"
move "Robotron 64 (Europe).zip" "_REN\Robotron 64 (E).zip"
move "Robotron 64 (USA).zip" "_REN\Robotron 64 (U).zip"
move "Rocket - Robot on Wheels (Europe) (Beta) (1999-09-29).zip" "_REN\RocketRobotonWheels(E)(Beta)(19990929).zip"
move "Rocket - Robot on Wheels (Europe) (En,Fr,De).zip" "_REN\Rocket - Robot on Wheels (E) (EnFrDe).zip"
move "Rocket - Robot on Wheels (USA).zip" "_REN\Rocket - Robot on Wheels (U).zip"
move "Rockman Dash - Hagane no Boukenshin (Japan).zip" "_REN\RockmanDash-HaganenoBoukenshin(J).zip"
move "RR64 - Ridge Racer 64 (Europe).zip" "_REN\RR64 - Ridge Racer 64 (E).zip"
move "RR64 - Ridge Racer 64 (USA).zip" "_REN\RR64 - Ridge Racer 64 (U).zip"
move "RTL World League Soccer 2000 (Germany).zip" "_REN\RTL World League Soccer 2000 (G).zip"
move "Rugrats - Die grosse Schatzsuche (Germany).zip" "_REN\Rugrats - Die grosse Schatzsuche (G).zip"
move "Rugrats - Scavenger Hunt (USA) (Beta) (1999-04-02).zip" "_REN\RugratsScavengerHunt(U)(Beta).zip"
move "Rugrats - Scavenger Hunt (USA).zip" "_REN\Rugrats - Scavenger Hunt (U).zip"
move "Rugrats - Treasure Hunt (Europe).zip" "_REN\Rugrats - Treasure Hunt (E).zip"
move "Rugrats in Paris - The Movie (Europe).zip" "_REN\Rugrats in Paris - The Movie (E).zip"
move "Rugrats in Paris - The Movie (USA).zip" "_REN\Rugrats in Paris - The Movie (U).zip"
move "Rush 2 - Extreme Racing USA (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN\Rush2ExtremeRacingUSA(E)(EnFrDeEsItNl).zip"
move "Rush 2 - Extreme Racing USA (USA).zip" "_REN\Rush 2 - Extreme Racing USA (U).zip"
move "S.C.A.R.S. (Europe) (En,Fr,De).zip" "_REN\S.C.A.R.S. (E) (EnFrDe).zip"
move "S.C.A.R.S. (USA).zip" "_REN\S.C.A.R.S. (U).zip"
move "Saikyou Habu Shougi (Japan).zip" "_REN\Saikyou Habu Shougi (J).zip"
move "San Francisco Rush - Extreme Racing (Europe) (En,Fr,De).zip" "_REN\SanFranciscoRushExtremeRacing(E).zip"
move "San Francisco Rush - Extreme Racing (USA) (En,Fr,De) (Rev 1).zip" "_REN\SanFranciscoRushExtremeRacing(U)(Rev1).zip"
move "San Francisco Rush - Extreme Racing (USA) (En,Fr,De).zip" "_REN\SanFranciscoRushExtremeRacing(U).zip"
move "San Francisco Rush 2049 (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN\SanFranciscoRush2049(E)(EnFrDeEsItNl).zip"
move "San Francisco Rush 2049 (USA).zip" "_REN\San Francisco Rush 2049 (U).zip"
move "Scooby-Doo! - Classic Creep Capers (Europe).zip" "_REN\Scooby-Doo! - Classic Creep Capers (E).zip"
move "Scooby-Doo! - Classic Creep Capers (USA) (Rev 1).zip" "_REN\ScoobyDoo!ClassicCreepCapers(U)(Rev1).zip"
move "Scooby-Doo! - Classic Creep Capers (USA).zip" "_REN\Scooby-Doo! - Classic Creep Capers (U).zip"
move "SD Hiryuu no Ken Densetsu (Japan).zip" "_REN\SD Hiryuu no Ken Densetsu (J).zip"
move "Sesame Street - Elmo's Letter Adventure (USA).zip" "_REN\SesameStreet-Elmo'sLetterAdventure(U).zip"
move "Sesame Street - Elmo's Number Journey (USA).zip" "_REN\SesameStreet-Elmo'sNumberJourney(U).zip"
move "Shadow Man (Brazil).zip" "_REN\Shadow Man (B).zip"
move "Shadow Man (Europe) (En,Es,It).zip" "_REN\Shadow Man (E) (EnEsIt).zip"
move "Shadow Man (France).zip" "_REN\Shadow Man (F).zip"
move "Shadow Man (Germany).zip" "_REN\Shadow Man (G).zip"
move "Shadow Man (USA).zip" "_REN\Shadow Man (U).zip"
move "Shadowgate 64 - Trials of the Four Towers (Europe) (Es,It).zip" "_REN\Shadowgate64TrialsoftheFourTowers(E).zip"
move "Shadowgate 64 - Trials of the Four Towers (Europe) (Fr,De,Nl).zip" "_REN\Shadowgate64TrialsoftheFourTowers(E)_0.zip"
move "Shadowgate 64 - Trials of the Four Towers (Europe).zip" "_REN\Shadowgate64-TrialsoftheFourTowers(E).zip"
move "Shadowgate 64 - Trials of the Four Towers (Japan).zip" "_REN\Shadowgate64-TrialsoftheFourTowers(J).zip"
move "Shadowgate 64 - Trials of the Four Towers (USA) (En,Es) (Beta).zip" "_REN\Shadowgate64TrialsoftheFourTo(U)(Beta).zip"
move "Shadowgate 64 - Trials of the Four Towers (USA) (En,Es).zip" "_REN\Shadowgate64TrialsoftheFourTowers(U).zip"
move "Shin Nihon Pro Wrestling Toukon Road - Brave Spirits (Japan).zip" "_REN\ShinNihonProWrestlingToukonRoadBrav(J).zip"
move "Shin Nihon Pro Wrestling Toukon Road 2 - The Next Generation (Japan).zip" "_REN\ShinNihonProWrestlingToukonRoad2The(J).zip"
move "SimCity 2000 (Japan).zip" "_REN\SimCity 2000 (J).zip"
move "SimCopter 64 (USA) (Proto).zip" "_REN\SimCopter 64 (U) (Proto).zip"
move "Snobo Kids (Japan).zip" "_REN\Snobo Kids (J).zip"
move "Snow Speeder (Japan).zip" "_REN\Snow Speeder (J).zip"
move "Snowboard Kids (Europe, Australia).zip" "_REN\Snowboard Kids (E).zip"
move "Snowboard Kids (USA).zip" "_REN\Snowboard Kids (U).zip"
move "Snowboard Kids 2 (Australia).zip" "_REN\Snowboard Kids 2 (A).zip"
move "Snowboard Kids 2 (USA).zip" "_REN\Snowboard Kids 2 (U).zip"
move "Sonic Wings Assault (Japan).zip" "_REN\Sonic Wings Assault (J).zip"
move "South Park (Brazil).zip" "_REN\South Park (B).zip"
move "South Park (Europe) (En,Fr,Es).zip" "_REN\South Park (E) (EnFrEs).zip"
move "South Park (Germany).zip" "_REN\South Park (G).zip"
move "South Park (USA).zip" "_REN\South Park (U).zip"
move "South Park - Chef's Luv Shack (Europe).zip" "_REN\South Park - Chef's Luv Shack (E).zip"
move "South Park Rally (Europe) (Beta) (2000-01-08).zip" "_REN\SouthParkRally(E)(Beta)(2000-01-08).zip"
move "South Park Rally (Europe) (Beta) (2000-01-17).zip" "_REN\SouthParkRally(E)(Beta)(2000-01-17).zip"
move "South Park Rally (Europe).zip" "_REN\South Park Rally (E).zip"
move "South Park Rally (USA) (Beta) (2000-01-14).zip" "_REN\SouthParkRally(U)(Beta)(2000-01-14).zip"
move "South Park Rally (USA) (Beta) (2000-01-27).zip" "_REN\SouthParkRally(U)(Beta)(2000-01-27).zip"
move "South Park Rally (USA).zip" "_REN\South Park Rally (U).zip"
move "Space Dynamites (Japan).zip" "_REN\Space Dynamites (J).zip"
move "Space Invaders (USA).zip" "_REN\Space Invaders (U).zip"
move "SpaceStation Silicon Valley (Europe) (En,Fr,De,Es,It,Nl,Pt).zip" "_REN\SpaceStationSiliconValley(E).zip"
move "SpaceStation Silicon Valley (USA).zip" "_REN\SpaceStation Silicon Valley (U).zip"
move "Spider-Man (USA).zip" "_REN\Spider-Man (U).zip"
move "Star Fox 64 (Japan).zip" "_REN\Star Fox 64 (J).zip"
move "Star Fox 64 (USA) (Rev 1).zip" "_REN\Star Fox 64 (U) (Rev 1).zip"
move "Star Fox 64 (USA).zip" "_REN\Star Fox 64 (U).zip"
move "Star Soldier - Vanishing Earth (Japan).zip" "_REN\Star Soldier - Vanishing Earth (J).zip"
move "Star Soldier - Vanishing Earth (USA).zip" "_REN\Star Soldier - Vanishing Earth (U).zip"
move "Star Twins (Japan).zip" "_REN\Star Twins (J).zip"
move "Star Wars - Rogue Squadron (Europe) (En,Fr,De) (Rev 1).zip" "_REN\StarWarsRogueSquadron(E)(EnFrDe)(Rev1).zip"
move "Star Wars - Rogue Squadron (Europe) (En,Fr,De).zip" "_REN\StarWars-RogueSquadron(E)(EnFrDe).zip"
move "Star Wars - Rogue Squadron (USA) (Rev 1).zip" "_REN\Star Wars - Rogue Squadron (U) (Rev 1).zip"
move "Star Wars - Rogue Squadron (USA).zip" "_REN\Star Wars - Rogue Squadron (U).zip"
move "Star Wars - Shadows of the Empire (Europe).zip" "_REN\Star Wars - Shadows of the Empire (E).zip"
move "Star Wars - Shadows of the Empire (USA) (Beta) (1996-10-15).zip" "_REN\StarWarsShadowsoftheEmpire(U)(Beta).zip"
move "Star Wars - Shadows of the Empire (USA) (Rev 1).zip" "_REN\StarWars-ShadowsoftheEmpire(U)(Rev1).zip"
move "Star Wars - Shadows of the Empire (USA) (Rev 2).zip" "_REN\StarWars-ShadowsoftheEmpire(U)(Rev2).zip"
move "Star Wars - Shadows of the Empire (USA).zip" "_REN\Star Wars - Shadows of the Empire (U).zip"
move "Star Wars - Shutsugeki! Rogue Chuutai (Japan).zip" "_REN\StarWars-Shutsugeki!RogueChuutai(J).zip"
move "Star Wars - Teikoku no Kage (Japan).zip" "_REN\Star Wars - Teikoku no Kage (J).zip"
move "Star Wars Episode I - Battle for Naboo (Europe).zip" "_REN\StarWarsEpisodeI-BattleforNaboo(E).zip"
move "Star Wars Episode I - Battle for Naboo (USA) (Beta).zip" "_REN\StarWarsEpisodeIBattleforNabo(U)(Beta).zip"
move "Star Wars Episode I - Battle for Naboo (USA).zip" "_REN\StarWarsEpisodeI-BattleforNaboo(U).zip"
move "Star Wars Episode I - Racer (Europe) (En,Fr,De).zip" "_REN\StarWarsEpisodeI-Racer(E)(EnFrDe).zip"
move "Star Wars Episode I - Racer (Japan).zip" "_REN\Star Wars Episode I - Racer (J).zip"
move "Star Wars Episode I - Racer (USA).zip" "_REN\Star Wars Episode I - Racer (U).zip"
move "StarCraft 64 (Australia).zip" "_REN\StarCraft 64 (A).zip"
move "StarCraft 64 (Germany) (Proto).zip" "_REN\StarCraft 64 (G) (Proto).zip"
move "StarCraft 64 (USA) (Beta).zip" "_REN\StarCraft 64 (U) (Beta).zip"
move "StarCraft 64 (USA).zip" "_REN\StarCraft 64 (U).zip"
move "Starshot - Space Circus Fever (Europe) (En,Fr,De).zip" "_REN\Starshot-SpaceCircusFever(E)(EnFrDe).zip"
move "Starshot - Space Circus Fever (USA) (En,Fr,Es).zip" "_REN\Starshot-SpaceCircusFever(U)(EnFrEs).zip"
move "Stunt Racer 64 (USA).zip" "_REN\Stunt Racer 64 (U).zip"
move "Super B-Daman - Battle Phoenix 64 (Japan).zip" "_REN\Super B-Daman - Battle Phoenix 64 (J).zip"
move "Super Bowling (Japan).zip" "_REN\Super Bowling (J).zip"
move "Super Bowling (USA).zip" "_REN\Super Bowling (U).zip"
move "Super Mario 64 (Europe) (En,Fr,De).zip" "_REN\Super Mario 64 (E) (EnFrDe).zip"
move "Super Mario 64 (Japan) (Rev 3) (Shindou Edition).zip" "_REN\SuperMario64(J)(Rev3)(ShindouEdition).zip"
move "Super Mario 64 (Japan).zip" "_REN\Super Mario 64 (J).zip"
move "Super Mario 64 (USA).zip" "_REN\Super Mario 64 (U).zip"
move "Super Robot Spirits (Japan).zip" "_REN\Super Robot Spirits (J).zip"
move "Super Robot Taisen 64 (Japan).zip" "_REN\Super Robot Taisen 64 (J).zip"
move "Super Smash Bros. (Australia).zip" "_REN\Super Smash Bros. (A).zip"
move "Super Smash Bros. (Europe) (En,Fr,De).zip" "_REN\Super Smash Bros. (E) (EnFrDe).zip"
move "Super Smash Bros. (USA).zip" "_REN\Super Smash Bros. (U).zip"
move "Super Speed Race 64 (Japan).zip" "_REN\Super Speed Race 64 (J).zip"
move "Supercross 2000 (Europe) (En,Fr,De).zip" "_REN\Supercross 2000 (E) (EnFrDe).zip"
move "Supercross 2000 (USA).zip" "_REN\Supercross 2000 (U).zip"
move "Superman (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN\Superman (E) (EnFrDeEsItNl).zip"
move "Superman (USA) (Beta) (1998-09-06).zip" "_REN\Superman (U) (Beta) (1998-09-06).zip"
move "Superman - The New Superman Aventures (USA) (En,Fr,Es).zip" "_REN\SupermanTheNewSupermanAventures(U).zip"
move "Susume! Taisen Puzzle Dama - Toukon! Marutama Chou (Japan).zip" "_REN\SusumeTaisenPuzzleDamaToukonMarutam(J).zip"
move "Sydney 2000 (Europe) (Proto).zip" "_REN\Sydney 2000 (E) (Proto).zip"
move "Sydney 2000 (USA) (Proto).zip" "_REN\Sydney 2000 (U) (Proto).zip"
move "Tamiya Racing 64 (USA) (Proto).zip" "_REN\Tamiya Racing 64 (U) (Proto).zip"
move "Tarzan (Europe).zip" "_REN\Tarzan (E).zip"
move "Tarzan (France).zip" "_REN\Tarzan (F).zip"
move "Tarzan (Germany).zip" "_REN\Tarzan (G).zip"
move "Tarzan (USA).zip" "_REN\Tarzan (U).zip"
move "Taz Express (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN\Taz Express (E) (EnFrDeEsItNl).zip"
move "Taz Express (USA) (Proto) (2000-05-15).zip" "_REN\Taz Express (U) (Proto) (2000-05-15).zip"
move "Telefoot Soccer 2000 (France).zip" "_REN\Telefoot Soccer 2000 (F).zip"
move "temp.txt" "_REN\temp.txt"
move "Tetris 64 (Japan) (En).zip" "_REN\Tetris 64 (J) (En).zip"
move "Tetrisphere (Europe).zip" "_REN\Tetrisphere (E).zip"
move "Tetrisphere (USA).zip" "_REN\Tetrisphere (U).zip"
move "TG Rally 2 (Europe).zip" "_REN\TG Rally 2 (E).zip"
move "Tigger's Honey Hunt (Europe) (En,Fr,De,Es,It,Nl,Da).zip" "_REN\Tigger'sHoneyHunt(E)(EnFrDeEsItNlDa).zip"
move "Tigger's Honey Hunt (USA).zip" "_REN\Tigger's Honey Hunt (U).zip"
move "Tom and Jerry in Fists of Furry (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN\TomandJerryinFistsofFurry(E).zip"
move "Tom and Jerry in Fists of Furry (USA).zip" "_REN\Tom and Jerry in Fists of Furry (U).zip"
move "Tom Clancy's Rainbow Six (Europe).zip" "_REN\Tom Clancy's Rainbow Six (E).zip"
move "Tom Clancy's Rainbow Six (France).zip" "_REN\Tom Clancy's Rainbow Six (F).zip"
move "Tom Clancy's Rainbow Six (Germany).zip" "_REN\Tom Clancy's Rainbow Six (G).zip"
move "Tom Clancy's Rainbow Six (USA).zip" "_REN\Tom Clancy's Rainbow Six (U).zip"
move "Tommy Thunder (USA) (Proto) (1997-10-01).zip" "_REN\Tommy Thunder (U) (Proto) (1997-10-01).zip"
move "Tonic Trouble (Europe) (En,Fr,De,Es,It).zip" "_REN\Tonic Trouble (E) (EnFrDeEsIt).zip"
move "Tonic Trouble (USA) (Rev 1).zip" "_REN\Tonic Trouble (U) (Rev 1).zip"
move "Tony Hawk's Pro Skater (USA) (Beta).zip" "_REN\Tony Hawk's Pro Skater (U) (Beta).zip"
move "Tony Hawk's Pro Skater (USA) (Rev 1).zip" "_REN\Tony Hawk's Pro Skater (U) (Rev 1).zip"
move "Tony Hawk's Pro Skater (USA).zip" "_REN\Tony Hawk's Pro Skater (U).zip"
move "Tony Hawk's Pro Skater 2 (Europe).zip" "_REN\Tony Hawk's Pro Skater 2 (E).zip"
move "Tony Hawk's Pro Skater 2 (USA) (Beta) (2001-04-20).zip" "_REN\TonyHawksProSkater2(U)(Beta)(20010420).zip"
move "Tony Hawk's Pro Skater 2 (USA) (v012) (Beta) (2001-06-04).zip" "_REN\TonyHawksProSkater2(U)(Beta).zip"
move "Tony Hawk's Pro Skater 2 (USA).zip" "_REN\Tony Hawk's Pro Skater 2 (U).zip"
move "Tony Hawk's Pro Skater 3 (USA).zip" "_REN\Tony Hawk's Pro Skater 3 (U).zip"
move "Tony Hawk's Skateboarding (Europe).zip" "_REN\Tony Hawk's Skateboarding (E).zip"
move "Toon Panic (Japan) (Proto).zip" "_REN\Toon Panic (J) (Proto).zip"
move "Top Gear Hyper Bike (Europe).zip" "_REN\Top Gear Hyper Bike (E).zip"
move "Top Gear Hyper Bike (Japan).zip" "_REN\Top Gear Hyper Bike (J).zip"
move "Top Gear Hyper-Bike (USA) (Beta).zip" "_REN\Top Gear Hyper-Bike (U) (Beta).zip"
move "Top Gear Hyper-Bike (USA).zip" "_REN\Top Gear Hyper-Bike (U).zip"
move "Top Gear Overdrive (Europe).zip" "_REN\Top Gear Overdrive (E).zip"
move "Top Gear Overdrive (Japan).zip" "_REN\Top Gear Overdrive (J).zip"
move "Top Gear Overdrive (USA) (Beta).zip" "_REN\Top Gear Overdrive (U) (Beta).zip"
move "Top Gear Overdrive (USA).zip" "_REN\Top Gear Overdrive (U).zip"
move "Top Gear Rally (Asia) (En).zip" "_REN\Top Gear Rally (Asia) (En).zip"
move "Top Gear Rally (Europe).zip" "_REN\Top Gear Rally (E).zip"
move "Top Gear Rally (Japan).zip" "_REN\Top Gear Rally (J).zip"
move "Top Gear Rally (USA).zip" "_REN\Top Gear Rally (U).zip"
move "Top Gear Rally 2 (Europe) (Beta) (1999-08-31).zip" "_REN\TopGearRally2(E)(Beta)(1999-08-31).zip"
move "Top Gear Rally 2 (Europe).zip" "_REN\Top Gear Rally 2 (E).zip"
move "Top Gear Rally 2 (Japan).zip" "_REN\Top Gear Rally 2 (J).zip"
move "Top Gear Rally 2 (USA) (Beta).zip" "_REN\Top Gear Rally 2 (U) (Beta).zip"
move "Top Gear Rally 2 (USA).zip" "_REN\Top Gear Rally 2 (U).zip"
move "Toy Story 2 - Buzz l'Eclair a la Rescousse! (France).zip" "_REN\ToyStory2-Buzzl'EclairalaRescousse!(F).zip"
move "Toy Story 2 - Buzz Lightyear to the Rescue! (Europe).zip" "_REN\ToyStory2-BuzzLightyeartotheRescue!(E).zip"
move "Toy Story 2 - Buzz Lightyear to the Rescue! (USA) (Rev 1).zip" "_REN\ToyStory2BuzzLightyeartotheRe(U)(Rev1).zip"
move "Toy Story 2 - Buzz Lightyear to the Rescue! (USA).zip" "_REN\ToyStory2-BuzzLightyeartotheRescue!(U).zip"
move "Toy Story 2 - Captain Buzz Lightyear auf Rettungsmission! (Germany) (Rev 1).zip" "_REN\ToyStory2CaptainBuzzLightyear(G)(Rev1).zip"
move "Toy Story 2 - Captain Buzz Lightyear auf Rettungsmission! (Germany).zip" "_REN\ToyStory2CaptainBuzzLightyearaufRet(G).zip"
move "Transformers - Beast Wars Metals 64 (Japan).zip" "_REN\Transformers-BeastWarsMetals64(J).zip"
move "Transformers - Beast Wars Transmetals (USA).zip" "_REN\Transformers-BeastWarsTransmetals(U).zip"
move "Triple Play 2000 (USA).zip" "_REN\Triple Play 2000 (U).zip"
move "Tsumi to Batsu - Hoshi no Keishousha (Japan).zip" "_REN\TsumitoBatsu-HoshinoKeishousha(J).zip"
move "Turok - Dinosaur Hunter (Europe) (Rev 2).zip" "_REN\Turok - Dinosaur Hunter (E) (Rev 2).zip"
move "Turok - Dinosaur Hunter (Europe).zip" "_REN\Turok - Dinosaur Hunter (E).zip"
move "Turok - Dinosaur Hunter (Germany) (Rev 1).zip" "_REN\Turok - Dinosaur Hunter (G) (Rev 1).zip"
move "Turok - Dinosaur Hunter (Germany).zip" "_REN\Turok - Dinosaur Hunter (G).zip"
move "Turok - Dinosaur Hunter (USA).zip" "_REN\Turok - Dinosaur Hunter (U).zip"
move "Turok - Legenden des Verlorenen Landes (Germany).zip" "_REN\Turok-LegendendesVerlorenenLandes(G).zip"
move "Turok - Rage Wars (Europe) (En,Fr,It).zip" "_REN\Turok - Rage Wars (E) (EnFrIt).zip"
move "Turok - Rage Wars (Europe).zip" "_REN\Turok - Rage Wars (E).zip"
move "Turok - Rage Wars (USA) (Rev 1).zip" "_REN\Turok - Rage Wars (U) (Rev 1).zip"
move "Turok - Rage Wars (USA).zip" "_REN\Turok - Rage Wars (U).zip"
move "Turok 2 - Seeds of Evil (Europe) (En,Fr,Es,It).zip" "_REN\Turok 2 - Seeds of Evil (E) (EnFrEsIt).zip"
move "Turok 2 - Seeds of Evil (Europe).zip" "_REN\Turok 2 - Seeds of Evil (E).zip"
move "Turok 2 - Seeds of Evil (Germany).zip" "_REN\Turok 2 - Seeds of Evil (G).zip"
move "Turok 2 - Seeds of Evil (USA) (Demo) (Kiosk).zip" "_REN\Turok2-SeedsofEvil(U)(Demo)(Kiosk).zip"
move "Turok 2 - Seeds of Evil (USA).zip" "_REN\Turok 2 - Seeds of Evil (U).zip"
move "Turok 3 - Shadow of Oblivion (Europe) (Beta) (2000-05-31).zip" "_REN\Turok3ShadowofOblivion(E)(Beta).zip"
move "Turok 3 - Shadow of Oblivion (Europe) (Beta) (2000-06-06) [b].zip" "_REN\Turok3ShadowofOblivion(E)(Beta)_0.zip"
move "Turok 3 - Shadow of Oblivion (Europe) (Beta) (2000-07-10) [b].zip" "_REN\Turok3ShadowofOblivion(E)(Beta)_0_1.zip"
move "Turok 3 - Shadow of Oblivion (Europe) (Beta) (2000-07-16T220245).zip" "_REN\Turok3ShadowofOblivion(E)(Beta)_0_1_2.zip"
move "Turok 3 - Shadow of Oblivion (Europe) (Beta) (2000-07-18).zip" "_REN\Turok3ShadowofOblivion(E)(Beta)_0_1__3.zip"
move "Turok 3 - Shadow of Oblivion (Europe).zip" "_REN\Turok 3 - Shadow of Oblivion (E).zip"
move "Turok 3 - Shadow of Oblivion (USA) (Beta) (2000-05-03).zip" "_REN\Turok3ShadowofOblivion(U)(Beta).zip"
move "Turok 3 - Shadow of Oblivion (USA) (Beta) (2000-06-26).zip" "_REN\Turok3ShadowofOblivion(U)(Beta)_0.zip"
move "Turok 3 - Shadow of Oblivion (USA) (Beta) (2000-07-16).zip" "_REN\Turok3ShadowofOblivion(U)(Beta)_0_1.zip"
move "Turok 3 - Shadow of Oblivion (USA).zip" "_REN\Turok 3 - Shadow of Oblivion (U).zip"
move "Twisted Edge - Extreme Snowboarding (USA).zip" "_REN\TwistedEdge-ExtremeSnowboarding(U).zip"
move "Twisted Edge - Snowboarding (Europe).zip" "_REN\Twisted Edge - Snowboarding (E).zip"
move "Utchan Nanchan no Hono no Challenger - Denryuu Ira Ira Bou (Japan).zip" "_REN\UtchanNanchannoHononoChallengerDenr(J).zip"
move "V-Rally Edition 99 (Europe) (En,Fr,De).zip" "_REN\V-Rally Edition 99 (E) (EnFrDe).zip"
move "V-Rally Edition 99 (Japan).zip" "_REN\V-Rally Edition 99 (J).zip"
move "V-Rally Edition 99 (USA).zip" "_REN\V-Rally Edition 99 (U).zip"
move "Viewpoint 2064 (Japan) (Proto).zip" "_REN\Viewpoint 2064 (J) (Proto).zip"
move "Vigilante 8 (Europe).zip" "_REN\Vigilante 8 (E).zip"
move "Vigilante 8 (France).zip" "_REN\Vigilante 8 (F).zip"
move "Vigilante 8 (Germany).zip" "_REN\Vigilante 8 (G).zip"
move "Vigilante 8 (USA).zip" "_REN\Vigilante 8 (U).zip"
move "Vigilante 8 - 2nd Offense (Europe).zip" "_REN\Vigilante 8 - 2nd Offense (E).zip"
move "Vigilante 8 - 2nd Offense (USA).zip" "_REN\Vigilante 8 - 2nd Offense (U).zip"
move "Violence Killer - Turok New Generation (Japan).zip" "_REN\ViolenceKiller-TurokNewGeneration(J).zip"
move "Virtual Chess 64 (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN\Virtual Chess 64 (E) (EnFrDeEsItNl).zip"
move "Virtual Chess 64 (USA) (En,Fr,Es).zip" "_REN\Virtual Chess 64 (U) (EnFrEs).zip"
move "Virtual Pool 64 (Europe).zip" "_REN\Virtual Pool 64 (E).zip"
move "Virtual Pool 64 (USA).zip" "_REN\Virtual Pool 64 (U).zip"
move "Virtual Pro Wrestling 2 - Oudou Keishou (Japan).zip" "_REN\VirtualProWrestling2-OudouKeishou(J).zip"
move "Virtual Pro Wrestling 64 (Japan).zip" "_REN\Virtual Pro Wrestling 64 (J).zip"
move "Waialae Country Club - True Golf Classics (Europe) (Rev 1).zip" "_REN\WaialaeCountryClubTrueGolfCla(E)(Rev1).zip"
move "Waialae Country Club - True Golf Classics (Europe).zip" "_REN\WaialaeCountryClub-TrueGolfClassics(E).zip"
move "Waialae Country Club - True Golf Classics (USA) (Rev 1).zip" "_REN\WaialaeCountryClubTrueGolfCla(U)(Rev1).zip"
move "Waialae Country Club - True Golf Classics (USA).zip" "_REN\WaialaeCountryClub-TrueGolfClassics(U).zip"
move "War Gods (Europe).zip" "_REN\War Gods (E).zip"
move "War Gods (USA).zip" "_REN\War Gods (U).zip"
move "Wave Race 64 - Kawasaki Jet Ski (Europe) (En,De).zip" "_REN\WaveRace64-KawasakiJetSki(E)(EnDe).zip"
move "Wave Race 64 - Kawasaki Jet Ski (Japan) (Rev 1).zip" "_REN\WaveRace64-KawasakiJetSki(J)(Rev1).zip"
move "Wave Race 64 - Kawasaki Jet Ski (Japan) (Rev 2) (Shindou Edition).zip" "_REN\WaveRace64KawasakiJetSki(J)(Rev2).zip"
move "Wave Race 64 - Kawasaki Jet Ski (Japan).zip" "_REN\Wave Race 64 - Kawasaki Jet Ski (J).zip"
move "Wave Race 64 - Kawasaki Jet Ski (USA) (Rev 1).zip" "_REN\WaveRace64-KawasakiJetSki(U)(Rev1).zip"
move "Wave Race 64 - Kawasaki Jet Ski (USA).zip" "_REN\Wave Race 64 - Kawasaki Jet Ski (U).zip"
move "Wayne Gretzky's 3D Hockey '98 (Europe) (En,Fr,De,Es).zip" "_REN\WayneGretzky's3DHockey'98(E)(EnFrDeEs).zip"
move "Wayne Gretzky's 3D Hockey '98 (USA).zip" "_REN\Wayne Gretzky's 3D Hockey '98 (U).zip"
move "Wayne Gretzky's 3D Hockey (Europe) (En,Fr,De,Es).zip" "_REN\WayneGretzky's3DHockey(E)(EnFrDeEs).zip"
move "Wayne Gretzky's 3D Hockey (Japan).zip" "_REN\Wayne Gretzky's 3D Hockey (J).zip"
move "Wayne Gretzky's 3D Hockey (USA) (Rev 1).zip" "_REN\Wayne Gretzky's 3D Hockey (U) (Rev 1).zip"
move "Wayne Gretzky's 3D Hockey (USA).zip" "_REN\Wayne Gretzky's 3D Hockey (U).zip"
move "WCW Backstage Assault (USA).zip" "_REN\WCW Backstage Assault (U).zip"
move "WCW Mayhem (Europe).zip" "_REN\WCW Mayhem (E).zip"
move "WCW Mayhem (USA).zip" "_REN\WCW Mayhem (U).zip"
move "WCW Nitro (USA).zip" "_REN\WCW Nitro (U).zip"
move "WCW vs. nWo - World Tour (Europe).zip" "_REN\WCW vs. nWo - World Tour (E).zip"
move "WCW vs. nWo - World Tour (USA) (Rev 1).zip" "_REN\WCW vs. nWo - World Tour (U) (Rev 1).zip"
move "WCW vs. nWo - World Tour (USA).zip" "_REN\WCW vs. nWo - World Tour (U).zip"
move "WCW-nWo Revenge (Europe).zip" "_REN\WCW-nWo Revenge (E).zip"
move "WCW-nWo Revenge (USA).zip" "_REN\WCW-nWo Revenge (U).zip"
move "Wetrix (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN\Wetrix (E) (EnFrDeEsItNl).zip"
move "Wetrix (Japan).zip" "_REN\Wetrix (J).zip"
move "Whack 'n' Roll (USA) (v0.8.2) (Beta) (1998-02-05).zip" "_REN\Whack'n'Roll(U)(v082)(Beta)(19980205).zip"
move "Wheel of Fortune (USA).zip" "_REN\Wheel of Fortune (U).zip"
move "Wide-Boy64 AGB (World) (v0.00b) (Beta).zip" "_REN\Wide-Boy64 AGB (U) (v0.00b) (Beta).zip"
move "Wide-Boy64 AGB (World) (v0.02c).zip" "_REN\Wide-Boy64 AGB (U) (v0.02c).zip"
move "Wide-Boy64 AGB (World) (v0.04c).zip" "_REN\Wide-Boy64 AGB (U) (v0.04c).zip"
move "Wide-Boy64 CGB (World) (v1.02).zip" "_REN\Wide-Boy64 CGB (U) (v1.02).zip"
move "Wild Choppers (Japan).zip" "_REN\Wild Choppers (J).zip"
move "Wildwaters (USA) (1999-06-15) (Proto).zip" "_REN\Wildwaters (U) (1999-06-15) (Proto).zip"
move "WinBack (Japan) (Rev 1).zip" "_REN\WinBack (J) (Rev 1).zip"
move "WinBack (Japan).zip" "_REN\WinBack (J).zip"
move "WinBack - Covert Operations (USA).zip" "_REN\WinBack - Covert Operations (U).zip"
move "Wipeout 64 (Europe) (Beta).zip" "_REN\Wipeout 64 (E) (Beta).zip"
move "Wipeout 64 (Europe).zip" "_REN\Wipeout 64 (E).zip"
move "Wipeout 64 (USA).zip" "_REN\Wipeout 64 (U).zip"
move "Wonder Project J2 - Koruro no Mori no Jozet (Japan).zip" "_REN\WonderProjectJ2-KoruronoMorinoJozet(J).zip"
move "World Cup 98 (Europe) (En,Fr,De,Es,It,Nl,Sv,Da).zip" "_REN\World Cup 98 (E) (EnFrDeEsItNlSvDa).zip"
move "World Cup 98 (USA) (En,Fr,De,Es,It,Nl,Sv,Da).zip" "_REN\World Cup 98 (U) (EnFrDeEsItNlSvDa).zip"
move "World Driver Championship (Europe) (En,Fr,De,Es,It).zip" "_REN\WorldDriverChampionship(E)(EnFrDeEsIt).zip"
move "World Driver Championship (USA).zip" "_REN\World Driver Championship (U).zip"
move "Worms Armageddon (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN\Worms Armageddon (E) (EnFrDeEsItNl).zip"
move "Worms Armageddon (USA) (En,Fr,Es).zip" "_REN\Worms Armageddon (U) (EnFrEs).zip"
move "WWF Attitude (Europe).zip" "_REN\WWF Attitude (E).zip"
move "WWF Attitude (Germany).zip" "_REN\WWF Attitude (G).zip"
move "WWF Attitude (USA).zip" "_REN\WWF Attitude (U).zip"
move "WWF No Mercy (Europe) (Rev 1).zip" "_REN\WWF No Mercy (E) (Rev 1).zip"
move "WWF No Mercy (Europe).zip" "_REN\WWF No Mercy (E).zip"
move "WWF No Mercy (USA) (Beta) (2000-09-11).zip" "_REN\WWF No Mercy (U) (Beta) (2000-09-11).zip"
move "WWF No Mercy (USA) (Rev 1).zip" "_REN\WWF No Mercy (U) (Rev 1).zip"
move "WWF No Mercy (USA).zip" "_REN\WWF No Mercy (U).zip"
move "WWF War Zone (Europe).zip" "_REN\WWF War Zone (E).zip"
move "WWF War Zone (USA).zip" "_REN\WWF War Zone (U).zip"
move "WWF WrestleMania 2000 (Europe).zip" "_REN\WWF WrestleMania 2000 (E).zip"
move "WWF WrestleMania 2000 (Japan).zip" "_REN\WWF WrestleMania 2000 (J).zip"
move "WWF WrestleMania 2000 (USA).zip" "_REN\WWF WrestleMania 2000 (U).zip"
move "X'treme Roller (USA) (Proto).zip" "_REN\X'treme Roller (U) (Proto).zip"
move "Xena - Warrior Princess - The Talisman of Fate (Europe).zip" "_REN\XenaWarriorPrincessTheTalismanofFat(E).zip"
move "Xena - Warrior Princess - The Talisman of Fate (USA).zip" "_REN\XenaWarriorPrincessTheTalismanofFat(U).zip"
move "Yakouchuu II - Satsujin Kouro (Japan).zip" "_REN\Yakouchuu II - Satsujin Kouro (J).zip"
move "Yoshi Story (Japan).zip" "_REN\Yoshi Story (J).zip"
move "Yoshi's Story (Europe) (En,Fr,De).zip" "_REN\Yoshi's Story (E) (EnFrDe).zip"
move "Yoshi's Story (USA) (En,Ja).zip" "_REN\Yoshi's Story (U) (EnJa).zip"
move "Yuke Yuke!! Trouble Makers (Japan).zip" "_REN\Yuke Yuke!! Trouble Makers (J).zip"
move "Zelda no Densetsu - Mujura no Kamen (Japan) (GameCube).zip" "_REN\ZeldanoDensetsuMujuranoKamen(J)(GC).zip"
move "Zelda no Densetsu - Mujura no Kamen (Japan) (Rev 1).zip" "_REN\ZeldanoDensetsu-MujuranoKamen(J)(Rev1).zip"
move "Zelda no Densetsu - Mujura no Kamen (Japan).zip" "_REN\ZeldanoDensetsu-MujuranoKamen(J).zip"
move "Zelda no Densetsu - Toki no Ocarina (Japan) (GameCube, Zelda Collection).zip" "_REN\ZeldanoDensetsuTokinoOcarina(J)(GC).zip"
move "Zelda no Densetsu - Toki no Ocarina GC (Japan) (GameCube).zip" "_REN\ZeldanoDensetsuTokinoOcarinaGC(J)(GC).zip"
move "Zelda no Densetsu - Toki no Ocarina GC Ura (Japan) (GameCube).zip" "_REN\ZeldanoDensetsuTokinoOcarinaGCU(J)(GC).zip"
move "Zool - Majuu Tsukai Densetsu (Japan).zip" "_REN\Zool - Majuu Tsukai Densetsu (J).zip"
