@echo off

rem //move roms not in surreal.ini
md _NOT_SURREAL64
move "FIFA Soccer 64 (USA) (En,Fr,De).zip" _NOT_SURREAL64
move "GameBooster 64 (USA) (v1.1) (Unl).zip" _NOT_SURREAL64
move "Nintendo 64 Modem (Japan) (Add-on).zip" _NOT_SURREAL64
move "South Park - Chef's Luv Shack (USA).zip" _NOT_SURREAL64
move "SpaceStation Silicon Valley (USA) (Rev 1).zip" _NOT_SURREAL64
move "Turok - Dinosaur Hunter (Europe) (Rev 1).zip" _NOT_SURREAL64
move "Turok - Dinosaur Hunter (Germany) (Rev 2).zip" _NOT_SURREAL64
move "Turok - Dinosaur Hunter (USA) (Rev 1).zip" _NOT_SURREAL64
move "Turok - Dinosaur Hunter (USA) (Rev 2).zip" _NOT_SURREAL64
move "Turok 2 - Seeds of Evil (USA) (Demo) (Kiosk).zip" _NOT_SURREAL64
move "Turok 2 - Seeds of Evil (USA) (Rev 1).zip" _NOT_SURREAL64
move "Wetrix (USA) (En,Fr,De,Es,It,Nl).zip" _NOT_SURREAL64
move "Zelda no Densetsu - Toki no Ocarina (Japan) (Rev 1).zip" _NOT_SURREAL64
move "Zelda no Densetsu - Toki no Ocarina (Japan) (Rev 2).zip" _NOT_SURREAL64
move "Zelda no Densetsu - Toki no Ocarina (Japan).zip" _NOT_SURREAL64
move "Blues Brothers 2000 (Europe) (En,Fr,De,Es,It,Nl) (Beta) (2000-01-15) (#53).zip" _NOT_SURREAL64
move "F-1 World Grand Prix (Europe) (Beta).zip" _NOT_SURREAL64
move "F-Zero X (USA) (Beta) (The Legend of Zelda Ocarina of Time Overdump).zip" _NOT_SURREAL64
move "Mortal Kombat Trilogy (USA) (Beta) (1996-05-13).zip" _NOT_SURREAL64
move "Turok 3 - Shadow of Oblivion (USA) (Beta) (2000-07-21).zip" _NOT_SURREAL64
move "Xplorer 64 (Germany) (v1.067) (Unl).zip" _NOT_SURREAL64
move "SpaceStation Silicon Valley (Japan) (Proto).zip" _NOT_SURREAL64
move "Cruis'n USA (USA) (Wii Virtual Console).zip" _NOT_SURREAL64
move "Legend of Zelda, The - Majora's Mask (Europe) (En,Fr,De,Es) (Rev 1) (Wii Virtual Console).zip" _NOT_SURREAL64
move "Mario Party 2 (Europe) (En,Fr,De,Es,It) (Wii Virtual Console).zip" _NOT_SURREAL64
move "Mario Party 2 (Japan) (Wii Virtual Console).zip" _NOT_SURREAL64
move "Mario Party 2 (USA) (Wii Virtual Console).zip" _NOT_SURREAL64
move "Mario Tennis (Europe) (Wii Virtual Console).zip" _NOT_SURREAL64
move "Mario Tennis (USA) (Wii Virtual Console).zip" _NOT_SURREAL64
move "Mario Tennis 64 (Japan) (Wii Virtual Console).zip" _NOT_SURREAL64
move "Ogre Battle 64 - Person of Lordly Caliber (Japan) (Rev 1) (Wii Virtual Console).zip" _NOT_SURREAL64
move "Ogre Battle 64 - Person of Lordly Caliber (USA, Europe) (Rev 1) (Wii Virtual Console).zip" _NOT_SURREAL64
move "Pokemon Puzzle League (Europe) (Wii Virtual Console).zip" _NOT_SURREAL64
move "Pokemon Puzzle League (France) (Wii Virtual Console).zip" _NOT_SURREAL64
move "Pokemon Puzzle League (Germany) (Wii Virtual Console).zip" _NOT_SURREAL64
move "Pokemon Puzzle League (USA) (Wii Virtual Console).zip" _NOT_SURREAL64
move "Pokemon Snap (Japan) (Rev 1) (Wii Virtual Console).zip" _NOT_SURREAL64
move "Star Fox 64 (Japan) (Rev 1) (Wii Virtual Console).zip" _NOT_SURREAL64


choice /m "do you want to rename to FATX?"
if %errorlevel% equ 2 exit

md _REN64
move "007 - The World Is Not Enough (Europe) (En,Fr,De).zip" "_REN64\007-TheWorldIsNotEnough(E)(EnFrDe).zip"
move "007 - The World Is Not Enough (USA) (v2) (Beta).zip" "_REN64\007-TheWorldIsNotEnough(U)(v2)(Beta).zip"
move "007 - The World Is Not Enough (USA) (v21) (Beta).zip" "_REN64\007-TheWorldIsNotEnough(U)(v21)(Beta).zip"
move "007 - The World Is Not Enough (USA).zip" "_REN64\007 - The World Is Not Enough (U).zip"
move "1080 Snowboarding (Europe) (En,Ja,Fr,De).zip" "_REN64\1080 Snowboarding (E) (EnJaFrDe).zip"
move "1080 Snowboarding (Japan, USA) (En,Ja).zip" "_REN64\1080 Snowboarding (Japan USA) (EnJa).zip"
move "3D Model RGB Test Program (USA) (Test Program).zip" "_REN64\3DModelRGBTestProgram(U)(TestProgram).zip"
move "40 Winks (Europe) (En,Es,It) (Proto) (1999-10-07).zip" "_REN64\40Winks(E)(EnEsIt)(Proto)(1999-10-07).zip"
move "40 Winks (USA) (Aftermarket) (Unl).zip" "_REN64\40 Winks (U) (Aftermarket) (Unl).zip"
move "40 Winks (USA) (Proto) (2000-01-10).zip" "_REN64\40 Winks (U) (Proto) (2000-01-10).zip"
move "64 de Hakken!! Tamagotchi - Minna de Tamagotchi World (Japan).zip" "_REN64\64deHakkenTamagotchiMinnadeTamagotc(J).zip"
move "64 Hanafuda - Tenshi no Yakusoku (Japan).zip" "_REN64\64 Hanafuda - Tenshi no Yakusoku (J).zip"
move "64 Oozumou (Japan).zip" "_REN64\64 Oozumou (J).zip"
move "64 Oozumou 2 (Japan).zip" "_REN64\64 Oozumou 2 (J).zip"
move "64 Trump Collection - Alice no Wakuwaku Trump World (Japan).zip" "_REN64\64TrumpCollectionAlicenoWakuwakuTru(J).zip"
move "Action Replay Pro 64 (Europe) (v3.0) (Unl).zip" "_REN64\Action Replay Pro 64 (E) (v3.0) (Unl).zip"
move "Action Replay Pro 64 (Europe) (v3.3) (Unl).zip" "_REN64\Action Replay Pro 64 (E) (v3.3) (Unl).zip"
move "AeroFighters Assault (Europe) (En,Fr,De).zip" "_REN64\AeroFighters Assault (E) (EnFrDe).zip"
move "AeroFighters Assault (USA).zip" "_REN64\AeroFighters Assault (U).zip"
move "AeroGauge (Europe) (En,Fr,De).zip" "_REN64\AeroGauge (E) (EnFrDe).zip"
move "AeroGauge (Japan) (Demo) (Kiosk).zip" "_REN64\AeroGauge (J) (Demo) (Kiosk).zip"
move "AeroGauge (Japan) (Rev 1).zip" "_REN64\AeroGauge (J) (Rev 1).zip"
move "AeroGauge (USA).zip" "_REN64\AeroGauge (U).zip"
move "AI Shougi 3 (Japan).zip" "_REN64\AI Shougi 3 (J).zip"
move "Aidyn Chronicles - The First Mage (Europe).zip" "_REN64\Aidyn Chronicles - The First Mage (E).zip"
move "Aidyn Chronicles - The First Mage (USA) (Beta) (2000-02-10).zip" "_REN64\AidynChroniclesTheFirstMage(U)(Beta).zip"
move "Aidyn Chronicles - The First Mage (USA) (Beta) (2000-05-09).zip" "_REN64\AidynChroniclesTheFirstMage(U)(Beta)_0.zip"
move "Aidyn Chronicles - The First Mage (USA) (Rev 1).zip" "_REN64\AidynChronicles-TheFirstMage(U)(Rev1).zip"
move "Aidyn Chronicles - The First Mage (USA).zip" "_REN64\Aidyn Chronicles - The First Mage (U).zip"
move "Air Boarder 64 (Japan).zip" "_REN64\Air Boarder 64 (J).zip"
move "Airboarder 64 (Europe).zip" "_REN64\Airboarder 64 (E).zip"
move "Akumajou Dracula Mokushiroku - Real Action Adventure (Japan).zip" "_REN64\AkumajouDraculaMokushirokuRealActio(J).zip"
move "Akumajou Dracula Mokushiroku Gaiden - Legend of Cornell (Japan).zip" "_REN64\AkumajouDraculaMokushirokuGaidenLeg(J).zip"
move "All Star Tennis '99 (Europe) (En,Fr,De,Es,It).zip" "_REN64\All Star Tennis '99 (E) (EnFrDeEsIt).zip"
move "All Star Tennis 99 (USA).zip" "_REN64\All Star Tennis 99 (U).zip"
move "All-Star Baseball 2000 (Europe).zip" "_REN64\All-Star Baseball 2000 (E).zip"
move "All-Star Baseball 2000 (USA).zip" "_REN64\All-Star Baseball 2000 (U).zip"
move "All-Star Baseball 2001 (USA).zip" "_REN64\All-Star Baseball 2001 (U).zip"
move "All-Star Baseball 99 (Europe).zip" "_REN64\All-Star Baseball 99 (E).zip"
move "All-Star Baseball 99 (USA).zip" "_REN64\All-Star Baseball 99 (U).zip"
move "Armorines - Project S.W.A.R.M. (Europe).zip" "_REN64\Armorines - Project S.W.A.R.M. (E).zip"
move "Armorines - Project S.W.A.R.M. (Germany).zip" "_REN64\Armorines - Project S.W.A.R.M. (G).zip"
move "Armorines - Project S.W.A.R.M. (USA).zip" "_REN64\Armorines - Project S.W.A.R.M. (U).zip"
move "Army Men - Air Combat (USA).zip" "_REN64\Army Men - Air Combat (U).zip"
move "Army Men - Sarge's Heroes (Europe) (En,Fr,De).zip" "_REN64\Army Men - Sarge's Heroes (E) (EnFrDe).zip"
move "Army Men - Sarge's Heroes (USA).zip" "_REN64\Army Men - Sarge's Heroes (U).zip"
move "Army Men - Sarge's Heroes 2 (USA).zip" "_REN64\Army Men - Sarge's Heroes 2 (U).zip"
move "Asteroids Hyper 64 (USA).zip" "_REN64\Asteroids Hyper 64 (U).zip"
move "Automobili Lamborghini (Europe).zip" "_REN64\Automobili Lamborghini (E).zip"
move "Automobili Lamborghini (USA).zip" "_REN64\Automobili Lamborghini (U).zip"
move "Baku Bomberman (Japan).zip" "_REN64\Baku Bomberman (J).zip"
move "Baku Bomberman 2 (Japan).zip" "_REN64\Baku Bomberman 2 (J).zip"
move "Bakuretsu Muteki Bangaioh (Japan).zip" "_REN64\Bakuretsu Muteki Bangaioh (J).zip"
move "Bakushou Jinsei 64 - Mezase! Resort Ou (Japan).zip" "_REN64\BakushouJinsei64-Mezase!ResortOu(J).zip"
move "Banjo to Kazooie no Daibouken (Japan).zip" "_REN64\Banjo to Kazooie no Daibouken (J).zip"
move "Banjo to Kazooie no Daibouken 2 (Japan).zip" "_REN64\Banjo to Kazooie no Daibouken 2 (J).zip"
move "Banjo-Kazooie (Europe) (En,Fr,De).zip" "_REN64\Banjo-Kazooie (E) (EnFrDe).zip"
move "Banjo-Kazooie (USA) (Rev 1).zip" "_REN64\Banjo-Kazooie (U) (Rev 1).zip"
move "Banjo-Kazooie (USA).zip" "_REN64\Banjo-Kazooie (U).zip"
move "Banjo-Tooie (Australia).zip" "_REN64\Banjo-Tooie (A).zip"
move "Banjo-Tooie (Europe) (En,Fr,De,Es).zip" "_REN64\Banjo-Tooie (E) (EnFrDeEs).zip"
move "Banjo-Tooie (USA).zip" "_REN64\Banjo-Tooie (U).zip"
move "Bass Rush - ECOGEAR PowerWorm Championship (Japan).zip" "_REN64\BassRushECOGEARPowerWormChampionshi(J).zip"
move "Bassmasters 2000 (USA) (Beta).zip" "_REN64\Bassmasters 2000 (U) (Beta).zip"
move "Bassmasters 2000 (USA).zip" "_REN64\Bassmasters 2000 (U).zip"
move "Batman Beyond - Return of the Joker (USA).zip" "_REN64\BatmanBeyond-ReturnoftheJoker(U).zip"
move "Batman of the Future - Return of the Joker (Europe) (En,Fr,De).zip" "_REN64\BatmanoftheFutureReturnoftheJoker(E).zip"
move "BattleTanx (USA).zip" "_REN64\BattleTanx (U).zip"
move "BattleTanx - Global Assault (Europe) (En,Fr,De).zip" "_REN64\BattleTanx-GlobalAssault(E)(EnFrDe).zip"
move "BattleTanx - Global Assault (USA).zip" "_REN64\BattleTanx - Global Assault (U).zip"
move "Battlezone - Rise of the Black Dogs (USA).zip" "_REN64\Battlezone-RiseoftheBlackDogs(U).zip"
move "Beetle Adventure Racing! (Europe) (En,Fr,De).zip" "_REN64\Beetle Adventure Racing! (E) (EnFrDe).zip"
move "Beetle Adventure Racing! (Japan).zip" "_REN64\Beetle Adventure Racing! (J).zip"
move "Beetle Adventure Racing! (USA) (En,Fr,De).zip" "_REN64\Beetle Adventure Racing! (U) (EnFrDe).zip"
move "Big Mountain 2000 (USA).zip" "_REN64\Big Mountain 2000 (U).zip"
move "Bio F.R.E.A.K.S. (Europe).zip" "_REN64\Bio F.R.E.A.K.S. (E).zip"
move "Bio F.R.E.A.K.S. (USA).zip" "_REN64\Bio F.R.E.A.K.S. (U).zip"
move "Biohazard 2 (Japan).zip" "_REN64\Biohazard 2 (J).zip"
move "Blast Corps (Europe) (En,De).zip" "_REN64\Blast Corps (E) (EnDe).zip"
move "Blast Corps (USA) (Rev 1).zip" "_REN64\Blast Corps (U) (Rev 1).zip"
move "Blast Corps (USA).zip" "_REN64\Blast Corps (U).zip"
move "Blastdozer (Japan).zip" "_REN64\Blastdozer (J).zip"
move "Blues Brothers 2000 (Europe) (En,Fr,De,Es,It,Nl) (Beta) (2000-01-15) (#20).zip" "_REN64\BluesBrothers2000(E)(Beta).zip"
move "Blues Brothers 2000 (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN64\Blues Brothers 2000 (E) (EnFrDeEsItNl).zip"
move "Blues Brothers 2000 (USA).zip" "_REN64\Blues Brothers 2000 (U).zip"
move "Body Harvest (Europe) (En,Fr,De).zip" "_REN64\Body Harvest (E) (EnFrDe).zip"
move "Body Harvest (USA).zip" "_REN64\Body Harvest (U).zip"
move "Bokujou Monogatari 2 (Japan) (Rev 1).zip" "_REN64\Bokujou Monogatari 2 (J) (Rev 1).zip"
move "Bokujou Monogatari 2 (Japan) (Rev 2).zip" "_REN64\Bokujou Monogatari 2 (J) (Rev 2).zip"
move "Bokujou Monogatari 2 (Japan).zip" "_REN64\Bokujou Monogatari 2 (J).zip"
move "Bomberman 64 (Europe).zip" "_REN64\Bomberman 64 (E).zip"
move "Bomberman 64 (Japan) [b].zip" "_REN64\Bomberman 64 (J) [b].zip"
move "Bomberman 64 (USA).zip" "_REN64\Bomberman 64 (U).zip"
move "Bomberman 64 - The Second Attack! (USA).zip" "_REN64\Bomberman 64 - The Second Attack! (U).zip"
move "Bomberman Hero (Europe).zip" "_REN64\Bomberman Hero (E).zip"
move "Bomberman Hero (USA).zip" "_REN64\Bomberman Hero (U).zip"
move "Bomberman Hero - Mirian Oujo o Sukue! (Japan).zip" "_REN64\BombermanHero-MirianOujooSukue!(J).zip"
move "Bottom of the 9th (USA).zip" "_REN64\Bottom of the 9th (U).zip"
move "Brunswick Circuit Pro Bowling (USA).zip" "_REN64\Brunswick Circuit Pro Bowling (U).zip"
move "Buck Bumble (Europe) (En,Fr,De,Es,It).zip" "_REN64\Buck Bumble (E) (EnFrDeEsIt).zip"
move "Buck Bumble (Japan).zip" "_REN64\Buck Bumble (J).zip"
move "Buck Bumble (USA).zip" "_REN64\Buck Bumble (U).zip"
move "Bug's Life, A (Europe).zip" "_REN64\Bug's Life A (E).zip"
move "Bug's Life, A (France).zip" "_REN64\Bug's Life A (F).zip"
move "Bug's Life, A (Germany).zip" "_REN64\Bug's Life A (G).zip"
move "Bug's Life, A (Italy).zip" "_REN64\Bug's Life A (I).zip"
move "Bug's Life, A (USA).zip" "_REN64\Bug's Life A (U).zip"
move "Bust-A-Move '99 (USA).zip" "_REN64\Bust-A-Move '99 (U).zip"
move "Bust-A-Move 2 - Arcade Edition (Europe).zip" "_REN64\Bust-A-Move 2 - Arcade Edition (E).zip"
move "Bust-A-Move 2 - Arcade Edition (USA).zip" "_REN64\Bust-A-Move 2 - Arcade Edition (U).zip"
move "Bust-A-Move 3 DX (Europe).zip" "_REN64\Bust-A-Move 3 DX (E).zip"
move "California Speed (Europe) (Proto).zip" "_REN64\California Speed (E) (Proto).zip"
move "California Speed (USA).zip" "_REN64\California Speed (U).zip"
move "Carmageddon 64 (Europe) (En,Fr,De,Es).zip" "_REN64\Carmageddon 64 (E) (EnFrDeEs).zip"
move "Carmageddon 64 (Europe) (En,Fr,Es,It).zip" "_REN64\Carmageddon 64 (E) (EnFrEsIt).zip"
move "Carmageddon 64 (USA).zip" "_REN64\Carmageddon 64 (U).zip"
move "Carnivale - Cenzo's Adventure (USA) (Proto).zip" "_REN64\Carnivale-Cenzo'sAdventure(U)(Proto).zip"
move "Castlevania (Europe) (En,Fr,De).zip" "_REN64\Castlevania (E) (EnFrDe).zip"
move "Castlevania (USA) (Rev 1).zip" "_REN64\Castlevania (U) (Rev 1).zip"
move "Castlevania (USA) (Rev 2).zip" "_REN64\Castlevania (U) (Rev 2).zip"
move "Castlevania (USA).zip" "_REN64\Castlevania (U).zip"
move "Castlevania - Legacy of Darkness (Europe) (En,Fr,De).zip" "_REN64\CastlevaniaLegacyofDarkness(E)(EnFrDe).zip"
move "Castlevania - Legacy of Darkness (USA).zip" "_REN64\Castlevania - Legacy of Darkness (U).zip"
move "Centre Court Tennis (Europe).zip" "_REN64\Centre Court Tennis (E).zip"
move "Chameleon Twist (Europe).zip" "_REN64\Chameleon Twist (E).zip"
move "Chameleon Twist (Japan).zip" "_REN64\Chameleon Twist (J).zip"
move "Chameleon Twist (USA) (Rev 1).zip" "_REN64\Chameleon Twist (U) (Rev 1).zip"
move "Chameleon Twist (USA).zip" "_REN64\Chameleon Twist (U).zip"
move "Chameleon Twist 2 (Europe).zip" "_REN64\Chameleon Twist 2 (E).zip"
move "Chameleon Twist 2 (Japan).zip" "_REN64\Chameleon Twist 2 (J).zip"
move "Chameleon Twist 2 (USA).zip" "_REN64\Chameleon Twist 2 (U).zip"
move "Charlie Blast's Territory (Europe).zip" "_REN64\Charlie Blast's Territory (E).zip"
move "Charlie Blast's Territory (USA).zip" "_REN64\Charlie Blast's Territory (U).zip"
move "Chopper Attack (Europe).zip" "_REN64\Chopper Attack (E).zip"
move "Chopper Attack (USA).zip" "_REN64\Chopper Attack (U).zip"
move "Choro Q 64 (Japan).zip" "_REN64\Choro Q 64 (J).zip"
move "Choro Q 64 2 - Hacha Mecha Grand Prix Race (Japan).zip" "_REN64\ChoroQ642-HachaMechaGrandPrixRace(J).zip"
move "Chou Kuukan Nighter Pro Yakyuu King (Japan).zip" "_REN64\ChouKuukanNighterProYakyuuKing(J).zip"
move "Chou Kuukan Nighter Pro Yakyuu King 2 (Japan).zip" "_REN64\ChouKuukanNighterProYakyuuKing2(J).zip"
move "Chou Snobo Kids (Japan).zip" "_REN64\Chou Snobo Kids (J).zip"
move "City-Tour GP - Zen-Nihon GT Senshuken (Japan).zip" "_REN64\City-TourGP-Zen-NihonGTSenshuken(J).zip"
move "Clay Fighter - Sculptor's Cut (USA).zip" "_REN64\Clay Fighter - Sculptor's Cut (U).zip"
move "Clay Fighter 63 1-3 (Europe).zip" "_REN64\Clay Fighter 63 1-3 (E).zip"
move "Clay Fighter 63 1-3 (USA) (Beta) (1997-08-21).zip" "_REN64\ClayFighter631-3(U)(Beta)(1997-08-21).zip"
move "Clay Fighter 63 1-3 (USA).zip" "_REN64\Clay Fighter 63 1-3 (U).zip"
move "Command & Conquer (Europe) (En,Fr).zip" "_REN64\Command & Conquer (E) (EnFr).zip"
move "Command & Conquer (Germany).zip" "_REN64\Command & Conquer (G).zip"
move "Command & Conquer (USA).zip" "_REN64\Command & Conquer (U).zip"
move "Conker's Bad Fur Day (Europe).zip" "_REN64\Conker's Bad Fur Day (E).zip"
move "Conker's Bad Fur Day (USA) (Beta) (2000-10-25).zip" "_REN64\Conker'sBadFurDay(U)(Beta)(2000-10-25).zip"
move "Conker's Bad Fur Day (USA) (Beta) (ECTS 2000) (2000-08-26).zip" "_REN64\ConkersBadFurDay(U)(Beta).zip"
move "Conker's Bad Fur Day (USA).zip" "_REN64\Conker's Bad Fur Day (U).zip"
move "Controller Kensa-ki NUS-yo N Cassette (Japan) (Test Program).zip" "_REN64\ControllerKensakiNUSyoNCassette(J).zip"
move "Cruis'n Exotica (USA).zip" "_REN64\Cruis'n Exotica (U).zip"
move "Cruis'n USA (Europe).zip" "_REN64\Cruis'n USA (E).zip"
move "Cruis'n USA (USA) (Rev 1).zip" "_REN64\Cruis'n USA (U) (Rev 1).zip"
move "Cruis'n USA (USA) (Rev 2).zip" "_REN64\Cruis'n USA (U) (Rev 2).zip"
move "Cruis'n USA (USA).zip" "_REN64\Cruis'n USA (U).zip"
move "Cruis'n World (Europe) (Rev 1).zip" "_REN64\Cruis'n World (E) (Rev 1).zip"
move "Cruis'n World (Europe).zip" "_REN64\Cruis'n World (E).zip"
move "Cruis'n World (USA).zip" "_REN64\Cruis'n World (U).zip"
move "Custom Robo (Japan).zip" "_REN64\Custom Robo (J).zip"
move "Custom Robo V2 (Japan).zip" "_REN64\Custom Robo V2 (J).zip"
move "CyberTiger (Europe).zip" "_REN64\CyberTiger (E).zip"
move "CyberTiger (USA).zip" "_REN64\CyberTiger (U).zip"
move "Daffy Duck Starring as Duck Dodgers (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN64\DaffyDuckStarringasDuckDodgers(E).zip"
move "Dance Dance Revolution - Disney Dancing Museum (Japan).zip" "_REN64\DanceDanceRevolutionDisneyDancingMu(J).zip"
move "Dark Rift (Europe).zip" "_REN64\Dark Rift (E).zip"
move "Dark Rift (USA).zip" "_REN64\Dark Rift (U).zip"
move "Deadly Arts (USA).zip" "_REN64\Deadly Arts (U).zip"
move "Defi au Tetris Magique (France).zip" "_REN64\Defi au Tetris Magique (F).zip"
move "Densha de Go! 64 (Japan).zip" "_REN64\Densha de Go! 64 (J).zip"
move "Derby Stallion 64 (Japan) (Beta) [b].zip" "_REN64\Derby Stallion 64 (J) (Beta) [b].zip"
move "Derby Stallion 64 (Japan).zip" "_REN64\Derby Stallion 64 (J).zip"
move "Destruction Derby 64 (Europe) (En,Fr,De).zip" "_REN64\Destruction Derby 64 (E) (EnFrDe).zip"
move "Destruction Derby 64 (USA).zip" "_REN64\Destruction Derby 64 (U).zip"
move "Dezaemon 3D (Japan).zip" "_REN64\Dezaemon 3D (J).zip"
move "Diddy Kong Racing (Europe) (En,Fr,De) (Rev 1).zip" "_REN64\Diddy Kong Racing (E) (EnFrDe) (Rev 1).zip"
move "Diddy Kong Racing (Europe) (En,Fr,De).zip" "_REN64\Diddy Kong Racing (E) (EnFrDe).zip"
move "Diddy Kong Racing (Japan).zip" "_REN64\Diddy Kong Racing (J).zip"
move "Diddy Kong Racing (USA) (En,Fr) (Rev 1).zip" "_REN64\Diddy Kong Racing (U) (EnFr) (Rev 1).zip"
move "Diddy Kong Racing (USA) (En,Fr).zip" "_REN64\Diddy Kong Racing (U) (EnFr).zip"
move "Die Hard 64 (USA) (Proto) (Level 1).zip" "_REN64\Die Hard 64 (U) (Proto) (Level 1).zip"
move "Die Hard 64 (USA) (Proto) (Level 2).zip" "_REN64\Die Hard 64 (U) (Proto) (Level 2).zip"
move "Die Hard 64 (USA) (Proto) (Level 3).zip" "_REN64\Die Hard 64 (U) (Proto) (Level 3).zip"
move "Dinosaur Planet (USA) (Proto) (2000-12-01).zip" "_REN64\DinosaurPlanet(U)(Proto)(2000-12-01).zip"
move "Donald Duck - Goin' Quackers (USA) (En,Fr,De,Es,It) [b].zip" "_REN64\DonaldDuckGoinQuackers(U)(EnFrDeEsIt)b.zip"
move "Donald Duck - Quack Attack (Europe) (En,Fr,De,Es,It) [b].zip" "_REN64\DonaldDuckQuackAttack(E)(EnFrDeEsIt)b.zip"
move "Donkey Kong 64 (Europe) (En,Fr,De,Es).zip" "_REN64\Donkey Kong 64 (E) (EnFrDeEs).zip"
move "Donkey Kong 64 (Japan).zip" "_REN64\Donkey Kong 64 (J).zip"
move "Donkey Kong 64 (USA) (Demo) (Kiosk).zip" "_REN64\Donkey Kong 64 (U) (Demo) (Kiosk).zip"
move "Donkey Kong 64 (USA).zip" "_REN64\Donkey Kong 64 (U).zip"
move "Doom 64 (Europe).zip" "_REN64\Doom 64 (E).zip"
move "Doom 64 (Japan).zip" "_REN64\Doom 64 (J).zip"
move "Doom 64 (USA) (Rev 1).zip" "_REN64\Doom 64 (U) (Rev 1).zip"
move "Doom 64 (USA).zip" "_REN64\Doom 64 (U).zip"
move "Doraemon - Nobita to 3tsu no Seireiseki (Japan).zip" "_REN64\Doraemon-Nobitato3tsunoSeireiseki(J).zip"
move "Doraemon 2 - Nobita to Hikari no Shinden (Japan).zip" "_REN64\Doraemon2-NobitatoHikarinoShinden(J).zip"
move "Doraemon 3 - Nobita no Machi SOS! (Japan).zip" "_REN64\Doraemon 3 - Nobita no Machi SOS! (J).zip"
move "Doubutsu Banchou (Japan) (Proto).zip" "_REN64\Doubutsu Banchou (J) (Proto).zip"
move "Doubutsu no Mori (Japan).zip" "_REN64\Doubutsu no Mori (J).zip"
move "Dr. Mario 64 (USA).zip" "_REN64\Dr. Mario 64 (U).zip"
move "Dragon Sword 64 (Europe) (Proto).zip" "_REN64\Dragon Sword 64 (E) (Proto).zip"
move "Dragon Sword 64 (USA) (Proto) (1999-08-25).zip" "_REN64\DragonSword64(U)(Proto)(1999-08-25).zip"
move "Dual Heroes (Europe).zip" "_REN64\Dual Heroes (E).zip"
move "Dual Heroes (Japan).zip" "_REN64\Dual Heroes (J).zip"
move "Dual Heroes (USA).zip" "_REN64\Dual Heroes (U).zip"
move "Duck Dodgers Starring Daffy Duck (USA) (En,Fr,Es) (Beta) (2000-03-07).zip" "_REN64\DuckDodgersStarringDaffyDuck(U)(Beta).zip"
move "Duck Dodgers Starring Daffy Duck (USA) (En,Fr,Es).zip" "_REN64\DuckDodgersStarringDaffyDuck(U).zip"
move "Duke Nukem - Zero Hour (Europe).zip" "_REN64\Duke Nukem - Zero Hour (E).zip"
move "Duke Nukem - Zero Hour (France).zip" "_REN64\Duke Nukem - Zero Hour (F).zip"
move "Duke Nukem - Zero Hour (USA).zip" "_REN64\Duke Nukem - Zero Hour (U).zip"
move "Duke Nukem 64 (Europe) (Beta).zip" "_REN64\Duke Nukem 64 (E) (Beta).zip"
move "Duke Nukem 64 (Europe).zip" "_REN64\Duke Nukem 64 (E).zip"
move "Duke Nukem 64 (France).zip" "_REN64\Duke Nukem 64 (F).zip"
move "Duke Nukem 64 (USA).zip" "_REN64\Duke Nukem 64 (U).zip"
move "Earthworm Jim 3D (Europe) (En,Fr,De,Es,It).zip" "_REN64\Earthworm Jim 3D (E) (EnFrDeEsIt).zip"
move "Earthworm Jim 3D (USA).zip" "_REN64\Earthworm Jim 3D (U).zip"
move "ECW Hardcore Revolution (Europe).zip" "_REN64\ECW Hardcore Revolution (E).zip"
move "ECW Hardcore Revolution (Germany).zip" "_REN64\ECW Hardcore Revolution (G).zip"
move "ECW Hardcore Revolution (USA) (Beta).zip" "_REN64\ECW Hardcore Revolution (U) (Beta).zip"
move "ECW Hardcore Revolution (USA).zip" "_REN64\ECW Hardcore Revolution (U).zip"
move "Eikou no Saint Andrews (Japan).zip" "_REN64\Eikou no Saint Andrews (J).zip"
move "Eltale Monsters (Japan).zip" "_REN64\Eltale Monsters (J).zip"
move "Excitebike 64 (Europe).zip" "_REN64\Excitebike 64 (E).zip"
move "Excitebike 64 (Japan).zip" "_REN64\Excitebike 64 (J).zip"
move "Excitebike 64 (USA) (Demo) (Kiosk).zip" "_REN64\Excitebike 64 (U) (Demo) (Kiosk).zip"
move "Excitebike 64 (USA) (Rev 1).zip" "_REN64\Excitebike 64 (U) (Rev 1).zip"
move "Excitebike 64 (USA).zip" "_REN64\Excitebike 64 (U).zip"
move "Extreme-G (Europe) (En,Fr,De,Es,It).zip" "_REN64\Extreme-G (E) (EnFrDeEsIt).zip"
move "Extreme-G (Japan).zip" "_REN64\Extreme-G (J).zip"
move "Extreme-G (USA).zip" "_REN64\Extreme-G (U).zip"
move "Extreme-G XG2 (Europe) (En,Fr,De,Es,It).zip" "_REN64\Extreme-G XG2 (E) (EnFrDeEsIt).zip"
move "Extreme-G XG2 (Japan).zip" "_REN64\Extreme-G XG2 (J).zip"
move "Extreme-G XG2 (USA).zip" "_REN64\Extreme-G XG2 (U).zip"
move "F-1 World Grand Prix (Europe).zip" "_REN64\F-1 World Grand Prix (E).zip"
move "F-1 World Grand Prix (France).zip" "_REN64\F-1 World Grand Prix (F).zip"
move "F-1 World Grand Prix (Germany).zip" "_REN64\F-1 World Grand Prix (G).zip"
move "F-1 World Grand Prix (Japan).zip" "_REN64\F-1 World Grand Prix (J).zip"
move "F-1 World Grand Prix (USA).zip" "_REN64\F-1 World Grand Prix (U).zip"
move "F-1 World Grand Prix II (Europe) (En,Fr,De,Es).zip" "_REN64\F-1 World Grand Prix II (E) (EnFrDeEs).zip"
move "F-Zero X (Europe).zip" "_REN64\F-Zero X (E).zip"
move "F-Zero X (Japan).zip" "_REN64\F-Zero X (J).zip"
move "F-Zero X (USA).zip" "_REN64\F-Zero X (U).zip"
move "F1 Pole Position 64 (Europe) (En,Fr,De).zip" "_REN64\F1 Pole Position 64 (E) (EnFrDe).zip"
move "F1 Pole Position 64 (USA) (En,Fr,De).zip" "_REN64\F1 Pole Position 64 (U) (EnFrDe).zip"
move "F1 Racing Championship (Brazil) (En,Fr).zip" "_REN64\F1 Racing Championship (B) (EnFr).zip"
move "F1 Racing Championship (Europe) (En,Fr,De,Es,It).zip" "_REN64\F1RacingChampionship(E)(EnFrDeEsIt).zip"
move "F1 Racing Championship (USA) (Beta).zip" "_REN64\F1 Racing Championship (U) (Beta).zip"
move "Famista 64 (Japan).zip" "_REN64\Famista 64 (J).zip"
move "FIFA - Road to World Cup 98 (Europe) (En,Fr,De,Es,It,Nl,Sv).zip" "_REN64\FIFARoadtoWorldCup98(E).zip"
move "FIFA - Road to World Cup 98 (USA) (En,Fr,De,Es,It,Nl,Sv).zip" "_REN64\FIFARoadtoWorldCup98(U).zip"
move "FIFA - Road to World Cup 98 - World Cup e no Michi (Japan).zip" "_REN64\FIFARoadtoWorldCup98WorldCupenoMich(J).zip"
move "FIFA 64 (Europe) (En,Fr,De).zip" "_REN64\FIFA 64 (E) (EnFrDe).zip"
move "FIFA 99 (Europe) (En,Fr,De,Es,It,Nl,Pt,Sv).zip" "_REN64\FIFA 99 (E) (EnFrDeEsItNlPtSv).zip"
move "FIFA 99 (USA) (En,Fr,De,Es,It,Nl,Pt,Sv).zip" "_REN64\FIFA 99 (U) (EnFrDeEsItNlPtSv).zip"
move "Fighter Destiny 2 (USA).zip" "_REN64\Fighter Destiny 2 (U).zip"
move "Fighters Destiny (Europe).zip" "_REN64\Fighters Destiny (E).zip"
move "Fighters Destiny (France).zip" "_REN64\Fighters Destiny (F).zip"
move "Fighters Destiny (Germany).zip" "_REN64\Fighters Destiny (G).zip"
move "Fighters Destiny (USA).zip" "_REN64\Fighters Destiny (U).zip"
move "Fighting Cup (Japan).zip" "_REN64\Fighting Cup (J).zip"
move "Fighting Force 64 (Europe).zip" "_REN64\Fighting Force 64 (E).zip"
move "Fighting Force 64 (USA).zip" "_REN64\Fighting Force 64 (U).zip"
move "Flying Dragon (Europe).zip" "_REN64\Flying Dragon (E).zip"
move "Flying Dragon (USA).zip" "_REN64\Flying Dragon (U).zip"
move "Forsaken (Europe) (En,Fr,Es,It).zip" "_REN64\Forsaken (E) (EnFrEsIt).zip"
move "Forsaken (Germany).zip" "_REN64\Forsaken (G).zip"
move "Forsaken 64 (USA).zip" "_REN64\Forsaken 64 (U).zip"
move "Fox Sports College Hoops '99 (USA).zip" "_REN64\Fox Sports College Hoops '99 (U).zip"
move "Freak Boy (Unknown) (Proto).zip" "_REN64\Freak Boy (Unknown) (Proto).zip"
move "Frogger 2 (USA) (Proto 1).zip" "_REN64\Frogger 2 (U) (Proto 1).zip"
move "Frogger 2 (USA) (Proto 2).zip" "_REN64\Frogger 2 (U) (Proto 2).zip"
move "Fushigi no Dungeon - Fuurai no Shiren 2 - Oni Shuurai! Shiren Jou! (Japan).zip" "_REN64\FushiginoDungeonFuurainoShiren2OniS(J).zip"
move "G.A.S.P!! Fighters' NEXTream (Europe).zip" "_REN64\G.A.S.P!! Fighters' NEXTream (E).zip"
move "G.A.S.P!! Fighters' NEXTream (Japan).zip" "_REN64\G.A.S.P!! Fighters' NEXTream (J).zip"
move "GameBooster 64 (Europe) (v1.1) (Unl).zip" "_REN64\GameBooster 64 (E) (v1.1) (Unl).zip"
move "GameShark Pro (USA) (v2.0) (Unl).zip" "_REN64\GameShark Pro (U) (v2.0) (Unl).zip"
move "GameShark Pro (USA) (v3.3) (Unl).zip" "_REN64\GameShark Pro (U) (v3.3) (Unl).zip"
move "Ganbare Goemon - Dero Dero Douchuu Obake Tenkomori (Japan).zip" "_REN64\GanbareGoemonDeroDeroDouchuuObakeTe(J).zip"
move "Ganbare Goemon - Neo Momoyama Bakufu no Odori (Japan).zip" "_REN64\GanbareGoemonNeoMomoyamaBakufunoOdo(J).zip"
move "Ganbare! Nippon! Olympics 2000 (Japan).zip" "_REN64\Ganbare! Nippon! Olympics 2000 (J).zip"
move "Gauntlet Legends (Europe).zip" "_REN64\Gauntlet Legends (E).zip"
move "Gauntlet Legends (Japan).zip" "_REN64\Gauntlet Legends (J).zip"
move "Gauntlet Legends (USA).zip" "_REN64\Gauntlet Legends (U).zip"
move "Getter Love!! - Cho Renai Party Game Tanjou (Japan).zip" "_REN64\GetterLove!!ChoRenaiPartyGameTanjou(J).zip"
move "Gex 3 - Deep Cover Gecko (Europe) (En,Es,It).zip" "_REN64\Gex 3 - Deep Cover Gecko (E) (EnEsIt).zip"
move "Gex 3 - Deep Cover Gecko (Europe) (Fr,De).zip" "_REN64\Gex 3 - Deep Cover Gecko (E) (FrDe).zip"
move "Gex 3 - Deep Cover Gecko (USA).zip" "_REN64\Gex 3 - Deep Cover Gecko (U).zip"
move "Gex 64 - Enter the Gecko (Europe).zip" "_REN64\Gex 64 - Enter the Gecko (E).zip"
move "Gex 64 - Enter the Gecko (USA).zip" "_REN64\Gex 64 - Enter the Gecko (U).zip"
move "Glover (Europe) (En,Fr,De).zip" "_REN64\Glover (E) (EnFrDe).zip"
move "Glover (USA) (Beta) (1998-07-16) [b].zip" "_REN64\Glover (U) (Beta) (1998-07-16) [b].zip"
move "Glover (USA) (Proto) (1998-09-04).zip" "_REN64\Glover (U) (Proto) (1998-09-04).zip"
move "Glover (USA).zip" "_REN64\Glover (U).zip"
move "Glover 2 (USA) (Proto 1).zip" "_REN64\Glover 2 (U) (Proto 1).zip"
move "Glover 2 (USA) (Proto 2).zip" "_REN64\Glover 2 (U) (Proto 2).zip"
move "Goemon - Mononoke Sugoroku (Japan).zip" "_REN64\Goemon - Mononoke Sugoroku (J).zip"
move "Goemon's Great Adventure (USA).zip" "_REN64\Goemon's Great Adventure (U).zip"
move "Golden Nugget 64 (USA).zip" "_REN64\Golden Nugget 64 (U).zip"
move "GoldenEye 007 (Europe).zip" "_REN64\GoldenEye 007 (E).zip"
move "GoldenEye 007 (Japan).zip" "_REN64\GoldenEye 007 (J).zip"
move "GoldenEye 007 (USA).zip" "_REN64\GoldenEye 007 (U).zip"
move "GT 64 - Championship Edition (Europe) (En,Fr,De).zip" "_REN64\GT64-ChampionshipEdition(E)(EnFrDe).zip"
move "GT 64 - Championship Edition (USA) (Beta) (1998-05-25).zip" "_REN64\GT64ChampionshipEdition(U)(Beta).zip"
move "GT 64 - Championship Edition (USA).zip" "_REN64\GT 64 - Championship Edition (U).zip"
move "Hamster Monogatari 64 (Japan).zip" "_REN64\Hamster Monogatari 64 (J).zip"
move "Harukanaru Augusta - Masters '98 (Japan).zip" "_REN64\Harukanaru Augusta - Masters '98 (J).zip"
move "Harvest Moon 64 (USA).zip" "_REN64\Harvest Moon 64 (U).zip"
move "Heiwa Pachinko World 64 (Japan).zip" "_REN64\Heiwa Pachinko World 64 (J).zip"
move "Hercules - The Legendary Journeys (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN64\HerculesTheLegendaryJourneys(E).zip"
move "Hercules - The Legendary Journeys (Unknown) (Beta).zip" "_REN64\HerculesTheLegendaryJou(Unknown)(Beta).zip"
move "Hercules - The Legendary Journeys (USA).zip" "_REN64\Hercules - The Legendary Journeys (U).zip"
move "Hexen (Europe).zip" "_REN64\Hexen (E).zip"
move "Hexen (France).zip" "_REN64\Hexen (F).zip"
move "Hexen (Germany).zip" "_REN64\Hexen (G).zip"
move "Hexen (Japan).zip" "_REN64\Hexen (J).zip"
move "Hexen (USA).zip" "_REN64\Hexen (U).zip"
move "Hey You, Pikachu! (USA).zip" "_REN64\Hey You Pikachu! (U).zip"
move "Hiryuu no Ken Twin (Japan).zip" "_REN64\Hiryuu no Ken Twin (J).zip"
move "Holy Magic Century (Europe).zip" "_REN64\Holy Magic Century (E).zip"
move "Holy Magic Century (France).zip" "_REN64\Holy Magic Century (F).zip"
move "Holy Magic Century (Germany).zip" "_REN64\Holy Magic Century (G).zip"
move "Hoshi no Kirby 64 (Japan) (Rev 1).zip" "_REN64\Hoshi no Kirby 64 (J) (Rev 1).zip"
move "Hoshi no Kirby 64 (Japan) (Rev 2).zip" "_REN64\Hoshi no Kirby 64 (J) (Rev 2).zip"
move "Hoshi no Kirby 64 (Japan) (Rev 3).zip" "_REN64\Hoshi no Kirby 64 (J) (Rev 3).zip"
move "Hoshi no Kirby 64 (Japan).zip" "_REN64\Hoshi no Kirby 64 (J).zip"
move "Hot Wheels - Turbo Racing (Europe) (En,Fr,De).zip" "_REN64\Hot Wheels - Turbo Racing (E) (EnFrDe).zip"
move "Hot Wheels - Turbo Racing (USA).zip" "_REN64\Hot Wheels - Turbo Racing (U).zip"
move "HSV Adventure Racing! (Australia).zip" "_REN64\HSV Adventure Racing! (A).zip"
move "Human Grand Prix - The New Generation (Japan).zip" "_REN64\HumanGrandPrix-TheNewGeneration(J).zip"
move "Hybrid Heaven (Europe) (En,Fr,De).zip" "_REN64\Hybrid Heaven (E) (EnFrDe).zip"
move "Hybrid Heaven (Japan).zip" "_REN64\Hybrid Heaven (J).zip"
move "Hybrid Heaven (USA).zip" "_REN64\Hybrid Heaven (U).zip"
move "Hydro Thunder (Europe).zip" "_REN64\Hydro Thunder (E).zip"
move "Hydro Thunder (France).zip" "_REN64\Hydro Thunder (F).zip"
move "Hydro Thunder (USA).zip" "_REN64\Hydro Thunder (U).zip"
move "Hyper Olympics in Nagano 64 (Japan).zip" "_REN64\Hyper Olympics in Nagano 64 (J).zip"
move "Ide Yosuke no Mahjong Juku (Japan).zip" "_REN64\Ide Yosuke no Mahjong Juku (J).zip"
move "Iggy's Reckin' Balls (Europe).zip" "_REN64\Iggy's Reckin' Balls (E).zip"
move "Iggy's Reckin' Balls (USA).zip" "_REN64\Iggy's Reckin' Balls (U).zip"
move "Iggy-kun no Bura Bura Poyon (Japan).zip" "_REN64\Iggy-kun no Bura Bura Poyon (J).zip"
move "In-Fisherman - Bass Hunter 64 (Europe).zip" "_REN64\In-Fisherman - Bass Hunter 64 (E).zip"
move "In-Fisherman - Bass Hunter 64 (USA).zip" "_REN64\In-Fisherman - Bass Hunter 64 (U).zip"
move "Indiana Jones and the Infernal Machine (Australia) (Proto).zip" "_REN64\IndianaJonesandtheInfernalMa(A)(Proto).zip"
move "Indiana Jones and the Infernal Machine (USA).zip" "_REN64\IndianaJonesandtheInfernalMachine(U).zip"
move "Indy Racing 2000 (USA).zip" "_REN64\Indy Racing 2000 (U).zip"
move "International Superstar Soccer '98 (Europe) (Beta) (1998-03-02).zip" "_REN64\InternationalSuperstarSoccer9(E)(Beta).zip"
move "International Superstar Soccer '98 (Europe).zip" "_REN64\International Superstar Soccer '98 (E).zip"
move "International Superstar Soccer '98 (USA).zip" "_REN64\International Superstar Soccer '98 (U).zip"
move "International Superstar Soccer 2000 (Europe) (En,De).zip" "_REN64\InternationalSuperstarSoccer2000(E).zip"
move "International Superstar Soccer 2000 (Europe) (Fr,It).zip" "_REN64\InternationalSuperstarSoccer2000(E)_0.zip"
move "International Superstar Soccer 2000 (USA) (En,Es) (Rev 1).zip" "_REN64\InternationalSuperstarSoccer2(U)(Rev1).zip"
move "International Superstar Soccer 2000 (USA) (En,Es).zip" "_REN64\InternationalSuperstarSoccer2000(U).zip"
move "International Superstar Soccer 64 (Europe).zip" "_REN64\International Superstar Soccer 64 (E).zip"
move "International Superstar Soccer 64 (USA).zip" "_REN64\International Superstar Soccer 64 (U).zip"
move "International Track & Field - Summer Games (Europe) (En,Fr,De).zip" "_REN64\InternationalTrack&FieldSummerGames(E).zip"
move "International Track & Field 2000 (USA).zip" "_REN64\International Track & Field 2000 (U).zip"
move "Itoi Shigesato no Bass Tsuri No. 1 Kettei Ban! (Japan).zip" "_REN64\ItoiShigesatonoBassTsuriNo1KetteiBa(J).zip"
move "J.League Dynamite Soccer 64 (Japan).zip" "_REN64\J.League Dynamite Soccer 64 (J).zip"
move "J.League Eleven Beat 1997 (Japan).zip" "_REN64\J.League Eleven Beat 1997 (J).zip"
move "J.League Live 64 (Japan).zip" "_REN64\J.League Live 64 (J).zip"
move "J.League Tactics Soccer (Japan) (Rev 1).zip" "_REN64\J.League Tactics Soccer (J) (Rev 1).zip"
move "J.League Tactics Soccer (Japan).zip" "_REN64\J.League Tactics Soccer (J).zip"
move "Jangou Simulation Mahjong Dou 64 (Japan).zip" "_REN64\Jangou Simulation Mahjong Dou 64 (J).zip"
move "Jeopardy! (USA).zip" "_REN64\Jeopardy! (U).zip"
move "Jeremy McGrath Supercross 2000 (Europe).zip" "_REN64\Jeremy McGrath Supercross 2000 (E).zip"
move "Jeremy McGrath Supercross 2000 (USA).zip" "_REN64\Jeremy McGrath Supercross 2000 (U).zip"
move "Jet Force Gemini (Europe) (En,Fr,De,Es).zip" "_REN64\Jet Force Gemini (E) (EnFrDeEs).zip"
move "Jet Force Gemini (USA) (Demo) (Kiosk).zip" "_REN64\Jet Force Gemini (U) (Demo) (Kiosk).zip"
move "Jet Force Gemini (USA).zip" "_REN64\Jet Force Gemini (U).zip"
move "Jikkyou G1 Stable (Japan) (Rev 1).zip" "_REN64\Jikkyou G1 Stable (J) (Rev 1).zip"
move "Jikkyou G1 Stable (Japan).zip" "_REN64\Jikkyou G1 Stable (J).zip"
move "Jikkyou J.League 1999 - Perfect Striker 2 (Japan) (Rev 1).zip" "_REN64\JikkyouJLeague1999PerfectStri(J)(Rev1).zip"
move "Jikkyou J.League 1999 - Perfect Striker 2 (Japan).zip" "_REN64\JikkyouJ.League1999-PerfectStriker2(J).zip"
move "Jikkyou J.League Perfect Striker (Japan).zip" "_REN64\Jikkyou J.League Perfect Striker (J).zip"
move "Jikkyou Powerful Pro Yakyuu - Basic Ban 2001 (Japan) (Rev 1).zip" "_REN64\JikkyouPowerfulProYakyuuBasic(J)(Rev1).zip"
move "Jikkyou Powerful Pro Yakyuu - Basic Ban 2001 (Japan).zip" "_REN64\JikkyouPowerfulProYakyuuBasicBan200(J).zip"
move "Jikkyou Powerful Pro Yakyuu 2000 (Japan) (Rev 1).zip" "_REN64\JikkyouPowerfulProYakyuu2000(J)(Rev1).zip"
move "Jikkyou Powerful Pro Yakyuu 2000 (Japan).zip" "_REN64\Jikkyou Powerful Pro Yakyuu 2000 (J).zip"
move "Jikkyou Powerful Pro Yakyuu 4 (Japan) (Beta) (1996-11-30).zip" "_REN64\JikkyouPowerfulProYakyuu4(J)(Beta).zip"
move "Jikkyou Powerful Pro Yakyuu 4 (Japan) (Rev 1).zip" "_REN64\JikkyouPowerfulProYakyuu4(J)(Rev1).zip"
move "Jikkyou Powerful Pro Yakyuu 4 (Japan).zip" "_REN64\Jikkyou Powerful Pro Yakyuu 4 (J).zip"
move "Jikkyou Powerful Pro Yakyuu 5 (Japan) (Rev 1).zip" "_REN64\JikkyouPowerfulProYakyuu5(J)(Rev1).zip"
move "Jikkyou Powerful Pro Yakyuu 5 (Japan) (Rev 2).zip" "_REN64\JikkyouPowerfulProYakyuu5(J)(Rev2).zip"
move "Jikkyou Powerful Pro Yakyuu 5 (Japan).zip" "_REN64\Jikkyou Powerful Pro Yakyuu 5 (J).zip"
move "Jikkyou Powerful Pro Yakyuu 6 (Japan) (Rev 1).zip" "_REN64\JikkyouPowerfulProYakyuu6(J)(Rev1).zip"
move "Jikkyou Powerful Pro Yakyuu 6 (Japan) (Rev 2).zip" "_REN64\JikkyouPowerfulProYakyuu6(J)(Rev2).zip"
move "Jikkyou Powerful Pro Yakyuu 6 (Japan).zip" "_REN64\Jikkyou Powerful Pro Yakyuu 6 (J).zip"
move "Jikkyou World Soccer - World Cup France '98 (Japan) (Rev 1).zip" "_REN64\JikkyouWorldSoccerWorldCupFra(J)(Rev1).zip"
move "Jikkyou World Soccer - World Cup France '98 (Japan) (Rev 2).zip" "_REN64\JikkyouWorldSoccerWorldCupFra(J)(Rev2).zip"
move "Jikkyou World Soccer - World Cup France '98 (Japan).zip" "_REN64\JikkyouWorldSoccerWorldCupFrance'98(J).zip"
move "Jikkyou World Soccer 3 (Japan).zip" "_REN64\Jikkyou World Soccer 3 (J).zip"
move "Jikuu Senshi Turok (Japan).zip" "_REN64\Jikuu Senshi Turok (J).zip"
move "Jinsei Game 64 (Japan).zip" "_REN64\Jinsei Game 64 (J).zip"
move "John Romero's Daikatana (Europe) (En,Fr,De).zip" "_REN64\John Romero's Daikatana (E) (EnFrDe).zip"
move "John Romero's Daikatana (Japan).zip" "_REN64\John Romero's Daikatana (J).zip"
move "John Romero's Daikatana (USA).zip" "_REN64\John Romero's Daikatana (U).zip"
move "Kakutou Denshou - F-Cup Maniax (Japan).zip" "_REN64\Kakutou Denshou - F-Cup Maniax (J).zip"
move "Ken Griffey Jr.'s Slugfest (USA).zip" "_REN64\Ken Griffey Jr.'s Slugfest (U).zip"
move "Killer Instinct Gold (Europe).zip" "_REN64\Killer Instinct Gold (E).zip"
move "Killer Instinct Gold (USA) (Rev 1).zip" "_REN64\Killer Instinct Gold (U) (Rev 1).zip"
move "Killer Instinct Gold (USA) (Rev 2).zip" "_REN64\Killer Instinct Gold (U) (Rev 2).zip"
move "Killer Instinct Gold (USA).zip" "_REN64\Killer Instinct Gold (U).zip"
move "King Hill 64 - Extreme Snowboarding (Japan).zip" "_REN64\KingHill64-ExtremeSnowboarding(J).zip"
move "Kiratto Kaiketsu! 64 Tanteidan (Japan).zip" "_REN64\Kiratto Kaiketsu! 64 Tanteidan (J).zip"
move "Kirby 64 - The Crystal Shards (Europe).zip" "_REN64\Kirby 64 - The Crystal Shards (E).zip"
move "Kirby 64 - The Crystal Shards (USA).zip" "_REN64\Kirby 64 - The Crystal Shards (U).zip"
move "Knife Edge - Nose Gunner (Europe).zip" "_REN64\Knife Edge - Nose Gunner (E).zip"
move "Knife Edge - Nose Gunner (Japan).zip" "_REN64\Knife Edge - Nose Gunner (J).zip"
move "Knife Edge - Nose Gunner (USA).zip" "_REN64\Knife Edge - Nose Gunner (U).zip"
move "Knockout Kings 2000 (Europe).zip" "_REN64\Knockout Kings 2000 (E).zip"
move "Knockout Kings 2000 (USA).zip" "_REN64\Knockout Kings 2000 (U).zip"
move "Kobe Bryant in NBA Courtside (Europe).zip" "_REN64\Kobe Bryant in NBA Courtside (E).zip"
move "Kobe Bryant in NBA Courtside (USA).zip" "_REN64\Kobe Bryant in NBA Courtside (U).zip"
move "Last Legion UX (Japan).zip" "_REN64\Last Legion UX (J).zip"
move "Legend of Zelda, The - Majora's Mask (Europe) (En,Fr,De,Es) (Rev 1) (Debug).zip" "_REN64\LegendofZeldaMajorasMask(E)(Rev1).zip"
move "Legend of Zelda, The - Majora's Mask (Europe) (En,Fr,De,Es) (Rev 1).zip" "_REN64\LegendofZeldaMajorasMask(E)(Rev1)_0.zip"
move "Legend of Zelda, The - Majora's Mask (Europe) (En,Fr,De,Es).zip" "_REN64\LegendofZeldaMajora'sMask(E)(EnFrDeEs).zip"
move "Legend of Zelda, The - Majora's Mask (Europe) (GameCube).zip" "_REN64\LegendofZeldaMajora'sMask(E)(GameCube).zip"
move "Legend of Zelda, The - Majora's Mask (USA) (Demo) (Kiosk).zip" "_REN64\LegendofZeldaMajorasMask(U)(Demo).zip"
move "Legend of Zelda, The - Majora's Mask (USA) (GameCube).zip" "_REN64\LegendofZeldaMajora'sMask(U)(GameCube).zip"
move "Legend of Zelda, The - Majora's Mask (USA).zip" "_REN64\Legend of Zelda - Majora's Mask (U).zip"
move "Legend of Zelda, The - Ocarina of Time (Europe) (Beta) (2003-02-13) (GameCube).zip" "_REN64\LegendofZeldaOcarinaofTime(E)(Beta).zip"
move "Legend of Zelda, The - Ocarina of Time (Europe) (Debug) (GameCube).zip" "_REN64\LegendofZeldaOcarinaofTime(E)(GC).zip"
move "Legend of Zelda, The - Ocarina of Time (Europe) (En,Fr,De) (Rev 1).zip" "_REN64\LegendofZeldaOcarinaofTime(E)(Rev1).zip"
move "Legend of Zelda, The - Ocarina of Time (Europe) (En,Fr,De).zip" "_REN64\LegendofZelda-OcarinaofTime(E)(EnFrDe).zip"
move "Legend of Zelda, The - Ocarina of Time (Europe) (GameCube).zip" "_REN64\LegendofZeldaOcarinaofTime(E)(GC)_0.zip"
move "Legend of Zelda, The - Ocarina of Time (USA) (Beta).zip" "_REN64\LegendofZelda-OcarinaofTime(U)(Beta).zip"
move "Legend of Zelda, The - Ocarina of Time (USA) (GameCube).zip" "_REN64\LegendofZeldaOcarinaofTime(U)(GC).zip"
move "Legend of Zelda, The - Ocarina of Time (USA) (Rev 1).zip" "_REN64\LegendofZelda-OcarinaofTime(U)(Rev1).zip"
move "Legend of Zelda, The - Ocarina of Time (USA) (Rev 2).zip" "_REN64\LegendofZelda-OcarinaofTime(U)(Rev2).zip"
move "Legend of Zelda, The - Ocarina of Time (USA).zip" "_REN64\Legend of Zelda - Ocarina of Time (U).zip"
move "Legend of Zelda, The - Ocarina of Time - Master Quest (Europe) (Debug) (GameCube).zip" "_REN64\LegendofZeldaOcarinaofTimeMaste(E)(GC).zip"
move "Legend of Zelda, The - Ocarina of Time - Master Quest (Europe) (GameCube).zip" "_REN64\LegendofZeldaOcarinaofTimeMaste(E)(G_0.zip"
move "Legend of Zelda, The - Ocarina of Time - Master Quest (USA) (GameCube).zip" "_REN64\LegendofZeldaOcarinaofTimeMaste(U)(GC).zip"
move "LEGO Racers (Europe) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).zip" "_REN64\LEGO Racers (E) (EnFrDeEsItNlSvNoDaFi).zip"
move "LEGO Racers (USA) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi).zip" "_REN64\LEGO Racers (U) (EnFrDeEsItNlSvNoDaFi).zip"
move "Let's Smash (Japan).zip" "_REN64\Let's Smash (J).zip"
move "Lode Runner 3-D (Europe) (En,Fr,De,Es,It).zip" "_REN64\Lode Runner 3-D (E) (EnFrDeEsIt).zip"
move "Lode Runner 3-D (Japan).zip" "_REN64\Lode Runner 3-D (J).zip"
move "Lode Runner 3-D (USA).zip" "_REN64\Lode Runner 3-D (U).zip"
move "Lylat Wars (Australia) (En,Fr,De).zip" "_REN64\Lylat Wars (A) (EnFrDe).zip"
move "Lylatwars (Europe) (En,Fr,De).zip" "_REN64\Lylatwars (E) (EnFrDe).zip"
move "Mace - The Dark Age (Europe).zip" "_REN64\Mace - The Dark Age (E).zip"
move "Mace - The Dark Age (USA) (Beta).zip" "_REN64\Mace - The Dark Age (U) (Beta).zip"
move "Mace - The Dark Age (USA).zip" "_REN64\Mace - The Dark Age (U).zip"
move "Madden Football 64 (Europe).zip" "_REN64\Madden Football 64 (E).zip"
move "Madden Football 64 (USA).zip" "_REN64\Madden Football 64 (U).zip"
move "Madden NFL 2000 (USA).zip" "_REN64\Madden NFL 2000 (U).zip"
move "Madden NFL 2001 (USA).zip" "_REN64\Madden NFL 2001 (U).zip"
move "Madden NFL 2002 (USA).zip" "_REN64\Madden NFL 2002 (U).zip"
move "Madden NFL 99 (Europe).zip" "_REN64\Madden NFL 99 (E).zip"
move "Madden NFL 99 (USA) (Beta) (1998-08-05).zip" "_REN64\Madden NFL 99 (U) (Beta) (1998-08-05).zip"
move "Madden NFL 99 (USA) (Rev 1).zip" "_REN64\Madden NFL 99 (U) (Rev 1).zip"
move "Madden NFL 99 (USA).zip" "_REN64\Madden NFL 99 (U).zip"
move "Magical Tetris Challenge (Europe).zip" "_REN64\Magical Tetris Challenge (E).zip"
move "Magical Tetris Challenge (Germany).zip" "_REN64\Magical Tetris Challenge (G).zip"
move "Magical Tetris Challenge (USA).zip" "_REN64\Magical Tetris Challenge (U).zip"
move "Magical Tetris Challenge featuring Mickey (Japan).zip" "_REN64\MagicalTetrisChallengefeaturingMick(J).zip"
move "Mahjong 64 (Japan).zip" "_REN64\Mahjong 64 (J).zip"
move "Mahjong Hourouki Classic (Japan).zip" "_REN64\Mahjong Hourouki Classic (J).zip"
move "Mahjong Master (Japan).zip" "_REN64\Mahjong Master (J).zip"
move "Major League Baseball Featuring Ken Griffey Jr. (Australia).zip" "_REN64\MajorLeagueBaseballFeaturingKenGrif(A).zip"
move "Major League Baseball Featuring Ken Griffey Jr. (USA).zip" "_REN64\MajorLeagueBaseballFeaturingKenGrif(U).zip"
move "Mario Golf (Europe).zip" "_REN64\Mario Golf (E).zip"
move "Mario Golf (USA).zip" "_REN64\Mario Golf (U).zip"
move "Mario Golf 64 (Japan) (Rev 1).zip" "_REN64\Mario Golf 64 (J) (Rev 1).zip"
move "Mario Golf 64 (Japan).zip" "_REN64\Mario Golf 64 (J).zip"
move "Mario Kart 64 (Europe) (Rev 1).zip" "_REN64\Mario Kart 64 (E) (Rev 1).zip"
move "Mario Kart 64 (Europe).zip" "_REN64\Mario Kart 64 (E).zip"
move "Mario Kart 64 (Japan) (Rev 1).zip" "_REN64\Mario Kart 64 (J) (Rev 1).zip"
move "Mario Kart 64 (Japan).zip" "_REN64\Mario Kart 64 (J).zip"
move "Mario Kart 64 (USA).zip" "_REN64\Mario Kart 64 (U).zip"
move "Mario no Photopie (Japan).zip" "_REN64\Mario no Photopie (J).zip"
move "Mario Party (Europe) (En,Fr,De).zip" "_REN64\Mario Party (E) (EnFrDe).zip"
move "Mario Party (Japan).zip" "_REN64\Mario Party (J).zip"
move "Mario Party (USA).zip" "_REN64\Mario Party (U).zip"
move "Mario Party 2 (Europe) (En,Fr,De,Es,It).zip" "_REN64\Mario Party 2 (E) (EnFrDeEsIt).zip"
move "Mario Party 2 (Japan).zip" "_REN64\Mario Party 2 (J).zip"
move "Mario Party 2 (USA).zip" "_REN64\Mario Party 2 (U).zip"
move "Mario Party 3 (Europe) (En,Fr,De,Es).zip" "_REN64\Mario Party 3 (E) (EnFrDeEs).zip"
move "Mario Party 3 (Japan).zip" "_REN64\Mario Party 3 (J).zip"
move "Mario Party 3 (USA) (Beta).zip" "_REN64\Mario Party 3 (U) (Beta).zip"
move "Mario Party 3 (USA).zip" "_REN64\Mario Party 3 (U).zip"
move "Mario Story (Japan).zip" "_REN64\Mario Story (J).zip"
move "Mario Tennis (Europe).zip" "_REN64\Mario Tennis (E).zip"
move "Mario Tennis (USA).zip" "_REN64\Mario Tennis (U).zip"
move "Mario Tennis 64 (Japan).zip" "_REN64\Mario Tennis 64 (J).zip"
move "Mega Man 64 (USA) (Beta).zip" "_REN64\Mega Man 64 (U) (Beta).zip"
move "Mega Man 64 (USA).zip" "_REN64\Mega Man 64 (U).zip"
move "Mia Hamm Soccer 64 (USA) (En,Es).zip" "_REN64\Mia Hamm Soccer 64 (U) (EnEs).zip"
move "Michael Owen's WLS 2000 (Europe).zip" "_REN64\Michael Owen's WLS 2000 (E).zip"
move "Mickey no Racing Challenge USA (Japan).zip" "_REN64\Mickey no Racing Challenge USA (J).zip"
move "Mickey's Speedway USA (Europe) (En,Fr,De,Es,It).zip" "_REN64\Mickey's Speedway USA (E) (EnFrDeEsIt).zip"
move "Mickey's Speedway USA (USA).zip" "_REN64\Mickey's Speedway USA (U).zip"
move "Micro Machines 64 Turbo (Europe) (En,Fr,De,Es,It).zip" "_REN64\MicroMachines64Turbo(E)(EnFrDeEsIt).zip"
move "Micro Machines 64 Turbo (USA).zip" "_REN64\Micro Machines 64 Turbo (U).zip"
move "Midway's Greatest Arcade Hits - Volume 1 (USA).zip" "_REN64\Midway'sGreatestArcadeHits-Volume1(U).zip"
move "Mike Piazza's Strike Zone (USA).zip" "_REN64\Mike Piazza's Strike Zone (U).zip"
move "Milo's Astro Lanes (Europe).zip" "_REN64\Milo's Astro Lanes (E).zip"
move "Milo's Astro Lanes (USA).zip" "_REN64\Milo's Astro Lanes (U).zip"
move "Mini Racers (USA) (Ja) (Proto).zip" "_REN64\Mini Racers (U) (Ja) (Proto).zip"
move "Mischief Makers (Europe).zip" "_REN64\Mischief Makers (E).zip"
move "Mischief Makers (USA) (Rev 1).zip" "_REN64\Mischief Makers (U) (Rev 1).zip"
move "Mischief Makers (USA).zip" "_REN64\Mischief Makers (U).zip"
move "Mission - Impossible (Europe).zip" "_REN64\Mission - Impossible (E).zip"
move "Mission - Impossible (France).zip" "_REN64\Mission - Impossible (F).zip"
move "Mission - Impossible (Germany).zip" "_REN64\Mission - Impossible (G).zip"
move "Mission - Impossible (Italy).zip" "_REN64\Mission - Impossible (I).zip"
move "Mission - Impossible (Spain) (Rev 1).zip" "_REN64\Mission - Impossible (S) (Rev 1).zip"
move "Mission - Impossible (Spain).zip" "_REN64\Mission - Impossible (S).zip"
move "Mission - Impossible (USA).zip" "_REN64\Mission - Impossible (U).zip"
move "Monaco Grand Prix (USA).zip" "_REN64\Monaco Grand Prix (U).zip"
move "Monaco Grand Prix - Racing Simulation 2 (Europe) (En,Fr,Es,It).zip" "_REN64\MonacoGrandPrixRacingSimulation2(E).zip"
move "Monopoly (USA).zip" "_REN64\Monopoly (U).zip"
move "Monster Truck Madness 64 (Europe) (En,Fr,De,Es,It).zip" "_REN64\MonsterTruckMadness64(E)(EnFrDeEsIt).zip"
move "Monster Truck Madness 64 (USA).zip" "_REN64\Monster Truck Madness 64 (U).zip"
move "Morita Shougi 64 (Japan).zip" "_REN64\Morita Shougi 64 (J).zip"
move "Mortal Kombat 4 (Europe).zip" "_REN64\Mortal Kombat 4 (E).zip"
move "Mortal Kombat 4 (USA).zip" "_REN64\Mortal Kombat 4 (U).zip"
move "Mortal Kombat Mythologies - Sub-Zero (Europe).zip" "_REN64\MortalKombatMythologies-Sub-Zero(E).zip"
move "Mortal Kombat Mythologies - Sub-Zero (USA).zip" "_REN64\MortalKombatMythologies-Sub-Zero(U).zip"
move "Mortal Kombat Trilogy (Europe).zip" "_REN64\Mortal Kombat Trilogy (E).zip"
move "Mortal Kombat Trilogy (USA) (Rev 1).zip" "_REN64\Mortal Kombat Trilogy (U) (Rev 1).zip"
move "Mortal Kombat Trilogy (USA) (Rev 2).zip" "_REN64\Mortal Kombat Trilogy (U) (Rev 2).zip"
move "Mortal Kombat Trilogy (USA).zip" "_REN64\Mortal Kombat Trilogy (U).zip"
move "MRC - Multi-Racing Championship (Europe) (En,Fr,De).zip" "_REN64\MRCMultiRacingChampionship(E)(EnFrDe).zip"
move "MRC - Multi-Racing Championship (Japan).zip" "_REN64\MRC - Multi-Racing Championship (J).zip"
move "MRC - Multi-Racing Championship (USA).zip" "_REN64\MRC - Multi-Racing Championship (U).zip"
move "Ms. Pac-Man - Maze Madness (USA).zip" "_REN64\Ms. Pac-Man - Maze Madness (U).zip"
move "Mystical Ninja 2 Starring Goemon (Europe) (En,Fr,De).zip" "_REN64\MysticalNinja2StarringGoemon(E).zip"
move "Mystical Ninja Starring Goemon (Europe).zip" "_REN64\Mystical Ninja Starring Goemon (E).zip"
move "Mystical Ninja Starring Goemon (USA).zip" "_REN64\Mystical Ninja Starring Goemon (U).zip"
move "Nagano Winter Olympics '98 (Europe).zip" "_REN64\Nagano Winter Olympics '98 (E).zip"
move "Nagano Winter Olympics '98 (USA).zip" "_REN64\Nagano Winter Olympics '98 (U).zip"
move "Namco Museum 64 (USA).zip" "_REN64\Namco Museum 64 (U).zip"
move "NASCAR 2000 (USA).zip" "_REN64\NASCAR 2000 (U).zip"
move "NASCAR 99 (Europe) (En,Fr,De).zip" "_REN64\NASCAR 99 (E) (EnFrDe).zip"
move "NASCAR 99 (USA).zip" "_REN64\NASCAR 99 (U).zip"
move "NBA Courtside 2 featuring Kobe Bryant (USA).zip" "_REN64\NBACourtside2featuringKobeBryant(U).zip"
move "NBA Hangtime (Europe).zip" "_REN64\NBA Hangtime (E).zip"
move "NBA Hangtime (USA).zip" "_REN64\NBA Hangtime (U).zip"
move "NBA in the Zone '98 (Japan).zip" "_REN64\NBA in the Zone '98 (J).zip"
move "NBA in the Zone '98 (USA).zip" "_REN64\NBA in the Zone '98 (U).zip"
move "NBA in the Zone '99 (USA).zip" "_REN64\NBA in the Zone '99 (U).zip"
move "NBA in the Zone 2 (Japan).zip" "_REN64\NBA in the Zone 2 (J).zip"
move "NBA in the Zone 2000 (Europe).zip" "_REN64\NBA in the Zone 2000 (E).zip"
move "NBA in the Zone 2000 (USA).zip" "_REN64\NBA in the Zone 2000 (U).zip"
move "NBA Jam 2000 (Europe).zip" "_REN64\NBA Jam 2000 (E).zip"
move "NBA Jam 2000 (USA).zip" "_REN64\NBA Jam 2000 (U).zip"
move "NBA Jam 99 (Europe).zip" "_REN64\NBA Jam 99 (E).zip"
move "NBA Jam 99 (USA).zip" "_REN64\NBA Jam 99 (U).zip"
move "NBA Live 2000 (Europe) (En,Fr,De,Es).zip" "_REN64\NBA Live 2000 (E) (EnFrDeEs).zip"
move "NBA Live 2000 (USA) (En,Fr,De,Es).zip" "_REN64\NBA Live 2000 (U) (EnFrDeEs).zip"
move "NBA Live 99 (Europe) (En,Fr,De,Es,It).zip" "_REN64\NBA Live 99 (E) (EnFrDeEsIt).zip"
move "NBA Live 99 (USA) (En,Fr,De,Es,It).zip" "_REN64\NBA Live 99 (U) (EnFrDeEsIt).zip"
move "NBA Pro 98 (Europe).zip" "_REN64\NBA Pro 98 (E).zip"
move "NBA Pro 99 (Europe).zip" "_REN64\NBA Pro 99 (E).zip"
move "NBA Showtime - NBA on NBC (USA).zip" "_REN64\NBA Showtime - NBA on NBC (U).zip"
move "Neon Genesis Evangelion (Japan).zip" "_REN64\Neon Genesis Evangelion (J).zip"
move "New Tetris, The (Europe).zip" "_REN64\New Tetris (E).zip"
move "New Tetris, The (USA).zip" "_REN64\New Tetris (U).zip"
move "NFL Blitz (USA).zip" "_REN64\NFL Blitz (U).zip"
move "NFL Blitz - Special Edition (USA).zip" "_REN64\NFL Blitz - Special Edition (U).zip"
move "NFL Blitz 2000 (USA) (Rev 1).zip" "_REN64\NFL Blitz 2000 (U) (Rev 1).zip"
move "NFL Blitz 2000 (USA).zip" "_REN64\NFL Blitz 2000 (U).zip"
move "NFL Blitz 2001 (USA).zip" "_REN64\NFL Blitz 2001 (U).zip"
move "NFL QB Club 2001 (USA).zip" "_REN64\NFL QB Club 2001 (U).zip"
move "NFL Quarterback Club 2000 (Europe).zip" "_REN64\NFL Quarterback Club 2000 (E).zip"
move "NFL Quarterback Club 2000 (USA).zip" "_REN64\NFL Quarterback Club 2000 (U).zip"
move "NFL Quarterback Club 98 (Europe).zip" "_REN64\NFL Quarterback Club 98 (E).zip"
move "NFL Quarterback Club 98 (USA).zip" "_REN64\NFL Quarterback Club 98 (U).zip"
move "NFL Quarterback Club 99 (Europe).zip" "_REN64\NFL Quarterback Club 99 (E).zip"
move "NFL Quarterback Club 99 (USA).zip" "_REN64\NFL Quarterback Club 99 (U).zip"
move "NHL 99 (Europe) (En,De,Sv,Fi).zip" "_REN64\NHL 99 (E) (EnDeSvFi).zip"
move "NHL 99 (USA).zip" "_REN64\NHL 99 (U).zip"
move "NHL Blades of Steel '99 (USA).zip" "_REN64\NHL Blades of Steel '99 (U).zip"
move "NHL Breakaway 98 (Europe).zip" "_REN64\NHL Breakaway 98 (E).zip"
move "NHL Breakaway 98 (USA).zip" "_REN64\NHL Breakaway 98 (U).zip"
move "NHL Breakaway 99 (Europe).zip" "_REN64\NHL Breakaway 99 (E).zip"
move "NHL Breakaway 99 (USA).zip" "_REN64\NHL Breakaway 99 (U).zip"
move "NHL Pro 99 (Europe).zip" "_REN64\NHL Pro 99 (E).zip"
move "Nightmare Creatures (USA).zip" "_REN64\Nightmare Creatures (U).zip"
move "Nintama Rantarou 64 Game Gallery (Japan).zip" "_REN64\Nintama Rantarou 64 Game Gallery (J).zip"
move "Nintendo All-Star! Dairantou Smash Brothers (Japan).zip" "_REN64\NintendoAllStarDairantouSmashBrothe(J).zip"
move "Nuclear Strike 64 (Europe) (En,Fr).zip" "_REN64\Nuclear Strike 64 (E) (EnFr).zip"
move "Nuclear Strike 64 (Germany) (Beta) (1999-11-17).zip" "_REN64\NuclearStrike64(G)(Beta)(1999-11-17).zip"
move "Nuclear Strike 64 (Germany).zip" "_REN64\Nuclear Strike 64 (G).zip"
move "Nuclear Strike 64 (USA).zip" "_REN64\Nuclear Strike 64 (U).zip"
move "Nushi Zuri 64 (Japan) (Rev 1).zip" "_REN64\Nushi Zuri 64 (J) (Rev 1).zip"
move "Nushi Zuri 64 (Japan).zip" "_REN64\Nushi Zuri 64 (J).zip"
move "Nushi Zuri 64 - Shiokaze ni Notte (Japan).zip" "_REN64\Nushi Zuri 64 - Shiokaze ni Notte (J).zip"
move "O.D.T. (Europe) (En,Fr,De,Es,It) (Proto).zip" "_REN64\O.D.T. (E) (EnFrDeEsIt) (Proto).zip"
move "O.D.T. (USA) (En,Fr,Es) (Proto).zip" "_REN64\O.D.T. (U) (EnFrEs) (Proto).zip"
move "Off Road Challenge (Europe).zip" "_REN64\Off Road Challenge (E).zip"
move "Off Road Challenge (USA).zip" "_REN64\Off Road Challenge (U).zip"
move "Ogre Battle 64 - Person of Lordly Caliber (Japan) (Rev 1).zip" "_REN64\OgreBattle64PersonofLordlyCal(J)(Rev1).zip"
move "Ogre Battle 64 - Person of Lordly Caliber (USA) (Rev 1).zip" "_REN64\OgreBattle64PersonofLordlyCal(U)(Rev1).zip"
move "Ogre Battle 64 - Person of Lordly Caliber (USA).zip" "_REN64\OgreBattle64-PersonofLordlyCaliber(U).zip"
move "Olympic Hockey 98 (Europe) (En,Fr,De,Es).zip" "_REN64\Olympic Hockey 98 (E) (EnFrDeEs).zip"
move "Olympic Hockey 98 (Japan).zip" "_REN64\Olympic Hockey 98 (J).zip"
move "Olympic Hockey 98 (USA).zip" "_REN64\Olympic Hockey 98 (U).zip"
move "Onegai Monsters (Japan).zip" "_REN64\Onegai Monsters (J).zip"
move "Operation WinBack (Europe) (En,Fr,De,Es,It).zip" "_REN64\Operation WinBack (E) (EnFrDeEsIt).zip"
move "Pachinko 365 Nichi (Japan).zip" "_REN64\Pachinko 365 Nichi (J).zip"
move "Paper Mario (Europe) (En,Fr,De,Es).zip" "_REN64\Paper Mario (E) (EnFrDeEs).zip"
move "Paper Mario (USA).zip" "_REN64\Paper Mario (U).zip"
move "Paperboy (Europe).zip" "_REN64\Paperboy (E).zip"
move "Paperboy (USA).zip" "_REN64\Paperboy (U).zip"
move "Parlor! Pro 64 - Pachinko Jikki Simulation Game (Japan) [b].zip" "_REN64\ParlorPro64PachinkoJikkiSimulationG(J).zip"
move "PD Ultraman Battle Collection 64 (Japan).zip" "_REN64\PD Ultraman Battle Collection 64 (J).zip"
move "Penny Racers (Europe).zip" "_REN64\Penny Racers (E).zip"
move "Penny Racers (USA).zip" "_REN64\Penny Racers (U).zip"
move "Perfect Dark (Europe) (Debug Version) (2000-04-26).zip" "_REN64\PerfectDark(E)(DebugVersion)(20000426).zip"
move "Perfect Dark (Europe) (En,Fr,De,Es,It).zip" "_REN64\Perfect Dark (E) (EnFrDeEsIt).zip"
move "Perfect Dark (Japan).zip" "_REN64\Perfect Dark (J).zip"
move "Perfect Dark (USA) (Debug Version) (2000-03-22).zip" "_REN64\PerfectDark(U)(DebugVersion)(20000322).zip"
move "Perfect Dark (USA) (Rev 1).zip" "_REN64\Perfect Dark (U) (Rev 1).zip"
move "Perfect Dark (USA).zip" "_REN64\Perfect Dark (U).zip"
move "PGA European Tour (USA).zip" "_REN64\PGA European Tour (U).zip"
move "PGA European Tour Golf (Europe) (En,Fr,De,Es,It).zip" "_REN64\PGAEuropeanTourGolf(E)(EnFrDeEsIt).zip"
move "Pikachuu Genki de Chuu (Japan).zip" "_REN64\Pikachuu Genki de Chuu (J).zip"
move "Pilotwings 64 (Europe) (En,Fr,De).zip" "_REN64\Pilotwings 64 (E) (EnFrDe).zip"
move "Pilotwings 64 (Japan).zip" "_REN64\Pilotwings 64 (J).zip"
move "Pilotwings 64 (USA).zip" "_REN64\Pilotwings 64 (U).zip"
move "Pokemon Puzzle League (Europe).zip" "_REN64\Pokemon Puzzle League (E).zip"
move "Pokemon Puzzle League (France).zip" "_REN64\Pokemon Puzzle League (F).zip"
move "Pokemon Puzzle League (Germany).zip" "_REN64\Pokemon Puzzle League (G).zip"
move "Pokemon Puzzle League (USA).zip" "_REN64\Pokemon Puzzle League (U).zip"
move "Pokemon Snap (Australia).zip" "_REN64\Pokemon Snap (A).zip"
move "Pokemon Snap (Europe).zip" "_REN64\Pokemon Snap (E).zip"
move "Pokemon Snap (France).zip" "_REN64\Pokemon Snap (F).zip"
move "Pokemon Snap (Germany).zip" "_REN64\Pokemon Snap (G).zip"
move "Pokemon Snap (Italy).zip" "_REN64\Pokemon Snap (I).zip"
move "Pokemon Snap (Japan).zip" "_REN64\Pokemon Snap (J).zip"
move "Pokemon Snap (Spain).zip" "_REN64\Pokemon Snap (S).zip"
move "Pokemon Snap (USA).zip" "_REN64\Pokemon Snap (U).zip"
move "Pokemon Snap Station (USA) (Demo) (Kiosk).zip" "_REN64\PokemonSnapStation(U)(Demo)(Kiosk).zip"
move "Pokemon Stadium (Europe) (Rev 1).zip" "_REN64\Pokemon Stadium (E) (Rev 1).zip"
move "Pokemon Stadium (Europe).zip" "_REN64\Pokemon Stadium (E).zip"
move "Pokemon Stadium (France).zip" "_REN64\Pokemon Stadium (F).zip"
move "Pokemon Stadium (Germany).zip" "_REN64\Pokemon Stadium (G).zip"
move "Pokemon Stadium (Italy).zip" "_REN64\Pokemon Stadium (I).zip"
move "Pokemon Stadium (Japan).zip" "_REN64\Pokemon Stadium (J).zip"
move "Pokemon Stadium (Spain).zip" "_REN64\Pokemon Stadium (S).zip"
move "Pokemon Stadium (USA) (Rev 1).zip" "_REN64\Pokemon Stadium (U) (Rev 1).zip"
move "Pokemon Stadium (USA) (Rev 2).zip" "_REN64\Pokemon Stadium (U) (Rev 2).zip"
move "Pokemon Stadium (USA).zip" "_REN64\Pokemon Stadium (U).zip"
move "Pokemon Stadium 2 (Europe).zip" "_REN64\Pokemon Stadium 2 (E).zip"
move "Pokemon Stadium 2 (France).zip" "_REN64\Pokemon Stadium 2 (F).zip"
move "Pokemon Stadium 2 (Germany).zip" "_REN64\Pokemon Stadium 2 (G).zip"
move "Pokemon Stadium 2 (Italy).zip" "_REN64\Pokemon Stadium 2 (I).zip"
move "Pokemon Stadium 2 (Japan).zip" "_REN64\Pokemon Stadium 2 (J).zip"
move "Pokemon Stadium 2 (Spain).zip" "_REN64\Pokemon Stadium 2 (S).zip"
move "Pokemon Stadium 2 (USA).zip" "_REN64\Pokemon Stadium 2 (U).zip"
move "Pokemon Stadium Kin Gin (Japan).zip" "_REN64\Pokemon Stadium Kin Gin (J).zip"
move "Polaris SnoCross (USA).zip" "_REN64\Polaris SnoCross (U).zip"
move "Power League 64 (Japan).zip" "_REN64\Power League 64 (J).zip"
move "Power Rangers - Lightspeed Rescue (Europe).zip" "_REN64\Power Rangers - Lightspeed Rescue (E).zip"
move "Power Rangers - Lightspeed Rescue (USA).zip" "_REN64\Power Rangers - Lightspeed Rescue (U).zip"
move "Powerpuff Girls, The - Chemical X-Traction (USA).zip" "_REN64\PowerpuffGirls-ChemicalX-Traction(U).zip"
move "Premier Manager 64 (Europe).zip" "_REN64\Premier Manager 64 (E).zip"
move "Pro Mahjong Kiwame 64 (Japan) (Rev 1).zip" "_REN64\Pro Mahjong Kiwame 64 (J) (Rev 1).zip"
move "Pro Mahjong Kiwame 64 (Japan).zip" "_REN64\Pro Mahjong Kiwame 64 (J).zip"
move "Pro Mahjong Tsuwamono 64 - Jansou Battle ni Chousen (Japan).zip" "_REN64\ProMahjongTsuwamono64JansouBattleni(J).zip"
move "Puyo Puyo Sun 64 (Japan).zip" "_REN64\Puyo Puyo Sun 64 (J).zip"
move "Puyo Puyoon Party (Japan).zip" "_REN64\Puyo Puyoon Party (J).zip"
move "Puzzle Bobble 64 (Japan).zip" "_REN64\Puzzle Bobble 64 (J).zip"
move "Quake (Europe).zip" "_REN64\Quake (E).zip"
move "Quake (USA).zip" "_REN64\Quake (U).zip"
move "Quake II (Europe).zip" "_REN64\Quake II (E).zip"
move "Quake II (USA).zip" "_REN64\Quake II (U).zip"
move "Quest 64 (USA).zip" "_REN64\Quest 64 (U).zip"
move "Racing Simulation 2 (Germany).zip" "_REN64\Racing Simulation 2 (G).zip"
move "Rakugakids (Europe).zip" "_REN64\Rakugakids (E).zip"
move "Rakugakids (Japan).zip" "_REN64\Rakugakids (J).zip"
move "Rally '99 (Japan) [b].zip" "_REN64\Rally '99 (J) [b].zip"
move "Rally Challenge 2000 (USA).zip" "_REN64\Rally Challenge 2000 (U).zip"
move "Rampage - World Tour (Europe).zip" "_REN64\Rampage - World Tour (E).zip"
move "Rampage - World Tour (USA).zip" "_REN64\Rampage - World Tour (U).zip"
move "Rampage 2 - Universal Tour (Europe).zip" "_REN64\Rampage 2 - Universal Tour (E).zip"
move "Rampage 2 - Universal Tour (USA).zip" "_REN64\Rampage 2 - Universal Tour (U).zip"
move "Rat Attack (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN64\Rat Attack (E) (EnFrDeEsItNl).zip"
move "Rat Attack! (USA) (En,Fr,De,Es,It,Nl).zip" "_REN64\Rat Attack! (U) (EnFrDeEsItNl).zip"
move "Rayman 2 - The Great Escape (Europe) (En,Fr,De,Es,It).zip" "_REN64\Rayman2-TheGreatEscape(E)(EnFrDeEsIt).zip"
move "Rayman 2 - The Great Escape (USA) (En,Fr,De,Es,It).zip" "_REN64\Rayman2-TheGreatEscape(U)(EnFrDeEsIt).zip"
move "Razmoket, Les - La Chasse aux Tresors (France).zip" "_REN64\RazmoketLes-LaChasseauxTresors(F).zip"
move "Razor Freestyle Scooter (USA).zip" "_REN64\Razor Freestyle Scooter (U).zip"
move "Re-Volt (Europe) (En,Fr,De,Es).zip" "_REN64\Re-Volt (E) (EnFrDeEs).zip"
move "Re-Volt (USA).zip" "_REN64\Re-Volt (U).zip"
move "Ready 2 Rumble Boxing (Europe) (En,Fr,De).zip" "_REN64\Ready 2 Rumble Boxing (E) (EnFrDe).zip"
move "Ready 2 Rumble Boxing (USA).zip" "_REN64\Ready 2 Rumble Boxing (U).zip"
move "Ready 2 Rumble Boxing - Round 2 (USA).zip" "_REN64\Ready 2 Rumble Boxing - Round 2 (U).zip"
move "Resident Evil 2 (Europe) (En,Fr).zip" "_REN64\Resident Evil 2 (E) (EnFr).zip"
move "Resident Evil 2 (USA) (Rev 1).zip" "_REN64\Resident Evil 2 (U) (Rev 1).zip"
move "Resident Evil 2 (USA).zip" "_REN64\Resident Evil 2 (U).zip"
move "Road Rash 64 (Europe) (Beta) (1999-10-12).zip" "_REN64\Road Rash 64 (E) (Beta) (1999-10-12).zip"
move "Road Rash 64 (Europe).zip" "_REN64\Road Rash 64 (E).zip"
move "Road Rash 64 (USA).zip" "_REN64\Road Rash 64 (U).zip"
move "Roadsters (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN64\Roadsters (E) (EnFrDeEsItNl).zip"
move "Roadsters (USA) (En,Fr,Es).zip" "_REN64\Roadsters (U) (EnFrEs).zip"
move "Robot Poncots 64 - 7tsu no Umi no Caramel (Japan).zip" "_REN64\RobotPoncots64-7tsunoUminoCaramel(J).zip"
move "Robotech - Crystal Dreams (USA) (Proto 1).zip" "_REN64\Robotech-CrystalDreams(U)(Proto1).zip"
move "Robotech - Crystal Dreams (USA) (Proto 2).zip" "_REN64\Robotech-CrystalDreams(U)(Proto2).zip"
move "Robotron 64 (Europe).zip" "_REN64\Robotron 64 (E).zip"
move "Robotron 64 (USA).zip" "_REN64\Robotron 64 (U).zip"
move "Rocket - Robot on Wheels (Europe) (Beta) (1999-09-29).zip" "_REN64\RocketRobotonWheels(E)(Beta)(19990929).zip"
move "Rocket - Robot on Wheels (Europe) (En,Fr,De).zip" "_REN64\Rocket - Robot on Wheels (E) (EnFrDe).zip"
move "Rocket - Robot on Wheels (USA).zip" "_REN64\Rocket - Robot on Wheels (U).zip"
move "Rockman Dash - Hagane no Boukenshin (Japan).zip" "_REN64\RockmanDash-HaganenoBoukenshin(J).zip"
move "Ronaldinho's Soccer 64 (Brazil) (Pirate).zip" "_REN64\Ronaldinho's Soccer 64 (B) (Pirate).zip"
move "RR64 - Ridge Racer 64 (Europe).zip" "_REN64\RR64 - Ridge Racer 64 (E).zip"
move "RR64 - Ridge Racer 64 (USA).zip" "_REN64\RR64 - Ridge Racer 64 (U).zip"
move "RTL World League Soccer 2000 (Germany).zip" "_REN64\RTL World League Soccer 2000 (G).zip"
move "Rugrats - Die grosse Schatzsuche (Germany).zip" "_REN64\Rugrats - Die grosse Schatzsuche (G).zip"
move "Rugrats - Scavenger Hunt (USA).zip" "_REN64\Rugrats - Scavenger Hunt (U).zip"
move "Rugrats - Treasure Hunt (Europe).zip" "_REN64\Rugrats - Treasure Hunt (E).zip"
move "Rugrats in Paris - The Movie (Europe).zip" "_REN64\Rugrats in Paris - The Movie (E).zip"
move "Rugrats in Paris - The Movie (USA).zip" "_REN64\Rugrats in Paris - The Movie (U).zip"
move "Rush 2 - Extreme Racing USA (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN64\Rush2ExtremeRacingUSA(E)(EnFrDeEsItNl).zip"
move "Rush 2 - Extreme Racing USA (USA).zip" "_REN64\Rush 2 - Extreme Racing USA (U).zip"
move "S.C.A.R.S. (Europe) (En,Fr,De).zip" "_REN64\S.C.A.R.S. (E) (EnFrDe).zip"
move "S.C.A.R.S. (USA).zip" "_REN64\S.C.A.R.S. (U).zip"
move "Saikyou Habu Shougi (Japan).zip" "_REN64\Saikyou Habu Shougi (J).zip"
move "San Francisco Rush - Extreme Racing (Europe) (En,Fr,De).zip" "_REN64\SanFranciscoRushExtremeRacing(E).zip"
move "San Francisco Rush - Extreme Racing (USA) (En,Fr,De) (Rev 1).zip" "_REN64\SanFranciscoRushExtremeRacing(U)(Rev1).zip"
move "San Francisco Rush - Extreme Racing (USA) (En,Fr,De).zip" "_REN64\SanFranciscoRushExtremeRacing(U).zip"
move "San Francisco Rush 2049 (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN64\SanFranciscoRush2049(E)(EnFrDeEsItNl).zip"
move "San Francisco Rush 2049 (USA).zip" "_REN64\San Francisco Rush 2049 (U).zip"
move "Scooby-Doo! - Classic Creep Capers (Europe).zip" "_REN64\Scooby-Doo! - Classic Creep Capers (E).zip"
move "Scooby-Doo! - Classic Creep Capers (USA) (Rev 1).zip" "_REN64\ScoobyDoo!ClassicCreepCapers(U)(Rev1).zip"
move "Scooby-Doo! - Classic Creep Capers (USA).zip" "_REN64\Scooby-Doo! - Classic Creep Capers (U).zip"
move "SD Hiryuu no Ken Densetsu (Japan).zip" "_REN64\SD Hiryuu no Ken Densetsu (J).zip"
move "Sesame Street - Elmo's Letter Adventure (USA).zip" "_REN64\SesameStreet-Elmo'sLetterAdventure(U).zip"
move "Sesame Street - Elmo's Number Journey (USA).zip" "_REN64\SesameStreet-Elmo'sNumberJourney(U).zip"
move "Shadow Man (Brazil).zip" "_REN64\Shadow Man (B).zip"
move "Shadow Man (Europe) (En,Es,It).zip" "_REN64\Shadow Man (E) (EnEsIt).zip"
move "Shadow Man (France).zip" "_REN64\Shadow Man (F).zip"
move "Shadow Man (Germany).zip" "_REN64\Shadow Man (G).zip"
move "Shadow Man (USA).zip" "_REN64\Shadow Man (U).zip"
move "Shadowgate 64 - Trials of the Four Towers (Europe) (Es,It).zip" "_REN64\Shadowgate64TrialsoftheFourTowers(E).zip"
move "Shadowgate 64 - Trials of the Four Towers (Europe) (Fr,De,Nl).zip" "_REN64\Shadowgate64TrialsoftheFourTowers(E)_0.zip"
move "Shadowgate 64 - Trials of the Four Towers (Europe).zip" "_REN64\Shadowgate64-TrialsoftheFourTowers(E).zip"
move "Shadowgate 64 - Trials of the Four Towers (Japan).zip" "_REN64\Shadowgate64-TrialsoftheFourTowers(J).zip"
move "Shadowgate 64 - Trials of the Four Towers (USA) (En,Es).zip" "_REN64\Shadowgate64TrialsoftheFourTowers(U).zip"
move "Shin Nihon Pro Wrestling Toukon Road - Brave Spirits (Japan).zip" "_REN64\ShinNihonProWrestlingToukonRoadBrav(J).zip"
move "Shin Nihon Pro Wrestling Toukon Road 2 - The Next Generation (Japan).zip" "_REN64\ShinNihonProWrestlingToukonRoad2The(J).zip"
move "SimCity 2000 (Japan).zip" "_REN64\SimCity 2000 (J).zip"
move "Snobo Kids (Japan).zip" "_REN64\Snobo Kids (J).zip"
move "Snow Speeder (Japan).zip" "_REN64\Snow Speeder (J).zip"
move "Snowboard Kids (Europe, Australia).zip" "_REN64\Snowboard Kids (E).zip"
move "Snowboard Kids (USA).zip" "_REN64\Snowboard Kids (U).zip"
move "Snowboard Kids 2 (Australia).zip" "_REN64\Snowboard Kids 2 (A).zip"
move "Snowboard Kids 2 (USA).zip" "_REN64\Snowboard Kids 2 (U).zip"
move "Sonic Wings Assault (Japan).zip" "_REN64\Sonic Wings Assault (J).zip"
move "South Park (Brazil).zip" "_REN64\South Park (B).zip"
move "South Park (Europe) (En,Fr,Es).zip" "_REN64\South Park (E) (EnFrEs).zip"
move "South Park (Germany).zip" "_REN64\South Park (G).zip"
move "South Park (USA).zip" "_REN64\South Park (U).zip"
move "South Park - Chef's Luv Shack (Europe).zip" "_REN64\South Park - Chef's Luv Shack (E).zip"
move "South Park Rally (Europe) (Beta).zip" "_REN64\South Park Rally (E) (Beta).zip"
move "South Park Rally (Europe).zip" "_REN64\South Park Rally (E).zip"
move "South Park Rally (USA).zip" "_REN64\South Park Rally (U).zip"
move "Space Dynamites (Japan).zip" "_REN64\Space Dynamites (J).zip"
move "Space Invaders (USA).zip" "_REN64\Space Invaders (U).zip"
move "SpaceStation Silicon Valley (Europe) (En,Fr,De,Es,It,Nl,Pt).zip" "_REN64\SpaceStationSiliconValley(E).zip"
move "SpaceStation Silicon Valley (USA).zip" "_REN64\SpaceStation Silicon Valley (U).zip"
move "Spider-Man (USA).zip" "_REN64\Spider-Man (U).zip"
move "Star Fox 64 (Japan).zip" "_REN64\Star Fox 64 (J).zip"
move "Star Fox 64 (USA) (Rev 1).zip" "_REN64\Star Fox 64 (U) (Rev 1).zip"
move "Star Fox 64 (USA).zip" "_REN64\Star Fox 64 (U).zip"
move "Star Soldier - Vanishing Earth (Japan).zip" "_REN64\Star Soldier - Vanishing Earth (J).zip"
move "Star Soldier - Vanishing Earth (USA).zip" "_REN64\Star Soldier - Vanishing Earth (U).zip"
move "Star Twins (Japan).zip" "_REN64\Star Twins (J).zip"
move "Star Wars - Rogue Squadron (Europe) (En,Fr,De) (Rev 1).zip" "_REN64\StarWarsRogueSquadron(E)(EnFrDe)(Rev1).zip"
move "Star Wars - Rogue Squadron (Europe) (En,Fr,De).zip" "_REN64\StarWars-RogueSquadron(E)(EnFrDe).zip"
move "Star Wars - Rogue Squadron (USA) (Rev 1).zip" "_REN64\Star Wars - Rogue Squadron (U) (Rev 1).zip"
move "Star Wars - Rogue Squadron (USA).zip" "_REN64\Star Wars - Rogue Squadron (U).zip"
move "Star Wars - Shadows of the Empire (Europe).zip" "_REN64\Star Wars - Shadows of the Empire (E).zip"
move "Star Wars - Shadows of the Empire (USA) (Beta) (1996-10-15).zip" "_REN64\StarWarsShadowsoftheEmpire(U)(Beta).zip"
move "Star Wars - Shadows of the Empire (USA) (Rev 1).zip" "_REN64\StarWars-ShadowsoftheEmpire(U)(Rev1).zip"
move "Star Wars - Shadows of the Empire (USA) (Rev 2).zip" "_REN64\StarWars-ShadowsoftheEmpire(U)(Rev2).zip"
move "Star Wars - Shadows of the Empire (USA) (Rev 3) (Aftermarket) (Unl).zip" "_REN64\StarWarsShadowsoftheEmpi(U)(Rev3)(Unl).zip"
move "Star Wars - Shadows of the Empire (USA).zip" "_REN64\Star Wars - Shadows of the Empire (U).zip"
move "Star Wars - Shutsugeki! Rogue Chuutai (Japan).zip" "_REN64\StarWars-Shutsugeki!RogueChuutai(J).zip"
move "Star Wars - Teikoku no Kage (Japan).zip" "_REN64\Star Wars - Teikoku no Kage (J).zip"
move "Star Wars Episode I - Battle for Naboo (Europe).zip" "_REN64\StarWarsEpisodeI-BattleforNaboo(E).zip"
move "Star Wars Episode I - Battle for Naboo (USA).zip" "_REN64\StarWarsEpisodeI-BattleforNaboo(U).zip"
move "Star Wars Episode I - Racer (Europe) (En,Fr,De).zip" "_REN64\StarWarsEpisodeI-Racer(E)(EnFrDe).zip"
move "Star Wars Episode I - Racer (Japan).zip" "_REN64\Star Wars Episode I - Racer (J).zip"
move "Star Wars Episode I - Racer (USA) (Rev 1) (Aftermarket) (Unl).zip" "_REN64\StarWarsEpisodeIRacer(U)(Rev1)(Unl).zip"
move "Star Wars Episode I - Racer (USA).zip" "_REN64\Star Wars Episode I - Racer (U).zip"
move "StarCraft 64 (Australia).zip" "_REN64\StarCraft 64 (A).zip"
move "StarCraft 64 (Germany) (Proto).zip" "_REN64\StarCraft 64 (G) (Proto).zip"
move "StarCraft 64 (USA) (Beta).zip" "_REN64\StarCraft 64 (U) (Beta).zip"
move "StarCraft 64 (USA).zip" "_REN64\StarCraft 64 (U).zip"
move "Starshot - Space Circus Fever (Europe) (En,Fr,De).zip" "_REN64\Starshot-SpaceCircusFever(E)(EnFrDe).zip"
move "Starshot - Space Circus Fever (USA) (En,Fr,Es).zip" "_REN64\Starshot-SpaceCircusFever(U)(EnFrEs).zip"
move "Stunt Racer 64 (USA).zip" "_REN64\Stunt Racer 64 (U).zip"
move "Super B-Daman - Battle Phoenix 64 (Japan).zip" "_REN64\Super B-Daman - Battle Phoenix 64 (J).zip"
move "Super Bowling (Japan).zip" "_REN64\Super Bowling (J).zip"
move "Super Bowling (USA).zip" "_REN64\Super Bowling (U).zip"
move "Super Mario 64 (Europe) (En,Fr,De).zip" "_REN64\Super Mario 64 (E) (EnFrDe).zip"
move "Super Mario 64 (Japan) (Rev 3) (Shindou Edition).zip" "_REN64\SuperMario64(J)(Rev3)(ShindouEdition).zip"
move "Super Mario 64 (Japan).zip" "_REN64\Super Mario 64 (J).zip"
move "Super Mario 64 (USA).zip" "_REN64\Super Mario 64 (U).zip"
move "Super Robot Spirits (Japan).zip" "_REN64\Super Robot Spirits (J).zip"
move "Super Robot Taisen 64 (Japan).zip" "_REN64\Super Robot Taisen 64 (J).zip"
move "Super Smash Bros. (Australia).zip" "_REN64\Super Smash Bros. (A).zip"
move "Super Smash Bros. (Europe) (En,Fr,De).zip" "_REN64\Super Smash Bros. (E) (EnFrDe).zip"
move "Super Smash Bros. (USA).zip" "_REN64\Super Smash Bros. (U).zip"
move "Super Speed Race 64 (Japan).zip" "_REN64\Super Speed Race 64 (J).zip"
move "Supercross 2000 (Europe) (En,Fr,De).zip" "_REN64\Supercross 2000 (E) (EnFrDe).zip"
move "Supercross 2000 (USA).zip" "_REN64\Supercross 2000 (U).zip"
move "Superman (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN64\Superman (E) (EnFrDeEsItNl).zip"
move "Superman (USA) (Beta) (1998-09-06).zip" "_REN64\Superman (U) (Beta) (1998-09-06).zip"
move "Superman - The New Superman Aventures (USA) (En,Fr,Es).zip" "_REN64\SupermanTheNewSupermanAventures(U).zip"
move "Susume! Taisen Puzzle Dama - Toukon! Marutama Chou (Japan).zip" "_REN64\SusumeTaisenPuzzleDamaToukonMarutam(J).zip"
move "Sydney 2000 (Europe) (Proto).zip" "_REN64\Sydney 2000 (E) (Proto).zip"
move "Sydney 2000 (USA) (Proto).zip" "_REN64\Sydney 2000 (U) (Proto).zip"
move "Tamiya Racing 64 (USA) (Proto).zip" "_REN64\Tamiya Racing 64 (U) (Proto).zip"
move "Tarzan (Europe).zip" "_REN64\Tarzan (E).zip"
move "Tarzan (France).zip" "_REN64\Tarzan (F).zip"
move "Tarzan (Germany).zip" "_REN64\Tarzan (G).zip"
move "Tarzan (USA).zip" "_REN64\Tarzan (U).zip"
move "Taz Express (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN64\Taz Express (E) (EnFrDeEsItNl).zip"
move "Taz Express (USA) (Proto) (2000-05-15).zip" "_REN64\Taz Express (U) (Proto) (2000-05-15).zip"
move "Telefoot Soccer 2000 (France).zip" "_REN64\Telefoot Soccer 2000 (F).zip"
move "Tetris 64 (Japan) (En).zip" "_REN64\Tetris 64 (J) (En).zip"
move "Tetrisphere (Europe).zip" "_REN64\Tetrisphere (E).zip"
move "Tetrisphere (USA).zip" "_REN64\Tetrisphere (U).zip"
move "TG Rally 2 (Europe).zip" "_REN64\TG Rally 2 (E).zip"
move "Tigger's Honey Hunt (Europe) (En,Fr,De,Es,It,Nl,Da).zip" "_REN64\Tigger'sHoneyHunt(E)(EnFrDeEsItNlDa).zip"
move "Tigger's Honey Hunt (USA).zip" "_REN64\Tigger's Honey Hunt (U).zip"
move "Tom and Jerry in Fists of Furry (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN64\TomandJerryinFistsofFurry(E).zip"
move "Tom and Jerry in Fists of Furry (USA).zip" "_REN64\Tom and Jerry in Fists of Furry (U).zip"
move "Tom Clancy's Rainbow Six (Europe).zip" "_REN64\Tom Clancy's Rainbow Six (E).zip"
move "Tom Clancy's Rainbow Six (France).zip" "_REN64\Tom Clancy's Rainbow Six (F).zip"
move "Tom Clancy's Rainbow Six (Germany).zip" "_REN64\Tom Clancy's Rainbow Six (G).zip"
move "Tom Clancy's Rainbow Six (USA).zip" "_REN64\Tom Clancy's Rainbow Six (U).zip"
move "Tommy Thunder (USA) (Proto) (1997-10-01).zip" "_REN64\Tommy Thunder (U) (Proto) (1997-10-01).zip"
move "Tonic Trouble (Europe) (En,Fr,De,Es,It).zip" "_REN64\Tonic Trouble (E) (EnFrDeEsIt).zip"
move "Tonic Trouble (USA) (Rev 1).zip" "_REN64\Tonic Trouble (U) (Rev 1).zip"
move "Tony Hawk's Pro Skater (USA) (Beta).zip" "_REN64\Tony Hawk's Pro Skater (U) (Beta).zip"
move "Tony Hawk's Pro Skater (USA) (Rev 1).zip" "_REN64\Tony Hawk's Pro Skater (U) (Rev 1).zip"
move "Tony Hawk's Pro Skater (USA).zip" "_REN64\Tony Hawk's Pro Skater (U).zip"
move "Tony Hawk's Pro Skater 2 (Europe).zip" "_REN64\Tony Hawk's Pro Skater 2 (E).zip"
move "Tony Hawk's Pro Skater 2 (USA) (Beta) (2001-04-20).zip" "_REN64\TonyHawksProSkater2(U)(Beta)(20010420).zip"
move "Tony Hawk's Pro Skater 2 (USA) (v012) (Beta) (2001-06-04).zip" "_REN64\TonyHawksProSkater2(U)(Beta).zip"
move "Tony Hawk's Pro Skater 2 (USA).zip" "_REN64\Tony Hawk's Pro Skater 2 (U).zip"
move "Tony Hawk's Pro Skater 3 (USA).zip" "_REN64\Tony Hawk's Pro Skater 3 (U).zip"
move "Tony Hawk's Skateboarding (Europe).zip" "_REN64\Tony Hawk's Skateboarding (E).zip"
move "Toon Panic (Japan) (Proto).zip" "_REN64\Toon Panic (J) (Proto).zip"
move "Top Gear Hyper Bike (Europe).zip" "_REN64\Top Gear Hyper Bike (E).zip"
move "Top Gear Hyper Bike (Japan).zip" "_REN64\Top Gear Hyper Bike (J).zip"
move "Top Gear Hyper-Bike (USA) (Beta).zip" "_REN64\Top Gear Hyper-Bike (U) (Beta).zip"
move "Top Gear Hyper-Bike (USA).zip" "_REN64\Top Gear Hyper-Bike (U).zip"
move "Top Gear Overdrive (Europe).zip" "_REN64\Top Gear Overdrive (E).zip"
move "Top Gear Overdrive (Japan).zip" "_REN64\Top Gear Overdrive (J).zip"
move "Top Gear Overdrive (USA).zip" "_REN64\Top Gear Overdrive (U).zip"
move "Top Gear Rally (Asia) (En).zip" "_REN64\Top Gear Rally (Asia) (En).zip"
move "Top Gear Rally (Europe).zip" "_REN64\Top Gear Rally (E).zip"
move "Top Gear Rally (Japan).zip" "_REN64\Top Gear Rally (J).zip"
move "Top Gear Rally (USA).zip" "_REN64\Top Gear Rally (U).zip"
move "Top Gear Rally 2 (Europe) (Beta) (1999-08-31).zip" "_REN64\TopGearRally2(E)(Beta)(1999-08-31).zip"
move "Top Gear Rally 2 (Europe).zip" "_REN64\Top Gear Rally 2 (E).zip"
move "Top Gear Rally 2 (Japan).zip" "_REN64\Top Gear Rally 2 (J).zip"
move "Top Gear Rally 2 (USA).zip" "_REN64\Top Gear Rally 2 (U).zip"
move "Toy Story 2 - Buzz l'Eclair a la Rescousse! (France).zip" "_REN64\ToyStory2-Buzzl'EclairalaRescousse!(F).zip"
move "Toy Story 2 - Buzz Lightyear to the Rescue! (Europe).zip" "_REN64\ToyStory2-BuzzLightyeartotheRescue!(E).zip"
move "Toy Story 2 - Buzz Lightyear to the Rescue! (USA) (Rev 1).zip" "_REN64\ToyStory2BuzzLightyeartotheRe(U)(Rev1).zip"
move "Toy Story 2 - Buzz Lightyear to the Rescue! (USA).zip" "_REN64\ToyStory2-BuzzLightyeartotheRescue!(U).zip"
move "Toy Story 2 - Captain Buzz Lightyear auf Rettungsmission! (Germany) (Rev 1).zip" "_REN64\ToyStory2CaptainBuzzLightyear(G)(Rev1).zip"
move "Toy Story 2 - Captain Buzz Lightyear auf Rettungsmission! (Germany).zip" "_REN64\ToyStory2CaptainBuzzLightyearaufRet(G).zip"
move "Transformers - Beast Wars Metals 64 (Japan).zip" "_REN64\Transformers-BeastWarsMetals64(J).zip"
move "Transformers - Beast Wars Transmetals (USA).zip" "_REN64\Transformers-BeastWarsTransmetals(U).zip"
move "Triple Play 2000 (USA).zip" "_REN64\Triple Play 2000 (U).zip"
move "Tsumi to Batsu - Hoshi no Keishousha (Japan).zip" "_REN64\TsumitoBatsu-HoshinoKeishousha(J).zip"
move "Turok - Dinosaur Hunter (Europe) (Rev 2).zip" "_REN64\Turok - Dinosaur Hunter (E) (Rev 2).zip"
move "Turok - Dinosaur Hunter (Europe).zip" "_REN64\Turok - Dinosaur Hunter (E).zip"
move "Turok - Dinosaur Hunter (Germany) (Rev 1).zip" "_REN64\Turok - Dinosaur Hunter (G) (Rev 1).zip"
move "Turok - Dinosaur Hunter (Germany).zip" "_REN64\Turok - Dinosaur Hunter (G).zip"
move "Turok - Dinosaur Hunter (USA).zip" "_REN64\Turok - Dinosaur Hunter (U).zip"
move "Turok - Legenden des Verlorenen Landes (Germany).zip" "_REN64\Turok-LegendendesVerlorenenLandes(G).zip"
move "Turok - Rage Wars (Europe) (En,Fr,It).zip" "_REN64\Turok - Rage Wars (E) (EnFrIt).zip"
move "Turok - Rage Wars (Europe).zip" "_REN64\Turok - Rage Wars (E).zip"
move "Turok - Rage Wars (USA) (Rev 1).zip" "_REN64\Turok - Rage Wars (U) (Rev 1).zip"
move "Turok - Rage Wars (USA).zip" "_REN64\Turok - Rage Wars (U).zip"
move "Turok 2 - Seeds of Evil (Europe) (Demo) (Kiosk).zip" "_REN64\Turok2-SeedsofEvil(E)(Demo)(Kiosk).zip"
move "Turok 2 - Seeds of Evil (Europe) (En,Fr,Es,It).zip" "_REN64\Turok 2 - Seeds of Evil (E) (EnFrEsIt).zip"
move "Turok 2 - Seeds of Evil (Europe).zip" "_REN64\Turok 2 - Seeds of Evil (E).zip"
move "Turok 2 - Seeds of Evil (Germany).zip" "_REN64\Turok 2 - Seeds of Evil (G).zip"
move "Turok 2 - Seeds of Evil (USA).zip" "_REN64\Turok 2 - Seeds of Evil (U).zip"
move "Turok 3 - Shadow of Oblivion (Europe) (Beta) (2000-05-31).zip" "_REN64\Turok3ShadowofOblivion(E)(Beta).zip"
move "Turok 3 - Shadow of Oblivion (Europe) (Beta) (2000-06-06) [b].zip" "_REN64\Turok3ShadowofOblivion(E)(Beta)_0.zip"
move "Turok 3 - Shadow of Oblivion (Europe) (Beta) (2000-07-10) [b].zip" "_REN64\Turok3ShadowofOblivion(E)(Beta)_0_1.zip"
move "Turok 3 - Shadow of Oblivion (Europe) (Beta) (2000-07-16).zip" "_REN64\Turok3ShadowofOblivion(E)(Beta)_0_1_2.zip"
move "Turok 3 - Shadow of Oblivion (Europe).zip" "_REN64\Turok 3 - Shadow of Oblivion (E).zip"
move "Turok 3 - Shadow of Oblivion (USA) (Beta) (2000-06-26).zip" "_REN64\Turok3ShadowofOblivion(U)(Beta).zip"
move "Turok 3 - Shadow of Oblivion (USA).zip" "_REN64\Turok 3 - Shadow of Oblivion (U).zip"
move "Twisted Edge - Extreme Snowboarding (USA).zip" "_REN64\TwistedEdge-ExtremeSnowboarding(U).zip"
move "Twisted Edge - Snowboarding (Europe).zip" "_REN64\Twisted Edge - Snowboarding (E).zip"
move "Utchan Nanchan no Hono no Challenger - Denryuu Ira Ira Bou (Japan).zip" "_REN64\UtchanNanchannoHononoChallengerDenr(J).zip"
move "V-Rally Edition 99 (Europe) (En,Fr,De).zip" "_REN64\V-Rally Edition 99 (E) (EnFrDe).zip"
move "V-Rally Edition 99 (Japan).zip" "_REN64\V-Rally Edition 99 (J).zip"
move "V-Rally Edition 99 (USA).zip" "_REN64\V-Rally Edition 99 (U).zip"
move "Viewpoint 2064 (Japan) (Proto).zip" "_REN64\Viewpoint 2064 (J) (Proto).zip"
move "Vigilante 8 (Europe).zip" "_REN64\Vigilante 8 (E).zip"
move "Vigilante 8 (France).zip" "_REN64\Vigilante 8 (F).zip"
move "Vigilante 8 (Germany).zip" "_REN64\Vigilante 8 (G).zip"
move "Vigilante 8 (USA).zip" "_REN64\Vigilante 8 (U).zip"
move "Vigilante 8 - 2nd Offense (Europe).zip" "_REN64\Vigilante 8 - 2nd Offense (E).zip"
move "Vigilante 8 - 2nd Offense (USA).zip" "_REN64\Vigilante 8 - 2nd Offense (U).zip"
move "Violence Killer - Turok New Generation (Japan).zip" "_REN64\ViolenceKiller-TurokNewGeneration(J).zip"
move "Virtual Chess 64 (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN64\Virtual Chess 64 (E) (EnFrDeEsItNl).zip"
move "Virtual Chess 64 (USA) (En,Fr,Es).zip" "_REN64\Virtual Chess 64 (U) (EnFrEs).zip"
move "Virtual Pool 64 (Europe).zip" "_REN64\Virtual Pool 64 (E).zip"
move "Virtual Pool 64 (USA).zip" "_REN64\Virtual Pool 64 (U).zip"
move "Virtual Pro Wrestling 2 - Oudou Keishou (Japan).zip" "_REN64\VirtualProWrestling2-OudouKeishou(J).zip"
move "Virtual Pro Wrestling 64 (Japan).zip" "_REN64\Virtual Pro Wrestling 64 (J).zip"
move "Waialae Country Club - True Golf Classics (Europe) (Rev 1).zip" "_REN64\WaialaeCountryClubTrueGolfCla(E)(Rev1).zip"
move "Waialae Country Club - True Golf Classics (Europe).zip" "_REN64\WaialaeCountryClub-TrueGolfClassics(E).zip"
move "Waialae Country Club - True Golf Classics (USA) (Rev 1).zip" "_REN64\WaialaeCountryClubTrueGolfCla(U)(Rev1).zip"
move "Waialae Country Club - True Golf Classics (USA).zip" "_REN64\WaialaeCountryClub-TrueGolfClassics(U).zip"
move "War Gods (Europe).zip" "_REN64\War Gods (E).zip"
move "War Gods (USA).zip" "_REN64\War Gods (U).zip"
move "Wave Race 64 - Kawasaki Jet Ski (Europe) (En,De).zip" "_REN64\WaveRace64-KawasakiJetSki(E)(EnDe).zip"
move "Wave Race 64 - Kawasaki Jet Ski (Japan) (Rev 1).zip" "_REN64\WaveRace64-KawasakiJetSki(J)(Rev1).zip"
move "Wave Race 64 - Kawasaki Jet Ski (Japan) (Rev 2) (Shindou Edition).zip" "_REN64\WaveRace64KawasakiJetSki(J)(Rev2).zip"
move "Wave Race 64 - Kawasaki Jet Ski (Japan).zip" "_REN64\Wave Race 64 - Kawasaki Jet Ski (J).zip"
move "Wave Race 64 - Kawasaki Jet Ski (USA) (Rev 1).zip" "_REN64\WaveRace64-KawasakiJetSki(U)(Rev1).zip"
move "Wave Race 64 - Kawasaki Jet Ski (USA).zip" "_REN64\Wave Race 64 - Kawasaki Jet Ski (U).zip"
move "Wayne Gretzky's 3D Hockey '98 (Europe) (En,Fr,De,Es).zip" "_REN64\WayneGretzky's3DHockey'98(E)(EnFrDeEs).zip"
move "Wayne Gretzky's 3D Hockey '98 (USA).zip" "_REN64\Wayne Gretzky's 3D Hockey '98 (U).zip"
move "Wayne Gretzky's 3D Hockey (Europe) (En,Fr,De,Es).zip" "_REN64\WayneGretzky's3DHockey(E)(EnFrDeEs).zip"
move "Wayne Gretzky's 3D Hockey (Japan).zip" "_REN64\Wayne Gretzky's 3D Hockey (J).zip"
move "Wayne Gretzky's 3D Hockey (USA) (Rev 1).zip" "_REN64\Wayne Gretzky's 3D Hockey (U) (Rev 1).zip"
move "Wayne Gretzky's 3D Hockey (USA).zip" "_REN64\Wayne Gretzky's 3D Hockey (U).zip"
move "WCW Backstage Assault (USA).zip" "_REN64\WCW Backstage Assault (U).zip"
move "WCW Mayhem (Europe).zip" "_REN64\WCW Mayhem (E).zip"
move "WCW Mayhem (USA).zip" "_REN64\WCW Mayhem (U).zip"
move "WCW Nitro (USA).zip" "_REN64\WCW Nitro (U).zip"
move "WCW vs. nWo - World Tour (Europe).zip" "_REN64\WCW vs. nWo - World Tour (E).zip"
move "WCW vs. nWo - World Tour (USA) (Rev 1).zip" "_REN64\WCW vs. nWo - World Tour (U) (Rev 1).zip"
move "WCW vs. nWo - World Tour (USA).zip" "_REN64\WCW vs. nWo - World Tour (U).zip"
move "WCW-nWo Revenge (Europe).zip" "_REN64\WCW-nWo Revenge (E).zip"
move "WCW-nWo Revenge (USA).zip" "_REN64\WCW-nWo Revenge (U).zip"
move "Wetrix (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN64\Wetrix (E) (EnFrDeEsItNl).zip"
move "Wetrix (Japan).zip" "_REN64\Wetrix (J).zip"
move "Whack 'n' Roll (USA) (Beta) (1998-02-05).zip" "_REN64\Whack 'n' Roll (U) (Beta) (1998-02-05).zip"
move "Wheel of Fortune (USA).zip" "_REN64\Wheel of Fortune (U).zip"
move "Wild Choppers (Japan).zip" "_REN64\Wild Choppers (J).zip"
move "Wildwaters (USA) (Proto) (1999-06-15).zip" "_REN64\Wildwaters (U) (Proto) (1999-06-15).zip"
move "WinBack (Japan) (Rev 1).zip" "_REN64\WinBack (J) (Rev 1).zip"
move "WinBack (Japan).zip" "_REN64\WinBack (J).zip"
move "WinBack - Covert Operations (USA).zip" "_REN64\WinBack - Covert Operations (U).zip"
move "Wipeout 64 (Europe) (Beta).zip" "_REN64\Wipeout 64 (E) (Beta).zip"
move "Wipeout 64 (Europe).zip" "_REN64\Wipeout 64 (E).zip"
move "Wipeout 64 (USA).zip" "_REN64\Wipeout 64 (U).zip"
move "Wonder Project J2 - Koruro no Mori no Jozet (Japan).zip" "_REN64\WonderProjectJ2-KoruronoMorinoJozet(J).zip"
move "World Cup 98 (Europe) (En,Fr,De,Es,It,Nl,Sv,Da).zip" "_REN64\World Cup 98 (E) (EnFrDeEsItNlSvDa).zip"
move "World Cup 98 (USA) (En,Fr,De,Es,It,Nl,Sv,Da).zip" "_REN64\World Cup 98 (U) (EnFrDeEsItNlSvDa).zip"
move "World Driver Championship (Europe) (En,Fr,De,Es,It).zip" "_REN64\WorldDriverChampionship(E)(EnFrDeEsIt).zip"
move "World Driver Championship (USA).zip" "_REN64\World Driver Championship (U).zip"
move "Worms Armageddon (Europe) (En,Fr,De,Es,It,Nl).zip" "_REN64\Worms Armageddon (E) (EnFrDeEsItNl).zip"
move "Worms Armageddon (USA) (En,Fr,Es).zip" "_REN64\Worms Armageddon (U) (EnFrEs).zip"
move "WWF Attitude (Europe).zip" "_REN64\WWF Attitude (E).zip"
move "WWF Attitude (Germany).zip" "_REN64\WWF Attitude (G).zip"
move "WWF Attitude (USA).zip" "_REN64\WWF Attitude (U).zip"
move "WWF No Mercy (Europe) (Rev 1).zip" "_REN64\WWF No Mercy (E) (Rev 1).zip"
move "WWF No Mercy (Europe).zip" "_REN64\WWF No Mercy (E).zip"
move "WWF No Mercy (USA) (Rev 1).zip" "_REN64\WWF No Mercy (U) (Rev 1).zip"
move "WWF No Mercy (USA).zip" "_REN64\WWF No Mercy (U).zip"
move "WWF War Zone (Europe).zip" "_REN64\WWF War Zone (E).zip"
move "WWF War Zone (USA).zip" "_REN64\WWF War Zone (U).zip"
move "WWF WrestleMania 2000 (Europe).zip" "_REN64\WWF WrestleMania 2000 (E).zip"
move "WWF WrestleMania 2000 (Japan).zip" "_REN64\WWF WrestleMania 2000 (J).zip"
move "WWF WrestleMania 2000 (USA).zip" "_REN64\WWF WrestleMania 2000 (U).zip"
move "X'treme Roller (USA) (Proto).zip" "_REN64\X'treme Roller (U) (Proto).zip"
move "Xena - Warrior Princess - The Talisman of Fate (Europe).zip" "_REN64\XenaWarriorPrincessTheTalismanofFat(E).zip"
move "Xena - Warrior Princess - The Talisman of Fate (USA).zip" "_REN64\XenaWarriorPrincessTheTalismanofFat(U).zip"
move "Yakouchuu II - Satsujin Kouro (Japan).zip" "_REN64\Yakouchuu II - Satsujin Kouro (J).zip"
move "Yoshi Story (Japan).zip" "_REN64\Yoshi Story (J).zip"
move "Yoshi's Story (Europe) (En,Fr,De).zip" "_REN64\Yoshi's Story (E) (EnFrDe).zip"
move "Yoshi's Story (USA) (En,Ja).zip" "_REN64\Yoshi's Story (U) (EnJa).zip"
move "Yuke Yuke!! Trouble Makers (Japan).zip" "_REN64\Yuke Yuke!! Trouble Makers (J).zip"
move "Zelda no Densetsu - Mujura no Kamen (Japan) (GameCube).zip" "_REN64\ZeldanoDensetsuMujuranoKamen(J)(GC).zip"
move "Zelda no Densetsu - Mujura no Kamen (Japan) (Rev 1).zip" "_REN64\ZeldanoDensetsu-MujuranoKamen(J)(Rev1).zip"
move "Zelda no Densetsu - Mujura no Kamen (Japan).zip" "_REN64\ZeldanoDensetsu-MujuranoKamen(J).zip"
move "Zelda no Densetsu - Toki no Ocarina (Japan) (GameCube, Zelda Collection).zip" "_REN64\ZeldanoDensetsuTokinoOcarina(J)(GC).zip"
move "Zelda no Densetsu - Toki no Ocarina GC (Japan) (GameCube).zip" "_REN64\ZeldanoDensetsuTokinoOcarinaGC(J)(GC).zip"
move "Zelda no Densetsu - Toki no Ocarina GC Ura (Japan) (GameCube).zip" "_REN64\ZeldanoDensetsuTokinoOcarinaGCU(J)(GC).zip"
move "Zool - Majuu Tsukai Densetsu (Japan).zip" "_REN64\Zool - Majuu Tsukai Densetsu (J).zip"
